### ISSUE TITLE
{Legacy Build} Schematic not pasting on clear

### ISSUE THREAD

**Issue by DaRiches** [IntellectualSites/PlotSquared#2366] opened 2019-05-22 18:43 UTC
http://prntscr.com/ns0zoj

**Comment by AeSix** [comment] 2019-05-22 19:25
Well, I was gonna yell at you for not filling out the form properly, but you're just doing as @MattBDev told you to. 
Also, posting this so other issue moderators know and don't yell at you :)

**Comment by DaRiches** [comment] 2019-05-22 19:27
👌

**Comment by AeSix** [comment] 2019-05-24 12:51
@MattBDev  could this be related to https://github.com/IntellectualSites/PlotSquared/issues/2349 as well?

**Comment by AeSix** [comment] 2019-07-30 12:06
Without full information, this sounds like yet another duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2375
closing.

**Closed by AeSix** 2019-07-30 12:06 UTC
Labels: Approved
