### ISSUE TITLE
/plot download on simple plot doesn't work fully

### ISSUE THREAD

**Issue by AnonymioD** [IntellectualSites/PlotSquared#3548] opened 2022-03-17 18:06 UTC
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Hello

When /plot done then /plot download (unmerged plot, of course)
For example: plot 1 and plot 2
Plot 1 (new plot) => Download link created
Plot 2 (exists since long time) => Can't generate the link
(same probleme for other plots exist since long time)

Tests to reproduce the un-downloadable for Plot2 :
- Same flags on new plot
- Same biome on new plot
- World Editing on new plot

Problem: Cannot generate download link on older plots (at least since few months)
Note: Same problem before 6.6.1, just tested on the last version and it's still going on

### To Reproduce

(seems to generate error on older plots..)
1- /plot done
2- /plot download

### Expected behaviour

3- Download link created

### Error log (if applicable)

https://paste.gg/p/anonymous/ca9efffcb79b4c5eb5d0bed11543b362

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ed778d7f237c404da0d10aa0238c1cef

### PlotSquared Version

PlotSquared-6.6.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

17.03 18:54:22 [Server] ERROR [PlotSquared/PlotUploader] Failed to upload schematic
17.03 18:54:22 [Server] INFO java.util.concurrent.CompletionException: com.plotsquared.core.arkitektonika.exceptions.InvalidFormatException: Failed to upload '/upload'. Code: 400 (Bad Request). Reason: Uploaded file is not of valid NBT format

_(check "Error log" for complete consol error)_

**Comment by NotMyFault** [comment] 2022-03-20 15:51
Duplicate of https://github.com/IntellectualSites/Arkitektonika/issues/12

**Closed by NotMyFault** 2022-03-20 15:51 UTC
Labels: Invalid
