### ISSUE TITLE
Could not pass event EntityCombustByEntityEvent to PlotSquared (1.11)

### ISSUE THREAD

**Issue by SioWolf** [IntellectualSites/PlotSquared#1432] opened 2016-11-20 07:45 UTC
http://pastebin.com/ZPC1SWcf

You will see in this pastebin that there is an error involving PlotSquared and entity events.

After some testing it seems to involve the fire/flame enchant. If applied to a weapon or bow, whenever you attack a mob the console is spammed with that error.

**Comment by MattBDev** [comment] 2016-11-21 00:50
Duplicate of #1431

**Closed by MattBDev** 2016-11-21 00:50 UTC
