### ISSUE TITLE
Merge bug

### ISSUE THREAD

**Issue by MinimiTyler** [IntellectualSites/PlotSquared#2735] opened 2020-03-29 18:29 UTC
I have a problem with merging the plots.
If i merge 2 Plots the merge counts as 2 plots but its one plot.
Pls I need help.

**Comment by dordsor21** [comment] 2020-03-29 18:30
That is intended behaviour. Open an issue at https://github.com/IntellectualSites/PlotSquaredSuggestions to add a config option to make merged plots count as one.

**Closed by dordsor21** 2020-03-29 18:30 UTC
Labels: [?] Testing Required
