### ISSUE TITLE
"block-ignition" by mobs / blocks don't work in merged plots

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/PlotSquared#2719] opened 2020-03-21 23:10 UTC
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

settings.yml: https://pastebin.com/rwBd5n1i
worlds.yml: https://pastebin.com/Tk6xEbuW
PlotSquared.use_THIS.yml: https://pastebin.com/anGR1W9e

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
[23:55:25 INFO]: This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[23:55:25 INFO]: Checking version, please wait...
[23:55:25 INFO]: Previous version: git-Paper-142 (MC: 1.15.2)
[23:55:25 INFO]: You are running the latest version
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [x] WorldEdit version: 7.1.0-SNAPSHOT;4822-a27ade5

### Description of the problem:

If I set the block-ignition true - block ignition not work on the merged plot.

### How to replicate:

1. Claim 2 plots.
2. Merge 2 plots.
3. Set block-ignition true flag.
4. Test the dispenser with flint and steel on the 2 plots.
https://www.youtube.com/watch?v=trnVnnxsljc

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

![2020-03-22_00 03 21](https://user-images.githubusercontent.com/8324198/77238474-98413000-6bd0-11ea-9eba-fe70a2833111.png)

for short (20 lines or less) text blobs, or a paste service for large blobs -->

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment] 2020-03-29 11:47
The problem is not the flag byself: If I use flint_and_steel by hand I can ignite all blocks in the plot.

Only the ignition-feature of blocks (dispenser + "flint_and_steel" or "fire_charge") or from mobs (blaze) have this problem.


![2020-03-29_13 36 41](https://user-images.githubusercontent.com/4140635/77848100-9673ff80-71c2-11ea-954c-ec825d8bdfd9.png)

**Comment by Sauilitired** [comment] 2020-04-08 15:05
I've tested this and block ignition works in merged plots as long as you're not standing in a section that previously belonged to the road.

**Closed** 2020-04-08 15:15 UTC
Labels: [!] Bug
