### ISSUE TITLE
Plot border block-update for e.g. "/p clear"

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#3054] opened 2021-05-19 21:36 UTC
**This Feature Request is a copy of https://issues.intellectualsites.com/issue/PS-218 by Theosis**

### What feature do you want to see added?

When a plot is being cleared, blocks get removed but block updates do not happen - similar to how in WorldEdit you can choose, using "//perf", whether or not to do block updates after operations.

I discovered that this was the case because the walls of my plot are iron bars, and clearing a plot when there are blocks adjacent to them results in them retaining their "attached" block state. These screenshots should describe what I mean:

Before "/plot clear":

![grafik](https://user-images.githubusercontent.com/4140635/118887524-c5838e00-b8fa-11eb-9568-d093709392ad.png)

After "/plot clear":

![grafik](https://user-images.githubusercontent.com/4140635/118887545-cd433280-b8fa-11eb-8363-95dcbb8575ab.png)

As you can see, the iron bars stay "stuck out" as if there are blocks near them. This would not happen if "/plot clear" caused block updates. The phenomenon can be replicated using WorldEdit if you disable block updates with the "//perf" command.

### Are there any alternatives?

-

### Anything else?

**How to replicate:**

- Set up a plot world with walls as iron bars, fences or something like that.
- Place blocks on the inside of the plot but attached to the walls.
- Clear the plot using "/plot clear"

**Comment by NotMyFault** [comment] 2021-06-01 20:54
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2996

**Closed by NotMyFault** 2021-06-01 20:54 UTC
Labels: Duplicate
