### ISSUE TITLE
Trident disapear if used on plot that you dont own

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2563] opened 2019-11-08 23:09 UTC
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):
https://athion.net/ISPaster/paste/view/b3c4604a0d7a496385301bb6d6ebf854

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [ ] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [ ] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [ ] Minecraft 1.13.2
- [ ] Minecraft Java Edition *other versions, please specify*:
- [ ] Minecraft Bedrock Edition *speicify version*:

### Server build info: 

``` paste here, between the tick marks, replacing this text ```

### WorldEdit/FAWE versions:

- [ ] FAWE *version*:
- [X] WorldEdit *newest*: 

### Description of the problem:

If i use a trident on plots wich i not own or on wich i have no rights, the trident disappear .

### How to replicate:

Use a trident in plot on wich you cant build

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

Only WorldEdit and P2

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment] 2019-11-08 23:17
Tridents and shot arrows are removed on claimed plots but the event is cancelled un unclaimed plots. The event should be cancelled for claimed plots where the actor is not the owner too.

**Comment by AeSix** [comment] 2019-11-08 23:31
The issue as reported is expected behavior.  Plot flags and/or trust membership should resolve this. 
I believe there is also a permission which can be assigned to staff to bypass these limits, but am currently unsure.

Additionally, next time, please follow all instructions, as the reported issue may pertain to Spigot or Paper only and not the other, or has been resolved with newer patches, etc.  Also, "newest" is not a version, and you among all the people should know this, assuming "Dev" in your name.  Not trying to nit-pick, but the requested information is requested and required for a reason. 

@N0tMyFaultOG - I am unsure as to why you marked this as a bug and did not close it?  Your statement serves only to verify that this is expected behavior.

**Comment by N0tMyFaultOG** [comment] 2019-11-08 23:35
Imagine throwing your loyalty 3 trident on an other users plot and it just gets deleted. That doesn't sound very user friendly. There's also no flag to prevent that iirc. Even if there is, that flag should work the other way around.

**Comment by MattBDev** [comment] 2019-11-09 01:09
I thought there was a 🔱 flag but it wasn't implemented? I could be imagining things.

**Comment by N0tMyFaultOG** [comment] 2019-11-09 10:01
> I thought there was a 🔱 flag but it wasn't implemented? I could be imagining things.

I guess so, there is no trident flag.

**Comment by AeSix** [comment] 2019-11-09 13:14
mark foe next release and merge the Trident flag, with it added enabled in the config?

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sauilitired** [comment] 2019-11-09 17:03
https://github.com/IntellectualSites/PlotSquared/blob/627ecd2b71830a7c9f05abf1ee0a65514611c997/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/listeners/PlayerEvents.java#L450
Code following that line is responsible for the observed behaviour. Tridents are treated like other entities.

`PERMISSION_PROJECTILE_UNOWNED` can be used to allow players to shoot at unowned plots, and `PERMISSION_PROJECTILE_OTHER` to shoot at plots where the player isn't added. 

A possible trident flag would be a feature suggestion. The observed behaviour is intended.

**Closed** 2019-11-09 17:15 UTC
Labels: 1.14.x, [!] Bug
