### ISSUE TITLE
\n new lines in plot greeting flag retain the backslash still

### ISSUE THREAD

**Issue by iLemon** [IntellectualSites/PlotSquared#3832] opened 2022-10-07 12:51 UTC
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Using `\n` in your plot greeting, when it sends it keeps the backspace.
![image](https://user-images.githubusercontent.com/18317307/194557607-8d871686-91fa-45d0-8cca-80b486cc57b4.png)

### To Reproduce

Go on your plot
Type `/p flag set greeting test\ntest2\nhi`

### Expected behaviour

There should not be backslashes from \n

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8a1892603b814a19add4e6f6b632961b

### PlotSquared Version

6.10.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment] 2022-10-07 16:49
Can you try to reproduce that behaviour with the MM format? (`/p flag set greeting test<br>test2<br>hi`)

**Comment by iLemon** [comment] 2022-10-08 12:10
![image](https://user-images.githubusercontent.com/18317307/194706820-5586da1b-1003-43c8-81d2-8274c9225165.png)
That does not work.

**Comment by PierreSchwang** [comment] 2022-10-08 21:26
Works for me at least 
![grafik](https://user-images.githubusercontent.com/27054324/194728305-aa2c0e99-d636-47ef-9fff-8ff8fddf9a5b.png)
Only difference is, that I'm running the build containing changes to string flag parsing (https://github.com/IntellectualSites/PlotSquared/pull/3835) - I guess that'll close this issue as well

**Closed** 2022-10-10 16:41 UTC
Labels: Bug, Under Investigation
