### ISSUE TITLE
Time plot flag not reset if change world

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/PlotSquared#2357] opened 2019-05-13 12:35 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
13.05 14:32:56 [Server] INFO [P2] >> PlotSquared (Version: PlotSquared-4.277)
13.05 14:32:56 [Server] INFO [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
13.05 14:32:56 [Server] INFO [P2] >> Wiki: https://github.com/IntellectualCrafters/PlotSquared/wiki
13.05 14:32:57 [Server] INFO [P2] >> Newest Version: development-builds

**[REQUIRED] Spigot/Paper Version Number:** 
13.05 14:27:36 [Server] INFO This server is running Paper version git-Paper-625 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.13.2

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem:** 
Time plot flag not reset if change world

**Any relevant console output or screenshots:**
https://www.youtube.com/watch?v=_ht8Pe1FNU8

**Plugins being used on the server:**

Plugins (103): AdditionsAPI, AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, BestViewDistance, BuntetesLogolo, ChangeSkin, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, Citizens, CitizensCMD, CombatLogX, CommandHook, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, Duels, EnderContainers, EntityDetection, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, FastAsyncVoxelSniper, FastAsyncWorldEdit, GriefPrevention, GriefPreventionFlags, HideAndSeek, HolographicDisplays, HonapStaffja, iDisguise, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, MobHeads, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PlaceholderAPI*, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaAdditions, ProtocolLib*, RandomTeleport, RedstoneClockDetector*, RestrictedCreative, Ridables, Shopkeepers, SignEdit*, StaffChat, StaffTime, Stats, SuperLuckyBlock, SzulinapiTuzijatek, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, ViaBackwards*, ViaVersion*, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

**How to replicate:** 

1. Go to my plot.
2. Set plot time flag.
3. Go to another world.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-05-19 03:17
I don't understand?
The plot flags should remain assigned to the plot they are set on, regardless how many times you leave/enter the plot, the world, or the server. 

Clarification from the op is needed.

**Comment by AeSix** [comment] 2019-05-24 12:49
@andris155 I assuming that this is either not an issue any longer, fixed either with config options, or understanding of proper behavior.  I am closing this ticket as you have not been more clear about the issue.  

If you feel the issue is not resolved, please provide more details:
What you believe it should do:
What it is doing:
What needs to change:

If valid, the ticket will be re-opened.

**Closed by AeSix** 2019-05-24 12:49 UTC

**Comment by andris155** [comment] 2019-05-27 14:21
Plot time flag reset to default world time if move out plot or tp other positions plotworld.
But world time not reset to default if changed world. Example.: /mvtp other world, or /warp to other world etc...

**Comment by andris155** [comment] 2019-05-27 14:24
Need to reset plot time flag to default world time if players changed world.
