### ISSUE TITLE
[V6] "Could not pass event PlayerTeleportEvent to PlotSquared v6.0.0-Premium"

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3109] opened 2021-06-22 14:05 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

On startup, I get the following:
`[14:50:34 ERROR]: Could not pass event PlayerTeleportEvent to PlotSquared v6.0.0-Premium
com.plotsquared.core.util.PlayerManager$NoSuchPlayerException: There is no online player with UUID '360152f3-c50b-20a4-a858-3abee8047c74'
[14:50:34 ERROR]: Could not pass event PlayerTeleportEvent to PlotSquared v6.0.0-Premium
com.plotsquared.core.util.PlayerManager$NoSuchPlayerException: There is no online player with UUID 'e858aeb6-78b3-27df-9423-756c1ee6db84'
[14:50:34 ERROR]: Could not pass event PlayerTeleportEvent to PlotSquared v6.0.0-Premium
com.plotsquared.core.util.PlayerManager$NoSuchPlayerException: There is no online player with UUID 'e5d89494-3fbf-2670-9ef4-823153bd4a0e'
[14:50:34 ERROR]: Could not pass event PlayerTeleportEvent to PlotSquared v6.0.0-Premium
com.plotsquared.core.util.PlayerManager$NoSuchPlayerException: There is no online player with UUID '923cdb29-8e5c-224c-961b-c9bfff761416'`
I believe this is related to the Citizens plugin, as the UUIDs mentioned above match some of my citizens' UUIDs.

These errors only started appearing in V6.

### To Reproduce

1. Install Citizens and create some NPCs (the ones that are showing up in the errors are near my server's spawn so I believe that has to be the case to reproduce)
2. Restart the server, and on startup, you should see the errors.

### Expected behaviour

I haven't noticed any unusual behaviour in-game as a result of these errors, so I guess the expected behaviour here is just for the errors to not show up.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/dc70f36ac2c04653a14a4322ea02adfe

### PlotSquared Version

6.0.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment] 2021-06-22 14:07
Duplicate of #3105, should be fixed in the next build

**Closed by SirYwell** 2021-06-22 14:07 UTC
Labels: Requires Testing
