### ISSUE TITLE
add plot command

### ISSUE THREAD

**Issue by voigtman** [IntellectualSites/PlotSquared#473] opened 2015-07-30 20:36 UTC
Hi, It would be handy to have a command that could be run 
i.e /plot (playername) add 1
to add an additional plot to a player's permission. - this would be a useful command for buycraft or vote rewards to give an additional plot space without manually changing the plots.plot.(number) permission for a player. There should still be a cap on maximum obtainable plots per user group. 
The existing plot cost section of the config is great for servers with economies, but fairly pointless on creative servers... 

I suppose to implement this, an if / else section would need to be attached to the command.

btw, thanks for the 3.0.0 update shortly after my last message... So far, no issues - but this server is still in the building stage, so I can't say if there are any player issues at this time.

**Comment by boy0001** [comment] 2015-08-01 05:43
Duplicate of #461

**Closed by boy0001** 2015-08-01 05:43 UTC
Labels: [+] Enhancement
