### ISSUE TITLE
Plot move bugs

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2547] opened 2019-10-27 09:59 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** 
https://athion.net/ISPaster/paste/view/6e2f13c9d1fa42749746b53e317324f9
**[REQUIRED] Spigot/Paper Version Number:** 
 This server is running Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.14.4
**[REQUIRED] Description of the problem:** 
On Plotmove the old plot will not be cleared.
**Any relevant console output or screenshots:**
No console output
**Plugins being used on the server:**

WorldEdit, PlotSquared, MultiVerse
**[REQUIRED] How to replicate:** 

Claim a Plot and build a beautiful building. Than go to a unclaimed free plot make /p i and keep the id. Then go to your plot and do /p move <idofthefreeplot>
**[REQUIRED] Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-10-27 12:03
https://github.com/IntellectualSites/PlotSquared/issues/2342
https://github.com/IntellectualSites/PlotSquared/issues/2375

**Comment by N0tMyFaultOG** [comment] 2019-10-27 12:04
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2375

**Closed by N0tMyFaultOG** 2019-10-27 12:04 UTC
Labels: 1.14.x, Spigot, [✖] Duplicate
