### ISSUE TITLE
PlayerCommandPreprocessEvent 

### ISSUE THREAD

**Issue by darkdragonxxxx** [IntellectualSites/PlotSquared#1032] opened 2016-04-03 05:30 UTC
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
Doesnt even let me do that command
**Description of the problem:**
Here:
http://pastebin.com/z7KG1QAB
Works fine on test server.
**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment] 2016-04-03 05:38
duplicate of #1029

**Closed by boy0001** 2016-04-03 05:38 UTC
