### ISSUE TITLE
Plants don't grow on merged plots

### ISSUE THREAD

**Issue by Dooleylabs** [IntellectualSites/PlotSquared#1183] opened 2016-06-15 16:41 UTC
**Issue:** Trees do not grow past the original plot which was merged with other plots.

**Replicate:** Merge a 3 x 3 plot.

**Debug:** [http://hastebin.com/rimuredihi](http://hastebin.com/rimuredihi)

**Comment by manuelgu** [comment] 2016-06-15 17:15
Duplicate of #1021.

Will be fixed with 3.4.0.

**Closed** 2016-06-15 17:33 UTC
