### ISSUE TITLE
Road schematics do not save NBT data for heads

### ISSUE THREAD

**Issue by Heliosares** [IntellectualSites/PlotSquared#3579] opened 2022-04-20 20:52 UTC
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When schematics for roads are being pasted, blocks such as player heads and daylight sensors lose their NBT data. This does not extend to things like rotation and/or orientation of blocks, those things work correctly. 

### To Reproduce

Place a road schematic containing a block with NBT into /plugins/PlotSquared/schematics/GEN_ROAD_SCHEMATIC/<world name>/ and generate the world, the blocks will generate without NBT.

### Expected behaviour

Blocks are pasted the same as WorldEdit //paste would, with their NBT data intact. 

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/8331595/164319558-a3edde01-b236-4998-934f-44ee81a5a161.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/c66232ce7588493e94b920525b87ba3b

### PlotSquared Version

6.6.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2022-04-23 13:53
I've reworded your issue a bit, because that is not an issue, that behavior doesn't exist at the moment.

**Comment by dordsor21** [comment] 2022-04-23 14:25
This is a shortfall of the spigot generation API (as usual). There is no method for generating with NBT data. At all.

**Comment by Heliosares** [comment] 2022-04-23 14:36
I've found a workaround for this for anyone struggling with it. Running `/plot regenallroads` will paste the road schematics with NBT. You just have to make sure all chunks are already generated prior to running the command using something like ChunkMaster.

**Comment by dordsor21** [comment] 2022-05-19 10:59
Well it probably can be fixed if we move to new generation API and/or set the NBT in population phase

**Comment by dordsor21** [comment] 2022-06-09 19:48
Duplicate of #3051

**Closed by dordsor21** 2022-06-09 19:48 UTC
Labels: Enhancement, Can't fix
