### ISSUE TITLE
PlotSquared can't close database connection on server stop

### ISSUE THREAD

**Issue by StealWonders** [IntellectualSites/PlotSquared#2407] opened 2019-06-26 12:38 UTC
**PlotSquared Version Number:** 4.297

**Spigot/Paper Version Number:** git-Paper-636 (MC: 1.13.2)

**Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
- https://gist.github.com/StealWonders/7e6906069ae9bac9e24e195ac7d2b35a
- https://gist.github.com/StealWonders/9531197fd785c6c8520c531b5848ed4a

**Description of the problem:** 
PlotSquared can't close the database connection and therefore the server takes ages to actually stop. (PlotSquared is blocking the server from shutting down). I am using the default storage.db database file.

**Any relevant console output or screenshots:**
` [14:33:16 INFO]: [PlotSquared] Disabling PlotSquared v4.297
[14:33:16 WARN]: java.lang.NullPointerException
[14:33:16 WARN]: at com.github.intellectualsites.plotsquared.plot.database.SQLManager.validateAllPlots(SQLManager.java:2856)
[14:33:16 WARN]: at com.github.intellectualsites.plotsquared.plot.database.DBFunc.validatePlots(DBFunc.java:74)
[14:33:16 WARN]: at com.github.intellectualsites.plotsquared.plot.PlotSquared.disable(PlotSquared.java:1521)
[14:33:16 WARN]: at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onDisable(BukkitMain.java:270)
[14:33:16 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[14:33:16 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[14:33:16 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[14:33:16 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[14:33:16 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[14:33:16 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[14:33:16 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652)
[14:33:16 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874)
[14:33:16 WARN]: at java.lang.Thread.run(Thread.java:748)
[14:33:16 INFO]: Could not close database connection!`

**Plugins being used on the server:**
`Plugins (34): Arceon*, ArmorStandEditor, BuildersUtilities*, BuycraftX, Chairs*, DiscordSRV, EasyBackup*, EasyBackupCore*, EditableSign, EpicSuite, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, ExtraContexts*, FastAsyncVoxelSniper, FastAsyncWorldEdit, goBrush, goPaint, HeadsInventory, HeadsPluginAPI, Holograms*, LuckPerms, Multiverse-Core, PetBlocks*, PlaceholderAPI*, PlotSquared, ProtocolLib*, SchematicBrush*, Vault, ViaVersion*, WorldBorder, WorldEdit, WorldGuard`

**How to replicate:** 
Stop the server with /stop

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report
- [x] I made sure I am using an up-to-date version of PlotSquared
- [?] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-07-21 13:54
Has this been resolved with newer builds? (Release and/or Breaking)
Nothing in change logs specifically say so, but any change can affect other areas.

**Comment by StealWonders** [comment] 2019-07-22 18:55
Will test, give me a couple days.

**Comment by StealWonders** [comment] 2019-07-22 19:08
` [21:06:28 INFO]: [PlotSquared] Disabling PlotSquared v4.303
[21:06:28 WARN]: java.lang.NullPointerException
[21:06:28 WARN]: at com.github.intellectualsites.plotsquared.plot.database.SQLManager.validateAllPlots(SQLManager.java:2856)
[21:06:28 WARN]: at com.github.intellectualsites.plotsquared.plot.database.DBFunc.validatePlots(DBFunc.java:74)
[21:06:28 WARN]: at com.github.intellectualsites.plotsquared.plot.PlotSquared.disable(PlotSquared.java:1521)
[21:06:28 WARN]: at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onDisable(BukkitMain.java:270)
[21:06:28 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[21:06:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[21:06:28 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[21:06:28 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[21:06:28 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[21:06:28 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[21:06:28 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652)
[21:06:28 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874)
[21:06:28 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:06:28 INFO]: Could not close database connection!`

Let me know if you need any further information... ;)

**Comment by MattBDev** [comment] 2019-08-07 00:44
The issue is that there is a a value on that line that is null. I've added debugging messages for it and the plugin will skip validation if any of these values are null.

**Closed** 2019-08-07 00:45 UTC
Labels: 1.13.x, Spigot
