### ISSUE TITLE
Clearing a plot in an augmented world results in a error

### ISSUE THREAD

**Issue by DerEingerostete** [IntellectualSites/PlotSquared#3597] opened 2022-05-05 17:53 UTC
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When clearning (or deleting) a plot in an augmented world the following error is printed in the server log and the plot is not cleard (still a success message is send).

### To Reproduce

1. Create a augmented plot world
2. Claim a plot (and optionally build some blocks in it)
3. Perform the /plot clear Command

### Expected behaviour

The plot is resetted to its default (aka. cleared)

### Error log (if applicable)

https://paste.gg/p/anonymous/e8389be3ab204caa8f31d8026ae7161d

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4db1ffdda7364d2d8c71bb9832b3933e

### PlotSquared Version

6.7.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2022-05-07 12:37
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3597

**Comment by DerEingerostete** [comment] 2022-05-08 11:34
> Duplicate of #3597

Is it correct that this is a duplicate of itselfy or why does the tag #3597 refer back to this issue?

**Comment by dordsor21** [comment] 2022-05-08 11:56
I assume he meant #2631

**Comment by DerEingerostete** [comment] 2022-05-08 12:02
> I assume he meant #2631

The error message is not the same but the issue seems to be the same. Thanks for the clarification anyway!

**Comment by dordsor21** [comment] 2022-05-08 12:05
You can add your error to that issue. It all stems from the same core issue, just at a different time in development

**Comment by dordsor21** [comment] 2022-05-08 15:52
Not not on phone, no idea what this is a duplicate of... My bad

**Closed** 2022-05-15 09:42 UTC
Labels: Duplicate
