### ISSUE TITLE
Spawn any mobs, but not be trusted

### ISSUE THREAD

**Issue by Sanyasp** [IntellectualSites/PlotSquared#2291] opened 2019-03-08 17:16 UTC
Debug paste link: https://incendo.org/paste/view/5b881635c5254b499422b7a9cfb6545b

Description of the problem: You can spawn any mob on the water at any (foreign) raft.

1 Need any (foreign) land with water
2 Take any spawn egg
3 Aim the spawn egg at the top of the water, so that would not show the HitBox block
4 Click the right mouse button

Relevant:
- 18.08.19-01a927c-2036
- 19.03.07-db8ee76-691
Other versions did not check.

https://youtu.be/9QsS5FT-A7c

UPD. Found a report of this problem. But in someone else's report version of Spigot 1.13. I have Spigot 1.12. https://github.com/IntellectualSites/PlotSquared/issues/2245

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-03-08 18:07
I don't know if this has been resolved in newer builds, but you are on an old build. 

Try a new build for 1.12 here: https://ci.athion.net/view/Everything/job/PlotSquared/

If the issue persists with the new build, please create a new debugpaste and update your ticket with the new information.  IF by chance, this resolves the issue, please update the ticket letting us know, and close it. 

Thank you! :)

**Comment by Sanyasp** [comment] 2019-03-08 18:12
> I don't know if this has been resolved in newer builds, but you are on an old build.
> 
> Try a new build for 1.12 here: https://ci.athion.net/view/Everything/job/PlotSquared/
> 
> If the issue persists with the new build, please create a new debugpaste and update your ticket with the new information. IF by chance, this resolves the issue, please update the ticket letting us know, and close it.
> 
> Thank you! :)
> 
> > <img alt="" width="48" src="/static/b8cf1c1c/favicon.ico">**[PlotSquared [Jenkins]](https://ci.athion.net/view/Everything/job/PlotSquared/)**

The problem remained urgent. debugpaste has updated.

**Comment by AeSix** [comment] 2019-03-08 18:40
WHat version of WorldEdit are you using?  It's not reported in the info. 
1.12 should be using 6.1.9 from here:
https://dev.bukkit.org/projects/worldedit/files
Or using FAWE from here:
https://ci.athion.net/view/Everything/job/FastAsyncWorldEdit/

Let us know how this goes for you.  If it's still an issue, the devs will take action as quickly as possible.

In the mean time if spawn eggs are a show-stopper, try using WorldGuard, here's some info:
http://worldguard.enginehub.org/en/latest/config/#event-handling

**Comment by Sanyasp** [comment] 2019-03-08 20:19
> In the mean time if spawn eggs are a show-stopper, try using WorldGuard, here's some info:

The WorldEdit version you specified is installed. The problem is urgent. The report on this problem was written on January 21, what I noticed only an hour after writing this report.
https://github.com/IntellectualSites/PlotSquared/issues/2245
There are only 1.13 and I have 1.12.

**Comment by MattBDev** [comment] 2019-03-09 00:14
Duplicate of #2245 which is now fixed.

**Comment by Sanyasp** [comment] 2019-03-09 03:50
> Duplicate of #2245 which is now fixed.

Downloaded the latest version (https://ci.athion.net/view/Everything/job/PlotSquared/722/), the problem is still relevant.

**Comment by MattBDev** [comment] 2019-03-10 02:44
I figured it out. I'll patch it tomorrow.

**Comment by dordsor21** [comment] 2019-03-11 13:40
What's the issue? I'm interested as to why my patch didn't work, I'm 99% sure it worked when I tested (albeit on 1.13)

**Closed** 2019-03-12 20:41 UTC
