### ISSUE TITLE
Chest items disappearing

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#2201] opened 2018-12-28 06:05 UTC
A user reported that breaking a chest in a plot does not always lead to the chest content being dropped in the plot. I've failed to reproduce this myself, so I am interested in seeing whether or not anyone else has experienced  this.

The user is running Paper.

**Comment by dordsor21** [comment] 2018-12-28 10:51
Might be something to do with
`chunk-processor:
  # Auto trim will not save chunks which aren't claimed
  auto-trim: false
  # Max tile entities per chunk
  max-tiles: 4096
  # Max entities per chunk
  max-entities: 512
  # Disable block physics
  disable-physics: false`

**Comment by DeepRobin** [comment] 2019-01-04 14:17
If you drop an item, will it removed, too? If yes i think its issue #2216.

**Comment by AeSix** [comment] 2019-01-15 18:20
Without knowing full details of this, I'm opting towards it being 
misc_spawn_unowned: false
in PlotSquared/config/worlds.yml

Set this to true and test. This setting, I believe, also controls player-dropped items (pressing q), as well as loot drops from mobs & player deaths.

**Comment by DeepRobin** [comment] 2019-01-15 18:35
@AeSix both options don't work

**Comment by AeSix** [comment] 2019-01-15 19:23
@DeepRobin 
Seeing the ticket 2216 now (I thought this sounded familiar):
Have you tried using an updated version of P2 4. beta builds?  Still an issue?
The only thing I can suggest is to create a test server using just P2 4.0, WorldEdit and PEX.  
This step is to ensure that the issue is with P2 or it's configs.  Use a default generated config for this test. Provided the items drop as expected, replace the default configs with your configs.  If the items disappear on drop, we know it's your configs.  Likewise, if your configs test out fine, then it's going to be another plugin.

Provided the issue persists, add in "Core", test, add in "PAC", test,  add in SkyPvP test. Add these one at a time if possible.  I don't know the dependencies for these plugins, but I suspect these first due to the rest having no business manipulating items at that level.

My experience with P2 over the years and with current releases makes me feel like something else is interfering other than default config options and P2.

**Comment by dordsor21** [comment] 2019-01-23 13:52
Fixed in fd4a5f

**Closed by dordsor21** 2019-01-23 13:52 UTC
Labels: 1.13.x, [!] Bug, [?] Testing Required, [✔] Verified
