### ISSUE TITLE
Error creating legacy block

### ISSUE THREAD

**Issue by FatherWh0** [IntellectualSites/PlotSquared#2400] opened 2019-06-19 03:20 UTC
When loading Plotsquared with paper 1.14.2 the following errors occur. 
https://pastebin.com/RjUkAPcU
This happens with 4.277 and the latest dev build 4.292.

**Comment by MattBDev** [comment] 2019-06-19 03:59
Duplicate of several others.

**Closed by MattBDev** 2019-06-19 03:59 UTC

**Comment by FatherWh0** [comment] 2019-06-19 04:01
Please link to duplicate. I cannot locate any.

**Comment by MattBDev** [comment] 2019-06-19 04:03
https://github.com/IntellectualSites/PlotSquared/issues/2364

**Comment by MattBDev** [comment] 2019-06-19 04:03
https://github.com/IntellectualSites/PlotSquared/issues/2362

**Comment by MattBDev** [comment] 2019-06-19 04:04
This is the reason you should FOLLOW THE TEMPLATE instead of deleting it.
