### ISSUE TITLE
Minecraft 1.10 Start up error.

### ISSUE THREAD

**Issue by DeadIntermediate** [IntellectualSites/PlotSquared#1173] opened 2016-06-10 05:17 UTC
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://pastebin.com/QUr6L3Bs

**Description of the problem:**
When starting up the server, I get that error in Minecraft 1.10 on spigot.

**How to replicate**:
Start the server up.

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by zombachu** [comment] 2016-06-10 07:34
This is a duplicate of #1164.

**Closed** 2016-06-10 14:21 UTC
