### ISSUE TITLE
Plot claim bugs

### ISSUE THREAD

**Issue by Fuzzlemann** [IntellectualSites/PlotSquared#811] opened 2015-12-28 12:20 UTC
Plots of our users are getting cleared (after x days or minutes) by nothing and /plot auto claims the plot of other users.

**Comment by manuelgu** [comment] 2015-12-28 13:13
Please provide a "/p debugpaste"

**Comment by Fuzzlemann** [comment] 2015-12-28 18:28
http://hastebin.com/jaqerirape

**Comment by boy0001** [comment] 2016-01-12 12:36
Duplicate of #801

**Closed by boy0001** 2016-01-12 12:36 UTC
