### ISSUE TITLE
startup bug

### ISSUE THREAD

**Issue by ILoveAMac** [IntellectualSites/PlotSquared#1194] opened 2016-06-18 10:54 UTC
# Bug report template (Follow this template unless you are making a feature request.)
**http://hastebin.com/ufihuganaq**:

`java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.v1_10_R1.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_10_R1.Chunk, boolean, int)
18.06 06:55:40 [Server] WARN at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:335)
18.06 06:55:40 [Server] WARN at com.plotsquared.bukkit.util.SendChunk.<init>(SendChunk.java:53)
18.06 06:55:40 [Server] WARN at com.plotsquared.bukkit.BukkitMain.initPlotQueue(BukkitMain.java:407)
18.06 06:55:40 [Server] WARN at com.intellectualcrafters.plot.PS.<init>(PS.java:253)`

**To replicate: Start the plugin in mc 1.10**

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by Sauilitired** [comment] 2016-06-18 16:12
Duplicate of #1164, which is fixed in development builds. There is yet to be an official release for 1.10.

**Closed by Sauilitired** 2016-06-18 16:12 UTC
