### ISSUE TITLE
IC2 Mod's rubber trees will crash plotsquared generation mechanism

### ISSUE THREAD

**Issue by sourcepowered** [IntellectualSites/PlotSquared#1215] opened 2016-06-23 13:52 UTC
Industrial Craft 2 Mod's rubber trees will crash plotsquared generation mechanism.
Only use PlotSquared and IC2 Mod, on Thermos 1.7.10.
Please see the photo:
![1](https://cloud.githubusercontent.com/assets/17511838/16175590/b05f25a0-3625-11e6-9666-d5d8807768b4.png)
This is a very old problem, but no one submit it.

If using plots.clear command to cleaning plot, the tree will still be there.
Even cleaned up all the buildings, the tree will restore to the previous look.(Even if you've destroyed it).

**Comment by MattBDev** [comment] 2016-06-23 20:38
Please use the issue template in the future. Are you saying the tree's are not being deleted on plot clear? Is there an actual crash? If there is a crash, we need to see the error.

**Comment by sourcepowered** [comment] 2016-06-24 14:10
@MattBDev Background log without any problems and no crashes, I express wrong, sorry. I mean, IC2 Mod will destroy the plots world, plots world should not have the rubber trees and rubber trees are not affected by use plots.clear command.

**Comment by Sauilitired** [comment] 2016-06-24 14:43
@sourcepowered sounds like a problem with IC2 then. They must force their block populators on all worlds, or something like that.

**Comment by MattBDev** [comment] 2016-06-24 14:58
@Sauilitired So it sounds like we both agree that this is an IC2 issue. Should we close this?

**Comment by Sauilitired** [comment] 2016-06-24 15:35
If it turns out that this is indeed caused by us, then we'll try to find a solution. As of now, nothing seems to point towards it being our fault.

**Closed** 2016-06-24 15:35 UTC
Labels: [✖] Insufficient Info
