### ISSUE TITLE
Claim schematic should contain the walls

### ISSUE THREAD

**Issue by NoFace851** [IntellectualSites/PlotSquared#2476] opened 2019-08-19 20:32 UTC
**[REQUIRED] PlotSquared Version Number: PlotSquared-4.298)

**[REQUIRED] [20:53:40 INFO]: This server is running Paper version git-Paper-171 (MC: 1.14.4)
(Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:1.14.4

Links to worlds.yml file and settings.yml file:
world.yml https://pastebin.com/DsKasjWR
settings.yml https://pastebin.com/vV84MLrA

**[REQUIRED] Description of the problem:

I followed this tutorial https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Schematic-on-claim but it's not what i want, i thought that i could change the template of the wall too with this (when you do /p claim). I don't want the sandstone slabs  and i have a structure above those walls (like a street lamp post made of iron bars) that disappear when i do /p claim. But as you can see i can't. Why is that? this schematic option should include the walls of the claim too, just a suggestion. Can i change to the way i want?

Any relevant console output or screenshots:
when it's unclaimed:
https://imgur.com/a/NuT69Sm
what happen's when i claim it:
https://imgur.com/a/kDkONow because of: https://imgur.com/a/CmdIxpS
what i would like to happen when i claim:
https://imgur.com/a/1rAzEu0

you can see that it destroys the iron bars, i would like to know if there are a fix for that please

Plugins being used on the server:
Plugins (52): AutoMessager, Autorank, ChatControl, ChestShop, C
laimFly, ClearLag, ColoredSigns*, CommandSigns, CompatNoCheatPlus*, ConditionalC
ommands*, DeathMessagesPrime, DragonSlayer, DragonTimer, EditableSign, Essential
s, GetSpawners, GriefPrevention, HolographicDisplays, IllegalStack, JukeBox, Las
tHolo*, mcMMO, Minepacks, MobHeads, Multiverse-Core, NametagEdit*, NoCheatPlus,
NoteBlockAPI, OldCombatMechanics, OreAnnouncer, PermissionsEx*, PixelVip*, Place
holderAPI*, PlotSquared, PluginLibrary*, ProtocolLib, PvPToggle, RankGrantPlus,
SecurityVillagers, SetTheSpawn, Statz, UltimateChat, UltimateStacker, Vault, Via
Version*, VoidGenerator, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard, World
GuardExtraFlags, XPBoost* --->

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by NoFace851** [comment] 2019-08-19 20:58
and when you do /p delete it should go back to what it was before it was bought, using the template you used to do /p createroadschematic. But it's just the same as the sandstone when you buy but with stone slabs instead

**Comment by AeSix** [comment] 2019-08-19 21:05
Plot walls are the plot's walls.  They are not part of the plot build area.  You can set the unclaimed and claimed wall material in the config files.  

This is not a bug, it is by design. 

If you would like to reuqest a feature change, please do so in PlotSquaredSuggestions, there is an issue tracker there suitable for this. 

Closing.

**Closed by AeSix** 2019-08-19 21:05 UTC
