### ISSUE TITLE
music flag not working.

### ISSUE THREAD

**Issue by fadfhkdfga** [IntellectualSites/PlotSquared#4316] opened 2024-02-05 01:12 UTC
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Even if you use the flag set music ~ command, background music is not set.

### To Reproduce

.

### Expected behaviour

.

### Plot Debugpaste

.

### PlotSquared Version

PlotSquared-7.3.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment] 2024-02-05 05:11
Have you set the "Music" slider to > 1? If not, that's the reason why. 

In hindsight it's kind of dumb of me to set the sound category for the plot music flag to "music" potentially - I guess Jukebox/Note-Blocks would've been a better choice? Tho it does make sense in that category as well.

**Comment by NotMyFault** [comment] 2024-02-05 21:38
> Have you set the "Music" slider to > 1? If not, that's the reason why.
> 
> In hindsight it's kind of dumb of me to set the sound category for the plot music flag to "music" potentially - I guess Jukebox/Note-Blocks would've been a better choice? Tho it does make sense in that category as well.

Could be moved over, but the lack of steps to reproduce included in the issue, don't really work towards a confident issue at all.

**Comment by PierreSchwang** [comment] 2024-02-07 00:22
Still no debugpaste(s) whatsoever - no way to look into it.

**Comment by OneLiteFeather** [comment] 2024-02-07 14:24
<img width="661" alt="grafik" src="https://github.com/IntellectualSites/PlotSquared/assets/77929075/d7a8cb54-ec8a-434a-801a-d088204beee8">
<img width="665" alt="grafik" src="https://github.com/IntellectualSites/PlotSquared/assets/77929075/ed245344-afcd-4b72-9585-5b3d34b9c7f2">

I hear default music, also the normal jukebox but no plot music
https://athion.net/ISPaster/paste/view/dcc35ce7a53141419881739a12cb8338

**Comment by PierreSchwang** [comment] 2024-02-07 15:24
> <img width="661" alt="grafik" src="https://github.com/IntellectualSites/PlotSquared/assets/77929075/d7a8cb54-ec8a-434a-801a-d088204beee8">
> 
> <img width="665" alt="grafik" src="https://github.com/IntellectualSites/PlotSquared/assets/77929075/ed245344-afcd-4b72-9585-5b3d34b9c7f2">
> 
> 
> 
> to reproduce: 
> 
> 1. Set /p flag set music RELIC on your own plot
> 
> 2. Hear out for no music, only minecraft default music can appear, but no music disk
> 
> 
> 
> I hear default music, also the normal jukebox but no plot music
> 
> https://athion.net/ISPaster/paste/view/dcc35ce7a53141419881739a12cb8338

Mhm, I had issues with sometimes not hearing any music and sometimes hearing the totally wrong music before my change(s) - but that's weird as it did work for me on 1.20.4.
Someone / I'll have to look into that I guess.

**Comment by Tsoccerguy3** [comment] 2024-02-13 06:49
I tested and noticed no music in the current February 2024 builds . /plot music and choosing a disc works but can not hear any music. . 

https://athion.net/ISPaster/paste/view/14a3d53ed00a478899c412c639319f8e

**Comment by Tsoccerguy3** [comment] 2024-02-13 07:07
I suspect that there is a mistake in this commit 9566af5fda7ec01d95e7f3ec5508f34de1e21c00 , because prior commit works.

**Comment by Tsoccerguy3** [comment] 2024-02-13 07:09
I reverted back to this commit a1d94af242751bdb4f53b9693f07faa316b4abfb and music is working

**Comment by SirYwell** [comment] 2024-02-13 07:44
Does #4301 apply to you?

**Comment by PierreSchwang** [comment] 2024-02-13 18:46
I really don't see how that commit should've broke that at all tbh. It even worked for me on 1.20.4 Paper.

The javadocs only state:
> This function will fail silently if Location or Sound are null. No sound will be heard by the player if their client does not have the respective sound for the value passed.

But sound parsing has not changed at all, and the location can't be null.

**Comment by Tsoccerguy3** [comment] 2024-02-14 06:16
All I can tell you is from that commit onward on Paper 1.20.4 current builds the sound is not heard from plot music discs. I will try reversing that commit and compile the latest PS

**Comment by Tsoccerguy3** [comment] 2024-02-27 11:06
reversing the commit fixed the issue. I had no time to find out why.

**Comment by Tsoccerguy3** [comment] 2024-03-13 00:59
> I really don't see how that commit should've broke that at all tbh. It even worked for me on 1.20.4 Paper.
> 
> The javadocs only state:
> 
> > This function will fail silently if Location or Sound are null. No sound will be heard by the player if their client does not have the respective sound for the value passed.
> 
> But sound parsing has not changed at all, and the location can't be null.

Hi Pierre, I could not figure out why your music flag commit is not working. I tested again on a local server on my home system , same results. The only fix was to undo your commit and compile current code . Sorry I couldnt be much help, I guess you could reverse it so that others dont have issues and revisit the patch another day. Not everyone uses the /plot music , as plot is used by new players visiting the server unit they get promoted and build on the main maps

**Comment by Tsoccerguy3** [comment] 2024-04-07 06:38
I am surprised that this commit has not been fixed yet , https://github.com/IntellectualSites/PlotSquared/commit/9566af5fda7ec01d95e7f3ec5508f34de1e21c00 . It simply did not work in 1.20.4 Paper . To test , compile latest build to date and goto a plot and do /plot music and select a Disc. Nothing is heard with volume at 100 percent .

**Comment by PierreSchwang** [comment] 2024-04-07 21:57
I'm sorry - I found the error which I just couldn't see. Will be fixed with https://github.com/IntellectualSites/PlotSquared/pull/4391

**Closed** 2024-04-12 18:55 UTC
Labels: Bug, Approved
