### ISSUE TITLE
Chunk Claiming GitHub Error??

### ISSUE THREAD

**Issue by CreationMC** [IntellectualSites/PlotSquared#2555] opened 2019-11-02 16:46 UTC
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):
 https://athion.net/ISPaster/paste/view/dc28a507c31b47e588f82de31469899c

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [ ] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [ ] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [ ] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [x] Minecraft 1.13.2
- [ ] Minecraft Java Edition *other versions, please specify*:
- [ ] Minecraft Bedrock Edition *speicify version*:

### Server build info: 

``` paste here, between the tick marks, replacing this text ```

### WorldEdit/FAWE versions:

- [X] FAWE FastAsyncWorldEdit-bukkit-1.13.184.
- [ ] WorldEdit *version*: 

### Description of the problem:

Just when users are trying to claim a plot this error occurs in chat:
[![Screenshot from Gyazo](https://gyazo.com/1fd1d0f18ca7706e2920a82ee927bac0/raw)](https://gyazo.com/1fd1d0f18ca7706e2920a82ee927bac0)

Who: Players/Everyone
What: Chunk Claiming use.
When: Today, November 2nd, 2019 at 12PM EST
Where: My server (ParallaxMC)
Why: No clue.
How: No clue.
Players can't claim plots.

### How to replicate:
No clue.

## Additional Information:
Console Error:
```
[16:45:10 WARN]: java.lang.AbstractMethodError: com.github.intellectualsites.plotsquared.plot.util.ChunkManager.loadChunk(Ljava/lang/String;Lcom/github/intellectualsites/plotsquared/plot/object/ChunkLoc;Z)Z
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot$6.run(Plot.java:2145)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot$6.run(Plot.java:2142)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.util.TaskManager.sync(TaskManager.java:119)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.util.TaskManager.sync(TaskManager.java:114)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot.guessOwner(Plot.java:2142)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot.canClaim(Plot.java:2124)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.PlotArea.getNextFreePlot(PlotArea.java:722)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.Auto.autoClaimFromDatabase(Auto.java:135)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.Auto.autoClaimSafe(Auto.java:111)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.Auto.onCommand(Auto.java:236)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.execute(SubCommand.java:36)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:335)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:251)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:25)
[16:45:10 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[16:45:10 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:45:10 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[16:45:10 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:45:10 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[16:45:10 WARN]: at java.lang.Thread.run(Thread.java:748)
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [ ] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] I made sure I am using an up-to-date version of PlotSquared
- [ ] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by CreationMC** [comment] 2019-11-02 16:47
Console Error:
[16:45:10 WARN]: java.lang.AbstractMethodError: com.github.intellectualsites.plotsquared.plot.util.ChunkManager.loadChunk(Ljava/lang/String;Lcom/github/intellectualsites/plotsquared/plot/object/ChunkLoc;Z)Z
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot$6.run(Plot.java:2145)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot$6.run(Plot.java:2142)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.util.TaskManager.sync(TaskManager.java:119)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.util.TaskManager.sync(TaskManager.java:114)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot.guessOwner(Plot.java:2142)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot.canClaim(Plot.java:2124)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.object.PlotArea.getNextFreePlot(PlotArea.java:722)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.Auto.autoClaimFromDatabase(Auto.java:135)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.Auto.autoClaimSafe(Auto.java:111)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.Auto.onCommand(Auto.java:236)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.execute(SubCommand.java:36)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:335)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:251)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[16:45:10 WARN]: at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:25)
[16:45:10 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[16:45:10 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:45:10 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[16:45:10 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:45:10 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[16:45:10 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[16:45:10 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by MattBDev** [comment] 2019-11-02 20:05
Duplicate of #2516 , #2543 , #2514, #2507 , #2510. The user also  wrote "Github Error" which makes no sense. They also did not check for duplicates and fill out the rest of the template correctly.

**Closed by MattBDev** 2019-11-02 20:05 UTC
Labels: [?] Testing Required
