### ISSUE TITLE
Plot move: Error and not properly moved

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#2342] opened 2019-04-25 13:59 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 

Failed to create the debug paste: Connection timed out (Connection timed out)
Paper 1.13.2 build 624
WE 7.0 beta 5 / WE v7.0.0 4156-a992632

**Description of the problem:** 
Plot move copies the plot but forgets to:
- change the newly claimed plot to change the plot border to the "claimed state"
- clear the old plot properly (buildings are left untouched)
- change the abandoned plot to change the plot border to the "unclaimed state"
- bonus error on console: (build 232: https://pastebin.com/dFVEFYy4 build 261: https://pastebin.com/xMi4JCiZ)

**How to replicate:** 

1. Plot move 2;2
2. See results
3. Check console

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

Tried WE 7 beta 5, WG 7 beta 3 and WE/WG 7 latest.
Tried plotsquared 4 build 232 as wel as build 261

**Comment by MattBDev** [comment] 2019-04-25 14:40
Does the latest release build work or does the error still occur?

**Comment by x1p** [comment] 2019-04-25 14:50
Both versions have the same behavior

**Comment by x1p** [comment] 2019-06-04 09:38
Still no fix in build 291
Initial pastbins are expired so let's drop it here:
```
[11:35:37 WARN]: java.lang.NullPointerException
[11:35:37 WARN]: at com.github.intellectualsites.plotsquared.plot.database.SQLManager.sendBatch(SQLManager.java:354)
[11:35:37 WARN]: at com.github.intellectualsites.plotsquared.plot.database.SQLManager.lambda$new$0(SQLManager.java:142)
[11:35:37 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[11:35:37 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:35:37 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:35:37 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:35:37 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:35:37 WARN]: at java.lang.Thread.run(Thread.java:748)
[11:35:43 WARN]: [PlotSquared] Task #555 for PlotSquared v4.291 generated an exception
```

**Comment by AeSix** [comment] 2019-07-30 12:08
https://github.com/IntellectualSites/PlotSquared/issues/2375 seems like a duplicate of this, however with a bit more information. 
Closing.

**Closed by AeSix** 2019-07-30 12:08 UTC
Labels: 1.13.x
