### ISSUE TITLE
Compatibility with SimplePets

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3857] opened 2022-10-25 11:37 UTC
### What feature do you want to see added?

I would like to see compatibility with the SimplePets plugin (https://www.spigotmc.org/resources/simplepets.100106/).

What I mean by compatibility is the ability to exempt pets from these PlotSquared configuration settings:

- `kill-road-mobs`
- `entity-pathing`

My personal use case for this is that on my server, I don't want entities to be able to move between plots, so I utilise the aforementioned settings to prevent that. However, I don't want this to apply to cosmetic pets, as there is no need.

### Are there any alternatives?

I created a feature request a while back (https://github.com/IntellectualSites/PlotSquared/issues/3287) asking if the API could be expanded to allow specific mobs to be exempted from the aforementioned settings, but it seems to be the case that it would require a lot of work for little/niche reward.

EDIT: I realised I have already asked for a similar thing to this before in the past (https://github.com/IntellectualSites/PlotSquared/issues/3240) but it was denied because SimplePets has a PlotSquared addon. However, this addon has nothing to do with the aforementioned PlotSquared settings, and I have already talked with the devs over at SimplePets about this particular issue, and it seems that it would be difficult for them to override the settings (while maintaining good practices anyway) due to PlotSquared not having API for them specifically. Here is the actual interaction I had with them:
![image](https://user-images.githubusercontent.com/26799016/197816939-aee2ae24-ee8f-4bc1-a1ba-b3b116cf2d54.png)

**Comment by dordsor21** [comment] 2022-11-11 11:04
Duplicate of #2971

**Closed by dordsor21** 2022-11-11 11:04 UTC
Labels: Enhancement
