### ISSUE TITLE
/p delete not working: A setblock timer is bound to either the current plot or you.

### ISSUE THREAD

**Issue by Ishidres** [IntellectualSites/PlotSquared#1653] opened 2017-07-01 18:37 UTC
# Bug report template 
**Debug paste link:** 
Well, it just gave me this error:
```
[20:26:18] [Server thread/INFO]: Ishidres issued server command: /p debugpaste
[20:26:18] [Craft Scheduler Thread - 72/WARN]: Exception in thread "
[20:26:18] [Craft Scheduler Thread - 72/WARN]: Craft Scheduler Thread - 72
[20:26:18] [Craft Scheduler Thread - 72/WARN]: " 
[20:26:18] [Craft Scheduler Thread - 72/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 1085
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Couldn't read response!
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43)
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Description of the problem:** 
When I try to clear/delete a plot using /p delete, it says in chat:
_A setblock timer is bound to either the current plot or you. Please wait for it to finish._

**How to replicate:** 
Well, go to any plot, do /p delete or /p clear, or anything which will set blocks on the plot or remove them. WorldEdit on plots is working fine (latest version).

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report (the issues before, aren't solved)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Ishidres** [comment] 2017-07-05 18:21
bump,
please help me 😢

**Comment by lurquhar1221** [comment] 2017-07-10 04:53
Also occurs on sponge, due to #1657.

@boy0001 when can we expect a fix?

**Comment by jiastku98** [comment] 2017-10-02 17:37
Also occurs ！！！！

**Comment by chedadmin** [comment] 2018-09-01 15:31
I know this is an old thread but I'm also having this problem.

**Comment by RedstoneFuture** [comment] 2019-01-27 17:40
Would you post a `/plot debugpaste link` ?

**Comment by AeSix** [comment] 2019-03-17 03:32
I cannot replicate this using 1.13.2 and P2 4.184.

Perhaps this is a Minecraft 1.8 issue.  Additionally, it seems to be (partially?) caused by the use of hastebin, which is no longer being used.  

The only time I have had this issue in the past is if there were large operations affecting P2, waiting a moment and retrying resulted in the operation completing.  This happened with deletes and road regens. I've always thought this to be expected behavior to prevent crashing the server.

**Comment by tylerpace123** [comment] 2019-04-28 02:59
Using 1.14 and up to date P2 and still having this issue. No fix after almost 2 years?

**Comment by MattBDev** [comment] 2019-05-05 19:09
Relevant link: https://pastebin.com/wNbGQXA5

**Comment by UnioDex** [comment] 2019-05-06 09:22
I don't think these 2 issues (#2351) are relevant. Because this only started to happen after i update to latest version from a version that has released in 2019. But this issue is opened in 2017. Also i don't get the message OP provided. I don't get any error message in game i only get console exception.

**Comment by AeSix** [comment] 2019-07-30 12:15
Is this still an issue when usinge newer builds from here: https://ci.athion.net/view/Everything/job/PlotSquared-Legacy/

**Comment by AeSix** [comment] 2019-08-09 11:43
I'm unable to replicate this issue with legacy builds without other plugins being installed, and no one else has reported back that newer builds are not working.  Closing ticket. 

If this is still an issue for any one of the users reporting this, please respond to this ticket and we'll see about re-opening it.  Be sure you're using the newest version of the legacy builds of P2, and if you're using Spigot 1.8.8, try Paper 1.8.8 (and vice versa) before reporting back.

**Closed by AeSix** 2019-08-09 11:43 UTC
Labels: 1.8.x, [✖] Cannot Replicate
