### ISSUE TITLE
player can place bucket

### ISSUE THREAD

**Issue by qq591692157** [IntellectualSites/PlotSquared#2008] opened 2018-06-29 02:17 UTC
In the latest version, players are free to place lava buckets or buckets on roads or other people's land!!!

![qq 20180629100934](https://user-images.githubusercontent.com/39996393/42069601-4847a788-7b85-11e8-8f99-98ab94204848.png)
![qq 20180629100952](https://user-images.githubusercontent.com/39996393/42069605-4a354438-7b85-11e8-93d2-8177a79d13eb.png)

![qq 20180629100947](https://user-images.githubusercontent.com/39996393/42069602-497ad77e-7b85-11e8-8fd1-8843673f18f2.png)

use 
spongeforge-1.12.2-2705-7.1.0-BETA-3206
PlotSquared-Sponge-18.06.23-79e1ea9-2017

**Comment by qq591692157** [comment] 2018-06-29 02:19
This problem is very serious, affecting player experience!

**Comment by RedstoneFuture** [comment] 2018-07-01 08:09
I think your test-user have the permission:

**plots.admin.interact.road**

**Comment by qq591692157** [comment] 2018-07-01 17:46
I'm sure the tester doesn't have this right!
plots.admin.interact.road

**Comment by RedstoneFuture** [comment] 2018-07-02 09:02
any error in the console?

**Comment by qq591692157** [comment] 2018-07-04 18:45
Console has no error, why don't you try!

**Comment by RedstoneFuture** [comment] 2018-07-04 21:14
Because I haven't a problem with this in PaperSpigot.

**Comment by qq591692157** [comment] 2018-07-06 23:13
I hope you can fix it, and now I have to disable buckets, magma buckets, and buckets!

**Comment by AeSix** [comment] 2019-08-12 18:10
@qq591692157 
Is this still an issue, or have you figured out what the problem is?
I can't promise anyone will be working on the Sponge code for PlotSquared, but if this was indeed an issue with the permission plugin or some other plugin or mod causing the problem, I'd like to close this ticket.  

It has been over a year, and afaik, no one has picked up Sponge development for PlotSquared.

**Closed** 2020-02-23 19:12 UTC
Labels: Sponge, Won't fix, [-] Low Priority
