### ISSUE TITLE
Particles dont clear after /plot clear|delete

### ISSUE THREAD

**Issue by xAphex** [IntellectualSites/PlotSquared#2346] opened 2019-04-29 10:22 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** PlotSquared-19.4.27-b7909cc-263

**[REQUIRED] Spigot/Paper Version Number:** git-Paper-622

**[REQUIRED] Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
`world.yml` https://hastebin.com/puliraheda.yml
`settings.yml` https://hastebin.com/zoresubobe.yml

**[REQUIRED] Description of the problem:** 
If you place a spawner and clear the plot the spawner particles remain.

**Any relevant console output or screenshots:**
![image](https://user-images.githubusercontent.com/5391237/56890204-7b17e600-6a81-11e9-8a87-e7807775f0c8.png)

**Plugins being used on the server:**
`AgreedPvP
AngelChest
ChatControl
ChestSort
CraftingStore
DiscordSRV
Essentials
EssentialsProtect
EssentialsSpawn
FastAsyncWorldEdit
GriefPrevention
IllegalStack
InvUnload
LuckPerms
LumberJack
Matrix
NoNetherRoof
PerWorldInventory
PlotSquared
ProtocolLib
Vault
WorldEdit`

**How to replicate:** 
1. Place spawner and wait 5 seconds for spawner particles to load.
2. Clear/Delete the plot using `/plot clear` or `/plot delete`

**How to fix:**
My guess is to add a task to the `/plot clear` or `/plot delete` commands to also clear/delete all particles.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by xAphex** [comment] 2019-04-29 11:41
**Update:**
Leaving the world and joining it again removed all the particles.

**Comment by MattBDev** [comment] 2019-04-29 16:00
If the error can be reproduced, it is likely an issue with a packet not being sent to the client.

**Comment by N0tMyFaultOG** [comment] 2019-04-29 16:18
> If the error can be reproduced, it is likely an issue with a packet not being sent to the client.

Yeah, seems like particles aren't updated on clearing/deleting a plot
![](https://i.imgur.com/7F4Y4je.png)

**Comment by dordsor21** [comment] 2019-05-01 16:24
What server version/P2 version @N0tMyFaultOG ? @xAphex You are using the wrong P2 version for 1.13. You want to be using https://ci.athion.net/job/PlotSquared-Breaking/

**Comment by N0tMyFaultOG** [comment] 2019-05-01 16:30
@dordsor21 paper 624 and p2 breaking 268

**Comment by AeSix** [comment] 2019-05-19 03:38
Does this happen with just P2/FAWE? Just Paper, or Spigot too? 
Or has this been resolved with newer builds of Paper/FAWE/P2?

I believe I've seen something with AngelChests causing issues, but I can't find what I had seen.  It was a random bit I took in while looking up another issue.  Perhaps this or another plugin is the cause?  I cannot test on my server due to configuration.

**Closed** 2019-06-09 05:42 UTC
Labels: [!] Bug
