### ISSUE TITLE
After switching from version 1.12.2 to 1.13.2, the /plot delete command does not work

### ISSUE THREAD

**Issue by Nevdh** [IntellectualSites/PlotSquared#2681] opened 2020-02-08 17:03 UTC
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):
https://athion.net/ISPaster/paste/view/89af469084d94228ab643e96f53476d4

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-1a3504a-e7700ab (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *worldedit-bukkit-7.1.1-SNAPSHOT-dist*: 

### Description of the problem:

After switching from version 1.12.2 to 1.13.2, the /plot delete command does not work

### How to replicate:

1. /plot delete
2. Nothing happens, no messages in the chat

### Other plugins being used on the server:

Plugins: Citizens, CommandNPC-1.9.1, LuckPerms-4.4.30, Multiverse-Core-4.1.0, PlotSquared-Bukkit-4.455, Vault, ViaVersion-2.2.3, worldedit-bukkit-7.1.0, worldguard-bukkit-7.0.0

### Relevant console output, log lines, and/or screenshots:

ERROR log:
https://pastebin.com/7Qu8RiVz

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment] 2020-02-08 17:37
make a copy of your server, take it to 1.14.4, update it with --forceUpgrade  (and wait until it's done)
then take it to 1.15.1, again update with --forceUpgrade, and wait until it's done.

If you still have issues with your server using 1.15.1 and PS, let us know.

**Comment by fhebuterne** [comment] 2020-02-08 22:20
Same issue here with last paper 1.15.2 version and last FAWE version on test server, i will try to forceUpgrade with 1.14.4 and next forceUpgrade with 1.15.2

**Comment by fhebuterne** [comment] 2020-02-10 19:21
Hi,

I've do some tests so after migration from 1.12.2 to 1.13.2, worlds.yml is totaly broken id blocs was replaced by percentage.

I've try to migrrate on 1.14.4 or 1.15.2, same issue, this issue is caused by bad worlds.yml config.

Config worlds.yml 1.12.2 : https://pastebin.com/z7EM7bKa
Config worlds.yml 1.13.2 : https://pastebin.com/62QtkHDt

Could you fix this @AeSix please ?

Thanks,
Fabien

**Comment by Sauilitired** [comment] 2020-02-23 20:10
@fhebuterne he legacy converter was indeed broken, but has been fixed in the most recent commit.

**Closed** 2020-02-23 20:11 UTC
Labels: 1.13+, v5
