### ISSUE TITLE
Could not pass event PlayerTeleportEvent to PlotSquared v6.0.5-Premium

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/PlotSquared#3142] opened 2021-07-04 15:41 UTC
### Server Implementation

Paper

### Server Version

1.17

### Describe the bug

Error when player join to the server.

### To Reproduce

1. Download and install PlotSquared 6.0.5-Premium.
2. Download and install NoCheatPlus and Protocollib.
3. Start server and join.

### Expected behaviour

No error when player join to the server.

### Error log (if applicable)

https://pastebin.com/JngizFjL

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/5da0eb2d4630455fa7204f7d0ecc3d9a

### PlotSquared Version

6.0.5-Premium

### Checklist

- [x] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-07-04 15:45
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3105

**Comment by SirYwell** [comment] 2021-07-04 21:00
This issue seems to be caused by events being triggered before the player is actually online. We'll need to look deeper into it.

**Comment by dordsor21** [comment] 2021-07-10 09:35
This looks more like an issue with NoCheatPlus attempting to teleport players that are not fully logged in yet...

**Closed** 2021-07-26 20:36 UTC
Labels: Invalid
