### ISSUE TITLE
Auto clear does not work

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/PlotSquared#3052] opened 2021-05-19 21:21 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Plot expiry and analysis do not work. No task appears to run, and if I attempt to manually analyze a plot using /p debugexec analyze, I get an error in the console.

### To Reproduce

1. Enable plot expiry in settings.yml and create an auto purge task that should remove plots
2. Notice plots are not removed, with no errors in console.
3. Stand on a plot and try to run /p debugexec analyze and see error in console

### Expected behaviour

No error in console.

### Error log (if applicable)

https://gist.github.com/Xaver106/dd4f68d9bdfa6c8117df9627939e73df

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/05154c2198b4478fa91faa211420e46e

### PlotSquared Version

PlotSquared-5.13.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-05-22 15:02
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3006

**Closed by NotMyFault** 2021-05-22 15:02 UTC
Labels: Requires Testing
