### ISSUE TITLE
The title that appears in the center of the screen is not displayed. (1.21.1)

### ISSUE THREAD

**Issue by fadfhkdfga** [IntellectualSites/PlotSquared#4470] opened 2024-08-10 14:17 UTC
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

The title that appears in the center of the screen is not displayed.

### To Reproduce

.

### Expected behaviour

.

### Plot Debugpaste

.

### PlotSquared Version

7.3.8-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment] 2024-08-10 14:28
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/4465

**Closed** 2024-08-10 14:28 UTC
Labels: Requires Testing
