### ISSUE TITLE
Players can't place blocks in certain areas

### ISSUE THREAD

**Issue by Permanently** [IntellectualSites/PlotSquared#1120] opened 2016-05-15 17:33 UTC
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/nusunigijo

**Description of the problem:**
So what's happening is that players have plots which in certain parts of it can't be edited (they can break blocks, but not place). It happens to random plots, and sometimes relogging fixes the issue. Other times, restarting the server fixes it. 

**How to replicate**: I have absolutely no idea, it just randomly happens. However, if you want to see what's happening, then I can give you my server IP.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment] 2016-05-15 18:21
Since you're using a development version, which exact build is that?

**Comment by manuelgu** [comment] 2016-05-15 18:29
HoloPlots is not supported for the current version of PlotSquared and is throwing a lot of exceptions, please remove the jar.

Disable plotme convert in your settings.yml

**Comment by Permanently** [comment] 2016-05-15 18:43
I am using dev build #115.

**Comment by manuelgu** [comment] 2016-05-15 19:23
In case  the problem is still occuring,

is it per-area or per-player, so can all players not build in certain areas or are there places where some people can build and some not?

Are the players that cannot build there owner of the plot, are they added or trusted? Are the admins bypassing the protection?

Are the plots marked as done?

Does it happen around 0,0 or is it spread on different plots all around the plot world?

**Comment by Permanently** [comment] 2016-05-15 20:03
I'm not sure but as op I can build there whilst they can't. I'm going to take a guess and say it's per-player, but I'll see if it's just because I'm op or if it actually is per-player.
Yes, I've only had these problems with the owners of the plot. No, they are not marked as done.

Yep, they are near 0;0, but spawn protection is on 0.

**Comment by manuelgu** [comment] 2016-05-15 20:11
> Yes, I've only had these problems with the owners of the plot.

Can you confirm that it has only happend to plot owners and never to added or trusted players?

> I'm going to take a guess and say it's per-player, but I'll see if it's just because I'm op or if it actually is per-player.

Maybe you can get two normal players into trying to build at the specific location? Would make things a lot easier :)


Also make sure that no other plots are conflicting with the areas, see if any plugins related to protection/areas/limiting building etc could be conflicting with PlotSquared.

**Comment by manuelgu** [comment] 2016-05-15 20:19
Looking at the code there are five cases in which block placing gets cancelled

1. [See](https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L2315) When the block is above MAX_BUILD_HEIGHT or below MIN_BUILD_HEIGHT
2. [See](https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L2320) When the plot is null (is road or not in a plot area)
3. [See](https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L2303) The plot is marked as done
4. [See](https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L2297) Player is neither owner nor added and does not have admin bypass permission
5. [See](https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L2284) The plot has no owners and the player has no admin bypass permission

**Comment by MattBDev** [comment] 2016-05-16 20:08
Super out of date dev version. Plus you are using a dev version.

**Comment by boy0001** [comment] 2016-05-17 06:04
Check the `server.properties` -> `spawn-protection` is set to 0.
Any message is sent when they try to build?

**Comment by Permanently** [comment] 2016-05-17 06:27
No message. Once again, they can break, but not place.

**Comment by MattBDev** [comment] 2016-05-17 21:56
Try disabling plugins 1 by 1 to make sure PlotSquared is the issue.

**Comment by MattBDev** [comment] 2016-05-21 00:41
@Permanently I am going to assume your problem is fixed since you have not replied.

**Comment by MattBDev** [comment] 2016-05-21 15:42
assuming this issue is fixed

**Closed by MattBDev** 2016-05-21 15:42 UTC

**Comment by Maxetto** [comment] 2016-08-19 01:07
I'm reopening this as I have this exact issue too. Somewhere in the Plot I can destroy but not build under y=56. No errors, nor messages, just the block disappearing (It desappears to me too, with "*" permission (but not OP)). The plot is nowhere around 0,0.

I'm using PlotSqured 3.4.5. @MattBDev 

http://hastebin.com/uzaqexubaf

**Comment by Demeng7215** [comment] 2017-12-17 13:18
I also have this issue. Please fix!
