### ISSUE TITLE
"Can Build" Permission on Plots are random

### ISSUE THREAD

**Issue by AnimeDrache** [IntellectualSites/PlotSquared#3856] opened 2022-10-25 08:16 UTC
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

I am NOT able to place minecarts on server-plots or on other unclaimed or not owned by myself plots (I am admin so I am able to build everywhere everytime but not for minecarts. that might be a bug. plus I definitely need to be able to do that on the server-plot)

### To Reproduce

1. create a PLOT WORLD
2. try to place mine carts on an unclaimed plot (on rails) or on a server-plot

### Expected behaviour

Being able to place minecarts on everywhere (or at least server-plots)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/61c45bb549a348ec9a2876ae2c0790aa

### PlotSquared Version

PlotSquared-Bukkit-6.10.2-Premium.jar

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment] 2022-10-25 08:24
Duplicate of #3850

**Closed** 2022-10-25 08:24 UTC
Labels: Requires Testing
