### ISSUE TITLE
Cant translate /p help all 

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3906] opened 2023-01-03 21:30 UTC
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

I want to translate this: 
![image](https://user-images.githubusercontent.com/38475631/210444013-9faddb20-e04b-49fd-9ce6-1b58787e6c95.png)
But there is nothin in the lang file.

### To Reproduce

Try to translate!

### Expected behaviour

It should be translateable

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/38475631/210444112-8725ab7a-8ead-427e-a6be-05426b2f02c0.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/39b4ba1b8c8e4c05b170f671132ce825

### PlotSquared Version

6.10.5-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment] 2023-01-06 12:56
Duplicate of #3167

**Comment by DevJoey** [comment] 2023-01-09 15:01
I have removed the duplicate! Please reopen! Thx

**Comment by NotMyFault** [comment] 2023-01-13 23:31
Exists in https://github.com/IntellectualSites/PlotSquared/blob/6a34a1996f821f99617cb3ada67bc40ca93bb668/Core/src/main/resources/lang/messages_en.json#L440

**Comment by NotMyFault** [comment] 2023-01-13 23:43
Pushed https://github.com/IntellectualSites/PlotSquared/commit/1448d8d4af8445fa15a4648699fae00954d1f040 to fine grain this behavior in v7.

**Closed by NotMyFault** 2023-01-13 23:43 UTC
Labels: Requires Testing

**Comment by DevJoey** [comment] 2023-01-15 21:03
> Exists in
> 
> https://github.com/IntellectualSites/PlotSquared/blob/6a34a1996f821f99617cb3ada67bc40ca93bb668/Core/src/main/resources/lang/messages_en.json#L440

This is not the message shown in /p help You see there ias a <prefix> tag in front and a dot at the end! On the /p help message is no prefix and no dot! This message dont change the Description displayed in /p help
