### ISSUE TITLE
road-schematic: block_claimed & block override ROAD schematic

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2521] opened 2019-10-04 00:32 UTC
What is actually the current configuration for a road-schematic (same before and after claim) without any block-change of the border?

On older versions block_claimed & block are ignored If that was undefined. Currently PlotSquared **set AIR blocks** in this position and **override my border schematic**.

```
[...]
    wall:
      filling: cyan_terracotta
      height: 62
      block_claimed: ''
      block: ''
[...]
    schematic:
      specify_on_claim: false
      on_claim: false
      file: ''
      schematics:
      - ''
[...]
```

schematic in
- PlotSquared/schematics/GEN_ROAD_SCHEMATIC/<worldname>/intersection.schem
- PlotSquared/schematics/GEN_ROAD_SCHEMATIC/<worldname>/sideroad.schem

before (normal world-generation with ROAD schematics):
![2019-10-04_02 21 46](https://user-images.githubusercontent.com/4140635/66172980-4d495580-e64e-11e9-8bce-88c9ab23735f.png)

after "/p claim":
![2019-10-04_02 21 59](https://user-images.githubusercontent.com/4140635/66172998-5d613500-e64e-11e9-9ffd-502c4d46494e.png)

**[REQUIRED] Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment] 2019-10-04 00:34
@Sauilitired @dordsor21 why did you have to go and break things?

**Comment by Sauilitired** [comment] 2019-10-04 09:05
Well, technically speaking it did set the block to... nothing, just as was specified. Set block_claimed to whatever you want it to be. Which is obviously problematic considering you have a pattern.

A good solution would be to introduce a new field where the user may specify whether or not the claimed wall block field should be used at all, rather than ignoring empty values. If anyone wants to do that, then yay.

As for why we had to break things. I guess we could have let the plugin die last year when no one else worked on it. Dropping support for post 1.12 would have been an option. We didn’t have to, we’re just bloody cruel.

**Comment by AeSix** [comment] 2019-10-04 09:45
Well, I thought the plot border wall was part of the plot, not the road?

Personally, I feel that's how it should be.  If admins want their border wall to be something other than the two options provided (available and claimed) then they should set both to the same material and incorporate that into the design.  Or actually use the plot schematic as designed.

The most I could give this is as a bug report for '' setting air... but what else should it do? Halt the function until the admin adds something?  Assuming air might not be the best solution, but it's a solution.  As pointed out, it's functioning by design. 

So, closing this because the plugin is working as designed. 

If @RedstoneFuture wants to add a feature request, it should be done through https://github.com/IntellectualSites/PlotSquaredSuggestions/issues

**Comment by RedstoneFuture** [comment] 2019-11-08 18:53
Reopen because boy001 said it's a bug.

https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/63

**Comment by RedstoneFuture** [comment] 2019-11-08 18:54
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/07fcd53bf86bdec7810cdd7d9887c2b5d2a04123

**Closed** 2019-11-08 18:54 UTC

**Comment by fjeddy** [comment] 2019-11-22 00:19
@RedstoneFuture So how do you now accomplish no air being set? So that it uses the road schematic (As originally designed), instead of the buildt in road / wall generator?

It seems to me that all this "fix" does, is set the value as air if nothing else is set. Which is still the incorrect behavior :/

**Comment by AeSix** [comment] 2019-11-22 02:14
@fjeddy  There are blocks which you can use, which when pasted (at least through mojang's means) acts as air, except that it will NOT replace any other blocks with air.  Would be interesting to see if that works with WE/FAWE.

**Comment by fjeddy** [comment] 2019-11-22 18:27
Which blocks?

The goal here is to use the road schematic, as it was intended by design, and whatever comments above how the wall is part of the plot and the road, is a drastic change of such design.

In other words, how, specifically, with this new "fix", do you only use the wall in the road schematic, and avoid using the wall generator entirely?
