### ISSUE TITLE
claiming is not working

### ISSUE THREAD

**Issue by chaosflo44-plus** [IntellectualSites/PlotSquared#2525] opened 2019-10-06 14:57 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** Uploaded a full debug to: https://athion.net/ISPaster/paste/view/8edd60623e3540ea8450acdc2097211e

**[REQUIRED] Spigot/Paper Version Number:** Spigot-1.14.4-ea7e48b-20190808-1048

**[REQUIRED] Minecraft Version Number:** 1.14.4

**[REQUIRED] Description of the problem:** if i type /p claim or /p auto just nothing hapens ):

**Any relevant console output or screenshots:** No console output.

**Plugins being used on the server:**
Plugins (14): WorldEdit, Essentials, PermissionsEx, PlugMan, ChatEx, ViaVersion, Kopf, PlotSquared, AutoVanishForCP, BuycraftX, MyCommand, Multiverse-Core, WorldGuard, Multiverse-SignPortals

**How to replicate:** 
Execute /p claim or /p auto

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-10-06 17:28
You have multiple issues ranging from using wrong-versions of plugins, missing dependency plugins to potentially wrong file encoding.  There is multiple portions of the log which have formatting (implicit and explicit) which may be affecting your server operations. 

Additionally, configurations using Multiverse/MultiWorld are tricky to setup.  You should ensure you can run PlotSquared properly without Multiverse. 

Please test with MV disabled, ViaVersion removed, Vault added, and update other plugins as needed.  Report back on this ticket when you have performed this.

**Comment by AeSix** [comment] 2019-10-13 11:23
@chaosflo44-plus If this is still an issue, please read my previous instructions and reply.  If we deem the issue is caused be PlotSquared, we'll reopen the issue.  Until then, it's being closed as user configuration errors.

**Closed by AeSix** 2019-10-13 11:23 UTC
Labels: 1.14.x, Awaiting response, [?] Testing Required
