### ISSUE TITLE
Plots unlink / unclaim automaticly

### ISSUE THREAD

**Issue by Sckaletz** [IntellectualSites/PlotSquared#726] opened 2015-11-18 10:30 UTC
Newly made plot world with version 3.2.18. Plots have unclaimed itself and has been claimed by other players. These two examples use to be a huge merged plot. This has happened within 24 hours after launch.

http://imgur.com/kHR80ho
http://imgur.com/85yQ1EM

**Comment by MattBDev** [comment] 2016-02-15 14:01
Duplicate of #801

**Closed by MattBDev** 2016-02-15 14:01 UTC
Labels: [✖] Duplicate
