### ISSUE TITLE
PlotSquared "corrupt tile entity"

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#2465] opened 2019-08-15 12:45 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  PlotSquared-4.298

**[REQUIRED] Spigot/Paper Version Number:** Paper Build 639

**[REQUIRED] Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
worlds.yml: https://pastebin.com/4QUjDJHn
settings.yml https://pastebin.com/JQu1Vraj

**[REQUIRED] Description of the problem:** 
As requested in: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/178 I've made a ticket on here. Paper has a config option which removes corrupt tile entities.
`remove-corrupt-tile-entities: true`
I've been getting this error ocasionally.
Log: https://pastebin.com/h4RSUkhn

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-08-15 14:10
pasting log in issue since there's been issues with pastes expiring:

```
[16:28:10] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.server.v1_13_R2.TileEntitySign@571ebb06) at 31513,49,-32245 (Block{minecraft:dirt}) where there was no entity tile!
[16:28:10] [Server thread/WARN]: Chunk coordinates: 31504,-32256
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:878)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:851)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:1460)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:827)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.getTileEntity(World.java:1951)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.getTileEntity(WorldServer.java:132)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.n(World.java:2011)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.BlockTileEntity.remove(SourceFile:39)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.IBlockData.remove(IBlockData.java:224)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Chunk.setType(Chunk.java:556)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.setTypeAndData(World.java:431)
[16:28:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.setTypeAndData(CraftBlock.java:168)
[16:28:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.setBlockData(CraftBlock.java:155)
[16:28:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.setType(CraftBlock.java:144)
[16:28:10] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.block.BukkitLocalQueue.setBaseBlocks(BukkitLocalQueue.java:106)
[16:28:10] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.block.BukkitLocalQueue.setComponents(BukkitLocalQueue.java:73)
[16:28:10] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.block.BasicLocalBlockQueue.execute(BasicLocalBlockQueue.java:69)
[16:28:10] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.block.BasicLocalBlockQueue.next(BasicLocalBlockQueue.java:55)
[16:28:10] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:33)
[16:28:10] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:30)
[16:28:10] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal2.run(RunnableVal2.java:16)
[16:28:10] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.block.GlobalBlockQueue.lambda$runTask$0(GlobalBlockQueue.java:106)
[16:28:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[16:28:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[16:28:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[16:28:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:28:10] [Server thread/INFO]: Removing corrupt tile entity
```
Note: This is a copy and paste from SecretlyJealous' pastebin.

**Comment by AeSix** [comment] 2019-08-15 14:14
@SecretlyJealous is this a repeatable thing when using 1.14.4? 
Additionally, upgrade to the newest breaking release from https://ci.athion.net/view/Everything/job/PlotSquared-Breaking/
and test this issue.  Update the ticket when you have more info.

If this issue is resolved, it'll be in breaking long before it's in the stable release on spigotmc. 

Thanks! :)

**Comment by AeSix** [comment] 2019-08-29 13:40
@SecretlyJealous just a thought.  I had this happen when I first moved to 1.13.2, I didn't forge upgrade the world.  After re-upgrading from my 1.12.2 backup, using --forceUpgrade I no longer had this issue.  I don't know what that would do to a world that's already got 1.13.2 chunks in it though.  

Anyways, did you start the world in 1.12.2 or earlier and not force upgrade?  If not, you can probably ignore the errors and they'll eventually all be resolved as the world is upgrade through chunk loading.  If you did force upgrade, or started the world in 1.13.2, then the issue is definitely something else.

**Comment by SecretlyJealous** [comment] 2019-10-26 16:47
I used the --forceUpgrade flag when I moved from 1.12.2 to 1.13.2. I'm currently on the breaking build and have not noticed this error yet. If it does appear again I'll update this.

**Comment by RedstoneFuture** [comment] 2019-10-27 01:16
On normal worlds you get this or similar warns with the 1.12.x to 1.13.x update too. Its maybe only a problem of spigot / paper. Can FAWE / PS fix this problem of plugin side? It this the job of them.

I mean I have got only one time this message. After a first chunk load it was clean.

**Comment by AeSix** [comment] 2019-10-27 02:56
Closing ticket.   re-open if the issue re-appears. 

@RedstoneFuture  The issue is file contents, which is controlled by the minecraft server - only so much a plugin *should* do to override the base server for that.  But yes, it's possible for someone to write a plugin to update the files individually through spigot.

**Closed by AeSix** 2019-10-27 02:56 UTC
Labels: 1.13+, Spigot, [-] Low Priority, [?] Testing Required
