### ISSUE TITLE
after plot-merge: all signs deleted or wrong sign-location

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#1930] opened 2018-04-27 18:26 UTC
**Description of the problem:** 
Its a small bug.
After deleting of a merged plot (e.g. 1x2) you have 2 sign at this plot border. After the deleting one sign will not remove.

**How to replicate:** 

1. Get you two plots.
![2018-04-27_20 17 21](https://user-images.githubusercontent.com/4140635/39378519-ec524fe4-4a58-11e8-9e17-a57887aca20c.png)

2. Merge this plots. (/p merge)
![2018-04-27_20 17 48](https://user-images.githubusercontent.com/4140635/39378537-f6dee7ce-4a58-11e8-9cbc-f78ba03a5c96.png)

3. Delete the merged plot. (/p delete)
![2018-04-27_20 20 13](https://user-images.githubusercontent.com/4140635/39378543-f9a98d92-4a58-11e8-8391-54b5a6af5df9.png)

**Checklist**:

- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment] 2019-01-10 15:19
If you still have this issue, reopen.

**Comment by AeSix** [comment] 2019-03-17 04:29
Yup, still an issue with 1.13.2 / P2 4.184
https://puu.sh/D18af/35377c4ec7.png

**Comment by AeSix** [comment] 2019-07-30 12:26
@RedstoneFuture  is this still an issue with breaking builds?

**Comment by AeSix** [comment] 2019-07-31 12:49
As of Spigot 1.13.2 / P2 4.305
This is still an issue.  The sign remains when plots are merged. The sign is not updated at all.
Upon unlinking the plots, the mid-plot sign is updated.

I found that the sign is not updated at all on merge due to me having changed my name.  It showed my name on the sign after merge, but after unlink, it shows "____Unknown____"  Additionally, unlinking results in a massive empty space between plots. Still. Will update the appropriate issue for that.

**Comment by RedstoneFuture** [comment] 2019-10-23 19:00
Still a problem if you merge to the west side:

**to west | wrong:**
![2019-10-23_20 56 23](https://user-images.githubusercontent.com/4140635/67425274-fcd37100-f5d7-11e9-80eb-e8300893afd6.png)
![2019-10-23_20 55 56](https://user-images.githubusercontent.com/4140635/67425276-fcd37100-f5d7-11e9-88f3-a62254400eef.png)

**to east| right:**
![2019-10-23_20 56 07](https://user-images.githubusercontent.com/4140635/67425277-fcd37100-f5d7-11e9-97a1-189f873d32ea.png)
![2019-10-23_20 56 16](https://user-images.githubusercontent.com/4140635/67425278-fd6c0780-f5d7-11e9-9fed-01388be3ae6d.png)


https://athion.net/ISPaster/paste/view/db5e43ab90fb435c9287d0d97104ea52

**Comment by dordsor21** [comment] 2020-05-15 10:22
Can anyone confirm if this is still an issue in v5? I can imagine this may have been caused by the old funky sign stuff that used old funky chunk stuff

**Comment by RedstoneFuture** [comment] 2020-05-16 00:05
I will test it as soon as possible.

**Comment by RedstoneFuture** [comment] 2020-05-19 00:25
It's still a problem.

For example, we have 4 plots. And one owner. After all follow steps we use "/p unmerge"!

![2020-05-19_02 00 13](https://user-images.githubusercontent.com/4140635/82270276-8c75ae00-9974-11ea-84c6-3545fd289fec.png)


**Situation 1:**

the owner standing on  plot 1 and looking to plot 2 (east)
= PS "remove all signs" and "set" the new plot-sign on the left top side -->OK

**Situation 2:**

the owner standing on  plot 2 and looking to plot 1 (west)
= the plugin down't break the sign on the plot where the player standing on (**bug A**)

![2020-05-19_02 09 06](https://user-images.githubusercontent.com/4140635/82270673-d4e19b80-9975-11ea-97d4-5f0371371dc0.png)

**Situation 3:**

the owner standing on  plot 2 and looking to plot 3 (south)
= PS "remove all signs" and "set" the new plot-sign on the left top side -->OK

**Situation 4:**

the owner standing on  plot 3 and looking to plot 2 (north)
= PS "remove all signs" and "set" the new plot-sign on the old path ... and then PS delete all paths in the plot --> this plot has no sign.

![2020-05-19_02 18 56](https://user-images.githubusercontent.com/4140635/82271086-1d4d8900-9977-11ea-9372-16b64bafd364.png)



Ouh .. I hope this was understandable with this step-by-step tutorial at now. :)

**Comment by N0tMyFaultOG** [comment] 2020-05-22 21:35
Please reopen the issue on youtrack.

**Closed by N0tMyFaultOG** 2020-05-22 21:35 UTC
Labels: 1.13+, Spigot, [!] Bug, [‼] high priority

**Comment by RedstoneFuture** [comment] 2020-05-23 10:17
moved to: https://issues.intellectualsites.com/issue/PS-19
