### ISSUE TITLE
Plot Bottom, top calculation problem

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#420] opened 2015-07-17 22:49 UTC
Hi,

I have 100x100 plots. I printed plot.getBottom() and plot.getTop() coords to console with my plugin (Using PlotSquared API) and I get this:

![bottom_top](https://cloud.githubusercontent.com/assets/3225958/8758607/56cfba16-2ce6-11e5-9b0f-d8d68ebd5989.png)

I made screenshot ingame:

Bottom (x and z?):
![2015-07-18_00 43 14](https://cloud.githubusercontent.com/assets/3225958/8758620/7578b83c-2ce6-11e5-85ce-045745b9d811.png)

Top (z?):
![2015-07-18_00 43 22](https://cloud.githubusercontent.com/assets/3225958/8758624/7e3a3e50-2ce6-11e5-9041-acc83a8edc8f.png)

**Comment by Sauilitired** [comment] 2015-07-17 23:35
That's intended :D

**Comment by diecode** [comment] 2015-07-17 23:42
This cause lots of problem :)

**Comment by Sauilitired** [comment] 2015-07-18 00:04
How? If you are using the API, then just adding (1, 0, 1) onto the bottom coordinates, will fix whatever issues you're experiencing. The offset is in there, for a reason that made sense back when we added it. Whatever it was, it must have been important.

**Comment by diecode** [comment] 2015-07-18 00:10
I am using getPlot(player) and when the Player is near the plot's border, then the plot variable will be null

**Comment by Sauilitired** [comment] 2015-07-18 00:12
That should never be the case. As long as the player isn't on the border, as the border isn't classed as a part of the plot. As soon as you're on the border, you're outside the plot.

However, if you can confirm that it's null whilst the player haven't left the plot (no PlayerLeavePlotEvent), then this is an actual bug. However, due to recently working with the events for a scoreboard plugin, I have tested everything - with no obvious issues.

**Comment by diecode** [comment] 2015-07-18 00:13
The plot is null in this row:

![2015-07-18_02 12 34](https://cloud.githubusercontent.com/assets/3225958/8759356/9320b36a-2cf2-11e5-8e18-d667b22a4247.png)

**Comment by Sauilitired** [comment] 2015-07-18 00:18
Strange :_: I'll make sure to get this tested tomorrow.

**Comment by diecode** [comment] 2015-07-18 00:51
I tested this problem with PlotSquared 2.12.0 and it is working fine. So, this is a new bug. The 2.12.7 - 2.12.8 is affected.

YouTube video about bug: https://youtu.be/gM73Ms1x6OI

**Comment by boy0001** [comment] 2015-07-18 06:34
The issue is with the rounding of negative locations for the player move / teleport events, This will be fixed shortly

**Closed** 2015-07-18 07:48 UTC
