### ISSUE TITLE
/plot delete - A set block timer is bound to either the current plot or you. Please wait for it to finish.

### ISSUE THREAD

**Issue by superkrebs13** [IntellectualSites/PlotSquared#3343] opened 2021-11-22 22:53 UTC
### Server Implementation

Spigot

### Server Version

1.17.1

### Java Versions (tested)

Java 16.0.1 Zulu
Java 16.0.2+7 Temurin

### Describe the bug

After claiming a plot "/plot claim" I got teleported to it.
If I enter plot and type "/plot delete" nothing is happend. After typing it again the message "A set block timer is bound to either the current plot or you. Please wait for it to finish." appeared.

**If the world is generated as a flat/normal world, this error didn't occurs.**

### To Reproduce

1. Generate a augmented or partial world with predefined/default values
2. Claim a plot
3. Get into the claimed plot
4. Show info of plot and make sure that you're the owner
5. Try to delete the plot (Nothing will be promted to the console)
6. Type the delete command once again to the console - error occurs

### Expected behaviour

The plot have to be deleted.

### Plot Debugpaste

Java 16.0.1 Zulu
https://athion.net/ISPaster/paste/view/e39d51e936ea41cd9f69da70993e0137

Java 16.0.2+7 Temurin
https://athion.net/ISPaster/paste/view/0b2ba302aea94f4dbb3adde606aa8d59

### PlotSquared Version

PlotSquared-6.1.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I'm using a proxmox hypervisor with Debian 11 running a LXC Container with nesting activated on it.

[Server thread/INFO]: This server is running CraftBukkit version 3284-Spigot-3892929-0ebef35 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

Steps how I create the world:

[00:05:22] [Server thread/INFO]: superkrebs issued server command: /plot setup PlotSquared
[00:05:32] [Server thread/INFO]: superkrebs issued server command: /plot setup partial
[00:05:40] [Server thread/INFO]: superkrebs issued server command: /plot setup worldorder
[00:05:51] [Server thread/INFO]: superkrebs issued server command: /plot setup 0,0
[00:05:56] [Server thread/INFO]: superkrebs issued server command: /plot setup 11,0
[00:06:00] [Server thread/INFO]: superkrebs issued server command: /plot setup ALL
[00:06:04] [Server thread/INFO]: superkrebs issued server command: /plot setup 62
[00:06:06] [Server thread/INFO]: superkrebs issued server command: /plot setup 42
[00:06:14] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:stone
[00:06:19] [Server thread/INFO]: superkrebs issued server command: /plot setup true
[00:06:25] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:grass_block
[00:06:30] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:stone_slab
[00:06:36] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:sandstone_slab
[00:06:40] [Server thread/INFO]: superkrebs issued server command: /plot setup 7
[00:06:43] [Server thread/INFO]: superkrebs issued server command: /plot setup 62
[00:06:50] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:quartz_block
[00:06:58] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:stone
[00:07:02] [Server thread/INFO]: superkrebs issued server command: /plot setup 62
[00:07:06] [Server thread/INFO]: superkrebs issued server command: /plot setup true
[00:07:11] [Server thread/INFO]: superkrebs issued server command: /plot setup wolrd139

**Comment by NotMyFault** [comment] 2021-11-26 15:42
Can you replicate that by using an up to date version of WorldEdit and Paper?

**Comment by superkrebs13** [comment] 2021-11-26 16:22
Hello,

setted up a fresh and clean paper with word edit and premium version of plot squared.

**Comment by superkrebs13** [comment] 2021-11-29 12:22
Problem persits.

https://athion.net/ISPaster/paste/view/4127043609944036bd62e782e5514125

Any Idea?

**Comment by F-TownGaming** [comment] 2022-01-14 23:34
we have the same problem on a Paper 1.18.1 Server FAWE Worldedit is the newest version 68 and Plotsquared is 6.3.0

**Comment by F-TownGaming** [comment] 2022-01-19 11:18
No Answer to Fix this Problem?????

**Comment by F-TownGaming** [comment] 2022-01-19 11:23
please take care of this bug. we too have the exact same problem.

**Comment by superkrebs13** [comment] 2022-01-19 11:35
The publisher isn't interested in fixing this issue.

**Comment by F-TownGaming** [comment] 2022-01-19 11:38
If this is the case, we will no longer use Plotquated and will promote it, on the contrary, we will include plotsquaren in the list of the worst plugins and warn users not to spend money on it

**Comment by superkrebs13** [comment] 2022-01-19 11:44
We also changed the plugin and will retrieve our money from visa. For a payed plugin, it's the worst support I've ever seen.

**Comment by NotMyFault** [comment] 2022-01-19 11:47
I was not able to replicate your issue with the steps provided on the environments provided. And apparently only one other person ran into it but provided no clear instructions how to replicate it.

> See the date of creation - the publisher isn't interested in fixing this issue.

I'm unsure where we ever stated that we will no longer look into the issue? The issue has been reported ~1 month-ish ago and is no show stopper.
General rule of thumb is, that is this an open source project, where everyone is welcome to contribute features, fixes or documentation (like in the nature of any other open source project).
You are more than welcome to look into it yourself and provide a solution that applies to a reproducible list of steps and help to fix your issue.
This is not one of our daytime jobs and we have no obligation to deliver a fix in any specific time frame. We, and any other our other contributors, look into issues when and if we have the time to.
Many of us are working full time, are engaged with major exams or are involved in other time consuming projects.

> For a payed plugin, it's the worst support I've ever seen.

You bought the plugin to support the people behind it. It's not a support contract with any obligation to deliver a solution to your problem. Yet again, you are more than welcome to look into itself and help resolving the issue, like in the nature of open source projects.

**Comment by F-TownGaming** [comment] 2022-01-19 11:53
We've already found an alternative to Plotsquared because we need a working server and can't wait forever for bug fixes we're sorry that we can't support you any further but that's life for the better wins

**Comment by superkrebs13** [comment] 2022-01-19 11:53
`Many of us are working full time, are engaged with major exams or are involved in other time consuming projects.
PlotSquared is not the center of the universe everything else wraps around.`

Feel this. 
Thanks for your reply. For me, the issue is solved :)

**Comment by DJMagicMike76** [comment] 2022-01-20 10:35
erver Implementation

Paper
Server Version

Paper 1.18.1 163
Java Versions (tested)

openjdk-17-jre:
  Installiert:           17.0.1+12-1+deb11u2
  Installationskandidat: 17.0.1+12-1+deb11u2
  Versionstabelle:
 *** 17.0.1+12-1+deb11u2 500
        500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
        100 /var/lib/dpkg/status
     17~19-1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
openjdk-17-jdk:
  Installiert:           17.0.1+12-1+deb11u2
  Installationskandidat: 17.0.1+12-1+deb11u2
  Versionstabelle:
 *** 17.0.1+12-1+deb11u2 500
        500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
        100 /var/lib/dpkg/status
     17~19-1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages

Describe the bug

After claiming a plot "/plot claim" I got teleported to it.
If I enter plot and type "/plot delete" nothing is happend. After typing it again the message "A set block timer is bound to either the current plot or you. Please wait for it to finish." appeared.

If the world is generated as a flat/normal world, this error didn't occurs.
To Reproduce

    Generate a augmented or partial world with predefined/default values
    Claim a plot
    Get into the claimed plot
    Show info of plot and make sure that you're the owner
    Try to delete the plot (Nothing will be promted to the console)
    Type the delete command once again to the console - error occurs



PlotSquared Version

PlotSquared-6.3.0-Premium
Checklist


[Server thread/INFO]: This server is running Paper version git-Paper-163 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 4533821)

Steps how I create the world:

[14:05:22] [Server thread/INFO]: superkrebs issued server command: /plot setup PlotSquared
[14:05:32] [Server thread/INFO]: superkrebs issued server command: /plot setup partial
[14:05:40] [Server thread/INFO]: superkrebs issued server command: /plot setup worldorder
[14:05:51] [Server thread/INFO]: superkrebs issued server command: /plot setup 0,0
[14:05:56] [Server thread/INFO]: superkrebs issued server command: /plot setup 11,0
[14:06:00] [Server thread/INFO]: superkrebs issued server command: /plot setup ALL
[14:06:04] [Server thread/INFO]: superkrebs issued server command: /plot setup 62
[14:06:06] [Server thread/INFO]: superkrebs issued server command: /plot setup 42
[14:06:14] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:stone
[14:06:19] [Server thread/INFO]: superkrebs issued server command: /plot setup true
[14:06:25] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:grass_block
[14:06:30] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:stone_slab
[14:06:36] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:sandstone_slab
[14:06:40] [Server thread/INFO]: superkrebs issued server command: /plot setup 7
[14:06:43] [Server thread/INFO]: superkrebs issued server command: /plot setup 62
[14:06:50] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:quartz_block
[14:06:58] [Server thread/INFO]: superkrebs issued server command: /plot setup minecraft:stone
[14:07:02] [Server thread/INFO]: superkrebs issued server command: /plot setup 62
[14:07:06] [Server thread/INFO]: superkrebs issued server command: /plot setup true
[14:07:11] [Server thread/INFO]: superkrebs issued server command: /plot setup citybuild3

**Comment by DJMagicMike76** [comment] 2022-01-20 10:36
pleace fix this

**Comment by DJMagicMike76** [comment] 2022-01-24 08:24
it would be possible to give a short feedback when this error will be tackled because we would have to look around for an alternative. I know you have little time and understand that. A bit of info avoids misunderstandings

**Comment by DJMagicMike76** [comment] 2022-01-25 07:14
> See the date of creation - the publisher isn't interested in fixing this issue.

I unfortunately have to agree with that. if you don't even have 2 minutes for a feedback, you should leave it alone. felt no sow cares about this bug. I'm very disappointed, I would have expected at least a feedback like "yes, it's our turn and we'll take care of it shortly" for this problem

**Comment by DJMagicMike76** [comment] 2022-01-26 08:32
no answer, no reaction, what kind of support is that

**Comment by dordsor21** [comment] 2022-01-26 08:42
"yes it's our turn and we will look into and maybe implement a fix if and when we have time, since we're all volunteering our free time for this. Personally, I am in the middle of University exams, which I feel are more important than responding to a GitHub issue to state that we have received an issue and saying nothing that's ultimately going to be much use since we cannot just drop everything we do and are doing just to fix a bug for you, personally."

**Comment by DJMagicMike76** [comment] 2022-01-26 08:48
521 / 5.000
Übersetzungsergebnisse
then you shouldn't ask for money for this plugin if you can't take care of it properly.
Your reaction does not speak for buying this plugin if the reaction is so snotty.
Then do what you want, we will look for an alternative so you can scare off your users.
In addition, I'm not the only one who has the problem, be happy if you are made aware of mistakes instead of giving such outrageous answers.
Plotsquared is done for me, have a nice life.

**Comment by dordsor21** [comment] 2022-01-26 08:51
Ok

**Comment by PierreSchwang** [comment] 2022-01-26 16:31
As I'm able to replicate the issue using the steps from the original post, I'll mark the issue as a valid bug. 
![grafik](https://user-images.githubusercontent.com/27054324/151204917-69c837e2-71d0-47b1-a32f-40f295128d2c.png)

**Closed** 2022-01-27 11:13 UTC
Labels: Bug, Approved
