### ISSUE TITLE
Errors /p clear / bug

### ISSUE THREAD

**Issue by 1Pootis1** [IntellectualSites/PlotSquared#3146] opened 2021-07-09 01:15 UTC
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

I write the /p clear command when I remove a lot of blocks, this error also appears when I enter /set air, again, if there are a lot of blocks, help plz

### To Reproduce

1. I write /p clear
2 see error

### Expected behaviour

normal cleaning

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/73141732/125009808-f025d380-e06d-11eb-91c7-1ae73ae5100a.png)
![image](https://user-images.githubusercontent.com/73141732/125009060-7c36fb80-e06c-11eb-90e0-81d86e2af99b.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/6f78c1a89b0e48a1b24e584bc516f925

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9c253789c15243d588b9d100b3a377b9

### PlotSquared Version

PlotSquared version 6.0.6-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

-

**Comment by NotMyFault** [comment] 2021-07-09 08:45
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1048

**Closed by NotMyFault** 2021-07-09 08:45 UTC
Labels: Duplicate, Invalid
