### ISSUE TITLE
Version 3.5.0 updater regarding same update

### ISSUE THREAD

**Issue by NinoM4ster** [IntellectualSites/PlotSquared#1587] opened 2017-04-18 23:33 UTC
# Bug report template 

**Debug paste link:** 
https://pastebin.com/raw/6j7VTjCq
**Description of the problem:** 
When PlotSquared is updated to version 3.5.0, the auto-updater feature still warns about an available update, which is the same version.
http://i.imgur.com/PwnMkuq.png

## Info:
/plot version -> [P2] >> PlotSquared (Version: 3.5.0)
/version -> git-Spigot-d276ab1-d219213 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
/pl -> Plugins (36): EmptyWorldGenerator, Skript, TitleMotd, OpenInv, iConomy_Recreation, ClearLag, sTablist, IronElevators, ProtocolLib, SkinsRestorer, FastAsyncWorldEdit, iDisguise, HeadDrops, PermissionsEx, MOTDColor, Vault, WorldEdit, FastLogin, Essentials, Rankup, **>> PlotSquared <<**, Multiverse-Core, WorldGuard, WGCustomFlags, MineResetLite, Multiverse-Portals, EssentialsSpawn, PixelVip, ChestShop, MineResetLitePlus, WGBlockRestricter, AuthMe, WGSpawnPointFlag, WGKeepInventoryFlags, HolographicDisplays, WGFlyFlag.

**How to replicate:** 

Probably just installing version 3.5.0 (I've downloaded it from GitHub)
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by bertek41** [comment] 2017-05-01 15:59
Same problem please fix it

**Comment by LazoYoung** [comment] 2017-05-21 05:04
I can confirm this report is true. It should be fixed sooner.

**Comment by RezzedUp** [comment] 2017-06-14 03:57
Same problem here. I get an update notification every single time I join my server, even though I'm running the latest version available.

![](http://i.imgur.com/t8zTLcI.png)

**Comment by dordsor21** [comment] 2017-06-17 11:08
#1466 dupe

**Closed by dordsor21** 2017-06-17 11:08 UTC
