### ISSUE TITLE
SpawnReason Beehive being affected by natural_mob_spawning

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#3043] opened 2021-05-19 19:56 UTC
### Server Implementation

Paper

### Server Version

1.15.2

### Describe the bug

**Copy of https://issues.intellectualsites.com/issue/PS-44 by MeFisto94**

As per https://github.com/IntellectualSites/PlotSquared/blob/6259287dffe03e6b0ccd29a2a485aa07aa8b71e6/Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEvents.java#L2078, the SpawnReason BEEHIVE is treated like all the other natural spawns. This however means that when someone has a bee nest/hive and spawns bees with eggs or spawners (i.e. manually not naturally), then they will "vanish" in the hive, as they despawn but the respective spawn event will be cancelled.

Since natural_mob_spawning is no flag under the users control afaict, there is nothing they can do about it. Also if someone wants bees, that doesn't imply they want mobs and animals to appear, anyway.

The only downside I could imagine here is that if someone uses beehives for the sole purpose of decorative building, they'd have bee spawns.

### To Reproduce

- Have a plot with bee hives/nests
- Spawn a bee
- Watch it enter the hive/nest
- Never see it again.

### Expected behaviour

- 

### Plot Debugpaste

- 

### PlotSquared Version

5.12.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by RedstoneFuture** [comment] 2021-05-19 19:57
![grafik](https://user-images.githubusercontent.com/4140635/118876082-1f7d5700-b8ed-11eb-8380-0179dccbb5ca.png)

**Comment by Xaver106** [comment] 2021-05-19 20:23
Still an issue with PS Version 5.13.11

**Comment by NotMyFault** [comment] 2021-05-22 15:05
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3033

**Closed by NotMyFault** 2021-05-22 15:05 UTC
Labels: Requires Testing
