### ISSUE TITLE
Plot condense moving plots away from 0,0 & DB error

### ISSUE THREAD

**Issue by Minetown** [IntellectualSites/PlotSquared#2439] opened 2019-07-23 00:47 UTC
**[REQUIRED] PlotSquared Version Number: PlotSquared (Version: PlotSquared-4.298)

**[REQUIRED] Spigot/Paper Version Number: git-Paper-600 

**[REQUIRED] Minecraft Version Number: 1.13.2

**Links to worlds.yml file and settings.yml file:** 
https://athion.net/ISPaster/paste/view/46d8dd0129d640368fd30d01edddb03c

**[REQUIRED] Description of the problem: When running "/plot condense worldname start 8" plots are seemingly moved to the same location according to the console output (example: 
[17:36:42 INFO]: [P2] Moving: plots;8;2 -> plots;8;2) however plots are either deleted or moved away from 0,0 and condensed in a different area of the world. Selection seems to be random, as some plots stay near 0,0. There is also a database error (Visible in debugpaste). 

**Any relevant console output or screenshots: Visible in debugpaste

**Plugins being used on the server:**
AsyncWorldEdit, LuckPerms, Multiverse-Core*, Multiverse-Portals*, PlotSquared, ProtocolLib*, ProtocolSupport, Vault*, ViaVersion*, WorldEdit, WorldGuard

**How to replicate:** 
Start server with existing world using MariaDB, run "/plot condense worldname start 8"

Closed/similar duplicates are for 1.8. 
https://github.com/IntellectualSites/PlotSquared/issues/2252
https://github.com/IntellectualSites/PlotSquared/issues/2273

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Minetown** [comment] 2019-07-23 01:00
Example: Claiming a 4x4 grid of plots centered on 0,0 (-1;-1 to 2;2) this is the spread of plots after the failed condense operation. -1;-7, 6;3, -2;-7, -7;-3, -1;2, -1;1, -1;0, 6;1, 0;-1, 1;-1, 2;-1, -7;-4, -6;7, 6;2, 6;4, -4;7

**Comment by MattBDev** [comment] 2019-07-23 05:27
Regardless if the issue is tagged as 1.8 a new issue isn't required for this.

**Comment by MattBDev** [comment] 2019-07-23 05:27
Duplicate of #2273

**Closed by MattBDev** 2019-07-23 05:27 UTC
