### ISSUE TITLE
InvenroyCloseEvent

### ISSUE THREAD

**Issue by darkdragonxxxx** [IntellectualSites/PlotSquared#1031] opened 2016-04-03 04:45 UTC
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
I can't do /debug because I can't do any commands.

**Description of the problem:**
http://pastebin.com/QYrLq1gV
So when ever I do /plot it says that in console and this in chat:
"An Internal error occurred while attempting to perform this command"
**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by darkdragonxxxx** [comment] 2016-04-03 04:50
Works fine on my other server so I'm not sure what's happening.

**Comment by boy0001** [comment] 2016-04-03 05:38
duplicate of #1029

**Closed by boy0001** 2016-04-03 05:38 UTC
