### ISSUE TITLE
plot schematic issue

### ISSUE THREAD

**Issue by titustitus98** [IntellectualSites/PlotSquared#2396] opened 2019-06-13 18:10 UTC
**[REQUIRED] PlotSquared Version Number:** 
PlotSquared-4.286

**[REQUIRED] Spigot/Paper Version Number:** 
CraftBukkit version git-spigot-01d0f04-b7fea42
**[REQUIRED] Minecraft Version Number:** 
1.14.2
**Links to worlds.yml file and settings.yml file:** 
Settings.yml: https://pastebin.com/jkZpfY2X worlds.yml: https://pastebin.com/HL4pHh90

**[REQUIRED] Description of the problem:** 
When I do /plot auto in a world where I have predefined a schematic it says "Unable to load schematic" and please do not say that it's because the plugin does not support 1.14.2 because it is not true as plotsquared works fine on my server.
**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**How to replicate:** 

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-06-13 19:19
Old build of PlotSquared.  There have been 4 successful builds since 286, at least 2 of which affect this area. Please update and test again. https://ci.athion.net/view/Everything/job/PlotSquared-Breaking/

Additionally, we need to know what other plugins you're using. Are you using WorldEdit or FAWE? Which versions/builds if you are?

Note: 1.14 support is being worked on, slowly, in the time the devs have.  Not all features and functions will work correctly on 1.14. To be frank, the fact you're able to use P2 at all on 1.14.2 is amazing. 

Also Note: CraftBukkit version git-Spigot-df0eb25-4090d01 (MC: 1.14.2) is a build less than 5 minutes old as of me writing this, thus you should build a new 1.14.2 and update the server before testing.

**Comment by titustitus98** [comment] 2019-06-14 10:10
Ok, but is the way I wrote the schematic i down in the worlds.yml file correct?

**Comment by AeSix** [comment] 2019-06-14 13:38
It is best to use the in-game commands to create the road schematic. Follow the process on the [wiki](https://github.com/IntellectualSites/PlotSquared/wiki) for creating and using road schematics. 

If the process fails, update the ticket.  Someone else will test and provided it fails for them as well, with the new builds of P2, the ticket will be marked as a bug, so the devs know to look into fixing it.

**Comment by titustitus98** [comment] 2019-06-14 14:06
No I wasn't talking about the road schematic but of the plot schematic.

**Comment by dordsor21** [comment] 2019-06-24 11:58
What version of Minecraft was the schematic made in?

**Comment by AeSix** [comment] 2019-08-10 16:41
Closing as a duplicate of #2349 (older issue, should contain all info)

**Closed by AeSix** 2019-08-10 16:41 UTC
Labels: 1.14.x, [?] Testing Required, in progress
