### ISSUE TITLE
ArrayOutOfBoundsError with plotworld creation

### ISSUE THREAD

**Issue by rhystedstone** [IntellectualSites/PlotSquared#2741] opened 2020-04-03 22:32 UTC
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [X] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paste the output here, between the tick marks, replacing this text
```03.04 22:25:13 [Server] INFO This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
03.04 22:25:13 [Server] INFO Previous version: git-Paper-624 (MC: 1.13.2)
03.04 22:25:13 [Server] INFO You are running the latest version
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 7.1.0;8e55131

### Description of the problem:

We created a second plot world with /plot setup, but, removed it from the config and multiverse and the file system when we made a mistake. When re-added, /p claim causes the Array Out Of Bounds Error (1). This only occurs when a plot is not claimed.

### How to replicate:

/p setup - Setup a world
/mv remove - Remove the world after setup
- Removed from worlds.yml
/p reload
/p setup - Again: After this, we noticed the world was generated identically
/mv remove
- Removed from worlds.yml again
- Restarted server
/p setup - setup a world
/p v 0;0 - Went to plot 0;0
/p claim - Did nothing
/p debug msg - one message
Console received error

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
When using PlugMan, /plugman reload PlotSquared often crashed the server.
Both plot worlds no longer work for claiming new plots

### Relevant console output, log lines, and/or screenshots:

```
 03.04 22:30:10 [Server] INFO _R_T_ issued server command: /p claim
03.04 22:30:17 [Server] INFO _R_T_ issued server command: /p debug msg
03.04 22:30:17 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 1
03.04 22:30:17 [Server] WARN at com.github.intellectualsites.plotsquared.plot.commands.Debug.onCommand(Debug.java:17)
03.04 22:30:17 [Server] WARN at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.execute(SubCommand.java:36)
03.04 22:30:17 [Server] WARN at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:343)
03.04 22:30:17 [Server] WARN at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:258)
03.04 22:30:17 [Server] WARN at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:141)
03.04 22:30:17 [Server] WARN at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:31)
03.04 22:30:17 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
03.04 22:30:17 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
03.04 22:30:17 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1804)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1612)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088)
03.04 22:30:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
03.04 22:30:17 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

Edit 1: Moved log to correct place
Edit 2: Added additional information

**Comment by MattBDev** [comment] 2020-04-03 23:25
You didn't read everything and checked everything above anyways. We need a `/plot debugpaste`. It is not optional. I will close this issue if none is provided.

**Comment by rhystedstone** [comment] 2020-04-03 23:27
https://athion.net/ISPaster/paste/view/e7f575c326b5488899984440fbcac7f7
From /plot debugpaste

**Comment by MattBDev** [comment] 2020-04-03 23:27
Also, if you are using PlugMan to reload plugins/server (I assume you were despite the poor template formatting) then PlotSquared is going to have issues because it is a world generator.

**Comment by Sauilitired** [comment] 2020-05-15 07:06
When removing a plot world, it needs to be removed both via PlotSquared's worlds.yml, and and from any world management plugin you're using. Furthermore, `/plot claim` did not cause the AIOOB-exception. As no debug paste was provided, we can't really see what went wrong initially either, but this is most likely just caused by not removing the world properly.

**Closed by Sauilitired** 2020-05-15 07:06 UTC
Labels: [?] Testing Required
