### ISSUE TITLE
Crash - java.lang.IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#1345] opened 2016-09-09 03:34 UTC
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/melotoniyi

**Description of the problem:**
Server would crash with:
```
[05:25:22] [Server thread/WARN]: java.lang.IllegalArgumentException: argument type mismatch
[05:25:22] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:25:22] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:25:22] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:25:22] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:25:22] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.QueueProvider$1.getNewQueue(QueueProvider.java:15)
[05:25:22] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue.getNewQueue(GlobalBlockQueue.java:69)
[05:25:22] [Server thread/WARN]: 	at com.plotsquared.bukkit.generator.BukkitPlotGenerator$1.populate(BukkitPlotGenerator.java:60)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:306)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Chunk.loadNearby(Chunk.java:1096)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:77)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:794)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[05:25:22] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[05:25:22] [Server thread/WARN]: java.lang.NullPointerException
[05:25:22] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.QueueProvider$1.getNewQueue(QueueProvider.java:22)
[05:25:22] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue.getNewQueue(GlobalBlockQueue.java:69)
[05:25:22] [Server thread/WARN]: 	at com.plotsquared.bukkit.generator.BukkitPlotGenerator$1.populate(BukkitPlotGenerator.java:60)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:306)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Chunk.loadNearby(Chunk.java:1096)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:77)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[05:25:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:794)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[05:25:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[05:25:22] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[05:25:22] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at com.plotsquared.bukkit.generator.BukkitPlotGenerator$1.populate(BukkitPlotGenerator.java:96) ~[?:?]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:306) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.Chunk.loadNearby(Chunk.java:1096) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:77) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:794) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**How to replicate**:
Not sure, it happened soon after startup (after updating P^2)

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment] 2016-09-09 04:13
FAWE issue, duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/286

Try updating FAWE.

**Closed by boy0001** 2016-09-09 04:13 UTC
