### ISSUE TITLE
[V6] [1.17] Some sort of schematics crash the server (Exception generating new chunk)

### ISSUE THREAD

**Issue by draand28** [IntellectualSites/PlotSquared#3104] opened 2021-06-22 00:21 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I tried upgrading my Creative 1.16.5 Paper server to Paper 1.17. Noticed that PS4.5 doesn't work anymore with 1.17 so I decided to upgrade to V6. The problem is that V6 seems to have some issue with my schematic, I'm always getting the same error while generating new chunks (see logs). 
My road schematic is pretty complex in my opinion. I have tried the following things:
- clear the schematic folder in PS6 plugin folder then do a */p createroadscheamatic* but that crashes the server with the same error
- clear the database and user cache
- make a new server with a fresh world, fresh configs, added my road width and plot size in world config (I left all the other configs alone, default), then I imported the old plotworld via Multiverse core, used AWE (Async world edit) to copy/paste 16 center plots (the spawn + a few plots around it that some players have), after that I tried to */p createroadschematic* but it crashed again (see logs).

### To Reproduce

Try to upgrade a plotworld with a custom schematic from 4.5 to 6 and from 1.16.5 to 1.17. It will crash every time a chunk needs generating via the Plotsquare generator. (other world without PlotSquared are not affected and no errors come up in the console)

### Expected behaviour

Be able to upgrade without any issues or at least be able to use my schematic on a fresh world with a fresh config.

### Screenshots / Videos

This is an image of my schematic design.
![image](https://user-images.githubusercontent.com/6523336/122843511-4a9e0080-d308-11eb-9d00-68b2cef88ae3.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/7a208708ba1647d89c5b824f5258e60a

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/45c9a52546e84190bec81eddb2f54735

### PlotSquared Version

6.0.1-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I use java 16 with git-Paper-"bc4b23e" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
I use the standard SQlite type of db (not mysql).
I have reproduced this bug all night (last 4-5 hours), I really wish I wouldn't be able to reproduce it...

**Comment by NotMyFault** [comment] 2021-06-22 00:34
Did you follow the migration guide for going from v4 to v6? A direct jump is not supported and may lead to issues down the line. See [this guide](https://github.com/IntellectualSites/PlotSquared-Documentation/wiki/Migrating-from-an-older-major-release#migrating-from-plotsquared-v4).
Please attach the schematic and update Paper, you are on one of the early test builds and more than 20 updates behind.

**Comment by draand28** [comment] 2021-06-22 16:06
I did try to migrate as in the guide, I made sure I was using latest V4, then upgraded to V5.13.13. Everything worked well (On Paper 1.16.5 and Java 11).
Then I tried upgrading to V6 while using Paper 1.16.5, but it does not work with Java 11 so I decided use the real latest build of Paper 1.17 (build 34) and Java 16.  It gave me the exact same error when trying to move into an ungenerated chunk.
I inserted my schematic below.
[plotworld.zip](https://github.com/IntellectualSites/PlotSquared/files/6695830/plotworld.zip)

**Comment by NotMyFault** [comment] 2021-06-22 16:28
I can reproduce that by using `/plot crs`, on Paper.
Exception: https://paste.gg/p/anonymous/e01ec741290b46e2b0242ef6373824df
Crash log: https://paste.gg/p/anonymous/38ead0f6125247d9b1e28b05e78f391d
I was not able to reproduce this on Spigot, likely down to some paper patch?

**Comment by SirYwell** [comment] 2021-06-22 17:10
Was fixed in Spigot by <https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/887bc05190637cc5fe5783c0cd353e4eb880a7f5#src/main/java/org/bukkit/craftbukkit/generator/CustomChunkGenerator.java>, seems to be missing in Paper for now

**Comment by NotMyFault** [comment] 2021-06-22 17:40
Fixed in https://github.com/PaperMC/Paper/commit/d4cb833565b2157eb0d8ea67ace2021e7b749451 Paper build 35, update Paper.

**Closed by NotMyFault** 2021-06-22 17:40 UTC
Labels: Approved, Bug, Server Software, Under Investigation
