### ISSUE TITLE
Server-Plot flag does not remove the owner from the database

### ISSUE THREAD

**Issue by dirtyequi** [IntellectualSites/PlotSquared#2508] opened 2019-09-17 19:44 UTC
As said in the description / steps to reproduce:

- Set a plot limit for a specific user/permission group
- Let a user claim this amount of plots (and - to speed things up - merge them to a single plot <- by the way, shouldn't merged plots count as one?)
- Set the server-plot flag
- Try to claim another plot

Since the plot still has set the original owner in the database, the user cannot claim another plot. A fix could be to remove the owner information from that plot in the database. A user/permission group with a separate server-type-plot permission should still be able to do all kind of settings to a server-type plot (or use any existing/apropriate permission).

**Comment by AeSix** [comment] 2019-09-17 20:17
Closing.  Not all required information has been provided. Will be re-opened once the information from the template is provided.

**Closed by AeSix** 2019-09-17 20:17 UTC

**Comment by MattBDev** [comment] 2019-09-17 20:33
I need to revisit the issue of sever plots anyways. The flag is stupid

**Comment by Sauilitired** [comment] 2019-09-17 20:40
@MattBDev This is intended behaviour. The server-plot flag is not the same as setting the plot owner to the server. This behaviour should remain. It's not "stupid", as it was added for a purpose and it fulfils that purpose.

**Comment by dirtyequi** [comment] 2019-09-17 21:41
At least the message that no plot can be found for that search query if that mentioned user tries to find its plots (/plot find mine) needs to be improved. Even the /plot tp and /plot home commands need to be fixed in the same way, because indeed there are plots that the user owns (according to the database) - they are just not assumed to be owned by the player because they have the server-plot flag.

Please consider reopening this ticket as I clearly showed that there is room for misunderstandings (at least in the error messages) in the search function and per-player plot-amount calculations.
