### ISSUE TITLE
Road gets placed one block further down than it should 

### ISSUE THREAD

**Issue by EscolarProgramming** [IntellectualSites/PlotSquared#3362] opened 2021-12-10 17:01 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I've already reported the bug in #3346 but it was closed with a wrong solution and I don't get an answer anymore.

After updating from PlotSquared 6.1.3 to 6.1.4, the road gets placed one block futher down than it should, when an interaction with the road happens (e.g. plot unmerge). Even "/debug roadregen" doesn't help. We haven't changed the road schematic. After downgrading back to 6.1.3, it works as it should.

You told us, that the polt and road height is different from the wall height. But why does than the exact same configuration work with 6.1.3, but not with 6.1.4, and works after downgrading again with 6.1.3? **_The exact same datas_**. This must be an issue with 6.1.4.

### To Reproduce

1. Create a merge
2. Unlink or delete it
3. There you go

### Expected behaviour

The road should be generated on the same level than the other ones

### Screenshots / Videos

https://user-images.githubusercontent.com/6965961/143273493-a411656c-ce27-4795-bda2-c852ed93e807.jpeg

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f6be46aaab1446f6a8392add90ff8924

### PlotSquared Version

6.1.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-12-12 10:43
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3346

**Closed by NotMyFault** 2021-12-12 10:43 UTC
Labels: Duplicate
