### ISSUE TITLE
Error spam caused by NPE

### ISSUE THREAD

**Issue by ChimpGamer** [IntellectualSites/PlotSquared#3688] opened 2022-06-17 23:33 UTC
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

This error is spamming the whole console.
`[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]: java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.world.block.BlockState.equals(Object)" because "now" is null
[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]:     at PlotSquared-Bukkit-6.9.1-SNAPSHOT-b766.jar//com.plotsquared.core.generator.HybridUtils.lambda$analyzeRegion$2(HybridUtils.java:239)
[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]:     at PlotSquared-Bukkit-6.9.1-SNAPSHOT-b766.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39)
[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]:     at PlotSquared-Bukkit-6.9.1-SNAPSHOT-b766.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44)
[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]:     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]:     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]:     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:47:51] [Craft Scheduler Thread - 12 - PlotSquared/WARN]:     at java.base/java.lang.Thread.run(Thread.java:833)`

According to https://github.com/IntellectualSites/PlotSquared/blob/v6/Core/src/main/java/com/plotsquared/core/generator/HybridUtils.java#L238 it should not be null.

### To Reproduce

I'm not sure how to reproduce this. It happend after I updated PlotSquared from 6.7.1 to 6.9.1 build 766.

### Expected behaviour

Obviously this error should be fixed

### Error log (if applicable)

https://pastebin.com/QfhkBnGV

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8228d00829644304ae595a4c0d5b74e2

### PlotSquared Version

6.9.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment] 2022-06-17 23:36
Duplicate of #3683 that has been fixed in FAWE.

**Closed by dordsor21** 2022-06-17 23:36 UTC
Labels: Requires Testing
