### ISSUE TITLE
Mob Spawner not Spawning Monsters

### ISSUE THREAD

**Issue by Drynael** [IntellectualSites/PlotSquared#2479] opened 2019-08-22 13:10 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** 
https://athion.net/ISPaster/paste/view/d477b1e4a5c84267a43a70e605215f38

**[REQUIRED] Spigot/Paper Version Number:** 
[15:04:56 INFO]: This server is running Paper version git-Paper-163 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.14.4

**[REQUIRED] Description of the problem:** 
Mobspawner are not Spawning Enemy Mobs

**Any relevant console output or screenshots:**
No

**Plugins being used on the server:**

Bank, ColoredAnvils*, Core, CoreProtect, CrazyCrates, CustomEnderChest, dynmap*, EasyBackup*, EasyBackupCore*, EZColors, GlobalMarketChest, HeadDatabase*, Horizon, Multiverse-Core, MythicDrops, OreRandomizer*, PetBlocks*, PlaceholderAPI*, Plan, PlayerParticles, PlotSquared, ProtocolLib, ScoreBoard*, Shopkeepers, StackMob, TAB, UltimateStacker, UltraPermissions, UltraPunishments, Vault, VentureChat, Votifier, VotingPlugin, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**How to replicate:** 

Place Spawner
Use Egg
No Spawning

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
Disabled CMI that intercats with Spawner

**Comment by MattBDev** [comment] 2019-08-22 14:21
What do you mean "use egg"?  It's a mob spawner.

**Comment by AeSix** [comment] 2019-08-22 17:11
r8ght click a spawner with a mob egg and the spawner is set to that mob type.... normally

**Comment by AeSix** [comment] 2019-08-22 22:28
UltraPermissions has already been proven to cause issues with PlotSquared.

Please confirm this issue does or does not exist when using only plotsquared on a 1.14.4 server. 
Please update to the newest build from the break branch, 4.318 is rather old. 
Please update to the newest build of Paper 1.14.4, as build 167 is rather old. 

If you can confirm that this issue still exists with new builds of P2, Paper, and with no other plugins installed, that would be great.

**Comment by AeSix** [comment] 2019-08-29 13:33
Closing due to issue most likely being caused by other plugins. 
@Drynael if you perform the test as prescribed above and the issues persists, we'll re-open this ticket.

**Closed by AeSix** 2019-08-29 13:33 UTC
Labels: 1.14.x, Spigot, [?] Testing Required
