### ISSUE TITLE
Unable to use /plot visit ?

### ISSUE THREAD

**Issue by mrfloris** [IntellectualSites/PlotSquared#3190] opened 2021-07-30 00:13 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

after the last update from plotsquared v6 to 6.0.7-Premium players can't type: /plot visit theirname 1, etc. we can't find any plot, i have to manually move players around now. 

### To Reproduce

go to the world
type /plot visit mrfloris 1 (or whatever)
and it will say it can't find the plot

### Expected behaviour

teleport to the plot

### Plot Debugpaste

[removed for obvious reasons]

### PlotSquared Version

6.0.7-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

```
[02:12:34 INFO]: Fr33_S0uL issued server command: /plot visit Fr33_S0uL 1
>
```
no console msgs 

and the player sees `Found No plots with your search query`

**Comment by SirYwell** [comment] 2021-07-30 17:52
I cannot reproduce this issue. Could you try with a clean setup (especially WorldEdit instead of AsyncWorldEdit)?

**Comment by mrfloris** [comment] 2021-07-30 18:06
> I cannot reproduce this issue. Could you try with a clean setup (especially WorldEdit instead of AsyncWorldEdit)?

Eh yeah i can do that saturday evening or sunday morning.

**Comment by mrfloris** [comment] 2021-08-01 10:42
> I cannot reproduce this issue. Could you try with a clean setup (especially WorldEdit instead of AsyncWorldEdit)?

Without asyncworldedit it works again. Thank you for this tip.

**Comment by mrfloris** [comment] 2021-08-02 15:22
I don't know who has to update, asyncworldedit or plotsquared, but if the plugins could play nice together than it would be fantastic, I will leave it to you two plugins to figure out what's the logical step to take;

https://www.spigotmc.org/threads/asyncworldedit-premium-paid.79081/page-136#post-4232217

**Comment by SirYwell** [comment] 2021-08-02 15:37
If it works with WE (7.2.x), AWE needs to update I guess

**Comment by TNTUP** [comment] 2021-08-05 08:48
Is the plot merged?

**Closed** 2021-09-12 19:57 UTC
Labels: [✖] Cannot Replicate, Requires Testing
