### ISSUE TITLE
Unknown plot owners

### ISSUE THREAD

**Issue by Dakado** [IntellectualSites/PlotSquared#1150] opened 2016-06-02 15:24 UTC
Please fix/add feature that if the plot Owner is "Unknown" the plot can by claimed by everybody, many of my plots are freezed just because if this bug.

You could make it configurable if you want to enable Unknown plot claims or not.

**Comment by manuelgu** [comment] 2016-06-02 15:28
Duplicate of #781

**Closed** 2016-06-02 15:36 UTC
