### ISSUE TITLE
Merging / Deleting Plots isn't working

### ISSUE THREAD

**Issue by Peda1996** [IntellectualSites/PlotSquared#2415] opened 2019-07-04 09:14 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
PlotSquared (Version: PlotSquared-4.298)

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-122 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.14.3

**Links to worlds.yml file and settings.yml file:** 

Settings: https://pastebin.com/paede7dZ
Worlds: https://pastebin.com/yX82SmVi

**[REQUIRED] Description of the problem:** 
Deleting, merging and all commands regarding world editing (done from plotsquared) lead to the following error. Therefore the world isn't changed.
After trying to use for example the /plot delete command again, the message: A setblock timer is bound to either the current plot or you. Please wait for it to finish appears.

Any idea what this problem causes?

**Any relevant console output or screenshots:**
```
[PlotSquared] Task #1033 for PlotSquared v4.298 generated an exception
java.lang.NullPointerException: null
	at com.github.intellectualsites.plotsquared.plot.object.LegacyPlotBlock.getBaseBlock(LegacyPlotBlock.java:37) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.block.BasicLocalBlockQueue.setBlock(BasicLocalBlockQueue.java:124) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.block.LocalBlockQueue.setCuboid(LocalBlockQueue.java:109) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:193) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:180) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.ChunkManager$3.run(ChunkManager.java:191) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-122]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[10:21:22 INFO]: Peda1996 issued server command: /p delete

```
**Plugins being used on the server:**

Worldedit: 7.0.0;214af8a

**How to replicate:** 

Install the newest plotsquared version, and then use the /plot delete on a claimed plot.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-07-04 11:52
is this replicable with FAWE?

also, for future, please use \`\`\` blocks \`\`\` for log text.

**Comment by Resi23** [comment] 2019-07-04 14:53
I have the same Problem with git-Paper-123 and PS 4.299 Claim and set border/wall works perfectly. At the "/p merge auto" the road stays behind. For "/p merge" he says "You do not own any adjacent plots." With the commands "/p clear" or "/p delete" I get an error in the console. 

`[15:41:40] [Server thread/WARN]: [PlotSquared] Task #962 for PlotSquared v4.299 generated an exception
java.lang.NullPointerException: null
	at com.github.intellectualsites.plotsquared.plot.object.StringPlotBlock.getBaseBlock(StringPlotBlock.java:85) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.block.BasicLocalBlockQueue.setBlock(BasicLocalBlockQueue.java:124) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.block.LocalBlockQueue.setCuboid(LocalBlockQueue.java:125) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:197) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:180) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.ChunkManager$3.run(ChunkManager.java:191) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-120]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-120]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-120]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-120]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-120]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-120]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

**Comment by Peda1996** [comment] 2019-07-04 18:42
I don't use FAWE, as 1.14 isn't supporting this

**Comment by Peda1996** [comment] 2019-07-20 07:13
> 
> 
> is this replicable with FAWE?
> 
> also, for future, please use ``` blocks ``` for log text.

Somehow I read over this comment. Sorry I edited my initial issue.

**Comment by AeSix** [comment] 2019-07-30 11:45
Is this resolved when using up to date versions of the applicable software?
Using PlotSquared Breaking releases?

**Comment by AeSix** [comment] 2019-07-30 12:06
Ultimately a duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2375
Closing.

**Closed by AeSix** 2019-07-30 12:06 UTC
Labels: 1.14.x, [‼] high priority, [✔] Verified

**Comment by Resi23** [comment] 2019-08-02 10:18
With me nothing is fixed and I use of all the latest version
Worldedit: 7.0.1-SNAPSHOT;4579
PlotSquared-4.306

I try delete a plot and become this error 

[12:15:06] [Server thread/INFO]: Resi issued server command: /p del
[12:15:06] [Server thread/WARN]: [PlotSquared] Task #1157 for PlotSquared v4.306 generated an exception
java.lang.NullPointerException: null
	at com.github.intellectualsites.plotsquared.plot.object.StringPlotBlock.getBaseBlock(StringPlotBlock.java:85) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.block.BasicLocalBlockQueue.setBlock(BasicLocalBlockQueue.java:124) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.block.LocalBlockQueue.setCuboid(LocalBlockQueue.java:125) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:197) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:180) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.ChunkManager$3.run(ChunkManager.java:191) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-154]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-154]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-154]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-154]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-154]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-154]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
