### ISSUE TITLE
/p unlink current

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3437] opened 2022-01-07 15:56 UTC
### What feature do you want to see added?

A command to only unlink the current plot from merge. So if i merge a plot, i can remove only the one iam currently standing in, without destroying the whole merge.

### Are there any alternatives?

Nope

**Comment by dordsor21** [comment] 2022-06-13 18:27
Duplicate of #2973

**Closed by dordsor21** 2022-06-13 18:27 UTC
Labels: Enhancement
