### ISSUE TITLE
Plot visit and home index is not the same

### ISSUE THREAD

**Issue by nicolube** [IntellectualSites/PlotSquared#4136] opened 2023-08-04 12:06 UTC
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

If u do `/p h 5` u land on `/p v <username> 4` plot,

### To Reproduce

Claim a few plots and use `/p v <username>` 3 and `/p h 3`, U will not be teleported to the same plot

### Expected behaviour

 `/p v <username> 3` and `/p h 3` Teleportet to the same plot

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/2215d86df66f46d48a0d3c74ae4598bb

### PlotSquared Version

PlotSquared-7.0.0-rc.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Also verfied on another server on rc-4

**Comment by nicolube** [comment] 2023-08-04 12:10
Ok that is in of wierd, I have 2nd CB that is basicly the same and there it works flawlessly

**Comment by OneLiteFeather** [comment] 2023-08-04 16:23
This is not how both command work, please read the documentation :)
/p v means plot visit <player/alias> and /p h means your plot home and behind the number of your plot where you want to teleport. An alias can only be set once each server and always teleports to one spot for everyone.

**Comment by dordsor21** [comment] 2023-08-04 16:30
The index really should be the same, else you cannot say "go to my 3rd plot"

**Comment by OneLiteFeather** [comment] 2023-08-04 16:42
![grafik](https://github.com/IntellectualSites/PlotSquared/assets/77929075/21b03a0f-935b-4835-b8da-3554cfb26694)
If so, why was this never a thing in Plotsquared 6.11.1 ?

> The index really should be the same, else you cannot say "go to my 3rd plot"

Actually you can, but only with /plot home 3 but never with /plot visit 3 because it can only be a player (and fortunately setting an alias with 3 doesn't work as it must be alphanummerical)
There must be something else broken that allows the command /p v 3 to work

**Comment by dordsor21** [comment] 2023-08-04 16:49
they were using visit correctly. The issue is your /plot home 3 is different to /plot visit <user> 3

**Comment by OneLiteFeather** [comment] 2023-08-04 17:13
https://intellectualsites.gitbook.io/plotsquared/commands#teleport
You can't use /p v 3 because you always have to add a player. How would Plotsquared know where to go if you don't tell the owner of the plot.
So if you need to go to a different players plot, use /p v <player> <number> and if you want to go to your plot /p h <number>

**Comment by dordsor21** [comment] 2023-08-04 17:49
Looks like it was edited lol
<img width="419" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/10080017/7d68b0f4-958b-4f93-8d13-24748e82a680">

**Comment by OneLiteFeather** [comment] 2023-08-04 18:18
I guess it could also be a merged plot @dordsor21 so all plots that are merged into one share the same home. But I am really not sure what is the issue behind this issue.

**Comment by OneLiteFeather** [comment] 2023-08-13 21:31
@nicolube can you explain more in detail what you mean? It looks like it's not an issue but a missunderstanding.

**Comment by nicolube** [comment] 2023-08-14 06:43
> @nicolube can you explain more in detail what you mean? It looks like it's not an issue but a missunderstanding.

Well this is about that `/p h 6` and `/p v <username> 5` the same plot for me is.
But I think it should be `/p h 6` and `/p v <username> 6`

**Comment by nicolube** [comment] 2023-08-14 06:47
> This is not how both command work, please read the documentation :) /p v means plot visit <player/alias> and /p h means your plot home and behind the number of your plot where you want to teleport. An alias can only be set once each server and always teleports to one spot for everyone.

It semms that Mardown removed `<>` tags, i added some code blocks to clarify that.

**Comment by nicolube** [comment] 2023-08-14 06:49
> Looks like it was edited lol @nicolube please clarify <img alt="image" width="419" src="https://user-images.githubusercontent.com/10080017/258494308-7d68b0f4-958b-4f93-8d13-24748e82a680.png">

**Comment by OneLiteFeather** [comment] 2023-08-14 10:34
Ah now I know what you mean, that is an issue for a long time. The plots with their index swap sometimes so they get out of the order they were claimed. You mean this @nicolube ?

**Comment by nicolube** [comment] 2023-08-14 16:16
@OneLiteFeather Yes

**Comment by nicolube** [comment] 2023-08-14 16:19
But they they are offset by one in this case between home and visit. When I'm on plot home 5 and ask someone to come by they land on and diffrent plot with plot visit.


I basikly need to search for my plot id with plot visit to share it

**Comment by OneLiteFeather** [comment] 2023-08-16 18:08
Not sure if there is a duplicate because I've known this issue for quite a while (2 years) also in PS5 I guess, but changing or adding plot owners can reproduce this behaviour, so I guess this can be confirmed till we find a duplicate

**Comment by RedstoneFuture** [comment] 2023-10-09 23:21
If I have 2 merged plots, the commands `/p home <1 & 2>` and `/p v RedstoneFuture <1 & 2>` are available for me. Of course, merged always counts as one plot. But with that, **I can't replicate the bug report.** HOME and VISIT numbers are always the same for the same plot.

`/p home 4` corresponds `/p v RedstoneFuture 4` for me and also for other players. No problems after a swap or setowner command. The order of the IDs for the plots is also correct.

Can you please test it on a clean test server with less plugins?

![grafik](https://github.com/IntellectualSites/PlotSquared/assets/4140635/ac19a62d-76db-4d95-a1a9-7039ed07e499)

**Comment by nicolube** [comment] 2023-10-09 23:30
Could it be this issue be caused from enabeling the Server Plot flag?

I can still teleport to a plot with /p h that has that flag enabled.

**Comment by nicolube** [comment] 2023-10-09 23:32
I owned about 15 Plots, 14 Single Plots and one 3x3 Merge.

The 3x3 Merge was a server plot.

**Comment by RedstoneFuture** [comment] 2023-10-09 23:45
Ah, okay, yes. That's intentional: With the server plot flag, you don't want other players to see that this is your plot. So any plot result shifts. But since it's your plot, you need the access to get it with the original plot ID.

**Comment by nicolube** [comment] 2023-10-09 23:58
Ok, would it then not be better to remove it from /p h too?
That the plot been treated as an plot that is not owned by a player.

As an example, Towny allows u to set a "Fake" Player as an town owner for thows that are owned by the server.

**Comment by RedstoneFuture** [comment] 2023-10-10 00:04
Technically, in PlotSquared the "server-plot" is still your plot and is only hidden from the others by the plot flag!

It's not technically the same concept as Towny does.

**Comment by RedstoneFuture** [comment] 2023-10-10 00:13
An unconventional solution: ban a player with a strange username "Server" or something and set this person as the owner of your current "Server-Plots".

**Closed** 2023-10-10 13:37 UTC
Labels: Approved, Not a defect
