### ISSUE TITLE
1.11 error

### ISSUE THREAD

**Issue by Sikatsu** [IntellectualSites/PlotSquared#1433] opened 2016-11-20 12:37 UTC
**Debug paste link**: 

http://pastebin.com/yrWdYTTu
http://hastebin.com/osagowihay

**Description of the problem:**

When killing a mob, the error pops up.

**How to replicate**:

Kill a mob.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
There are duplicates, tho I followed the right lines for the report.

- [X] Made sure you're using an up-to-date version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment] 2016-11-21 00:43
duplicate of #1432 
Please do not check the box that says "Made sure there aren't any duplicates of this report" when you clearly didn't.

**Closed by MattBDev** 2016-11-21 00:43 UTC

**Comment by Sikatsu** [comment] 2016-11-21 07:26
Pardon?

I said "There are duplicates, tho I followed the right lines for the report"

My point was to make a clear report for you with the default questions when making an issue here, if you do not appreciate that, I wonder were these questions are for.
