### ISSUE TITLE
the bees do not come out of the hive

### ISSUE THREAD

**Issue by PaciorJr** [IntellectualSites/PlotSquared#3512] opened 2022-02-22 12:04 UTC
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

the bees do not produce honey, they do not come out of the hive.

### To Reproduce

1. put the beehive
2. put flowers for the bees
3. Use the bees' eggs to respawn them
4. Wait for them to fly into the Hive and nothing will happen

### Expected behaviour

I expected them to work properly

### Plot Debugpaste

I don't have it now

### PlotSquared Version
6.5.0

### Checklist

- [ ] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

the problem is from version 5 of this plugin

**Comment by dordsor21** [comment] 2022-02-22 13:37
Duplicate of #3033

**Closed by dordsor21** 2022-02-22 13:37 UTC
Labels: Requires Testing
