### ISSUE TITLE
Bypassing the Entity limit on a plot with flowing water - Video Included.

### ISSUE THREAD

**Issue by TerraPrimal** [IntellectualSites/PlotSquared#2063] opened 2018-08-14 22:22 UTC
**Debug paste link:** https://hastebin.com/maposoruze

**Description of the problem:** I had a report come in from a player advising me they could bypass the entity limit within the plot due to flowing water.
I asked them to replicate the issue and they did so with a video showing how it's done.
https://vimeo.com/283710709

Were not on the latest dev build, but I saw nothing in the change list to show that this was an issue already addressed.

Thanks for your help/time.

**How to replicate:** From the video, you make a 1x1 tunnel with following water and spawn the entities, let them from into a "common" area.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-03-17 20:02
@TerraPrimal is this still an issue with the newer builds?
There's been a lot of work since this was reported.  

If it is still an issue, give us a new /plot debugpaste please
If it's not an issue, let us know and close then ticket.  Thank you :)

**Comment by AeSix** [comment] 2019-08-10 17:13
As this has not been responded to be the original author, I could not reproduce, and 1.12 development is limited (or non-existent at this point), I'm closing this ticket. 

@TerraPrimal if this is still an issue, please ensure you're using the newest builds from the legacy branch, newest build of the server, and then update the ticket. 

Better yet would be to update to 1.13.2 and P2 4 and test as well.

**Closed by AeSix** 2019-08-10 17:13 UTC
Labels: 1.12.x
