### ISSUE TITLE
Setbiome giving unlimited timer

### ISSUE THREAD

**Issue by Azriael2** [IntellectualSites/PlotSquared#2653] opened 2020-01-04 02:59 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** 

https://athion.net/ISPaster/paste/view/abcdd87ac91444ba9646271fa7395a1d

**[REQUIRED] Spigot/Paper Version Number:** 
Version: git-Paper-209
**[REQUIRED] Minecraft Version Number:** 
(MC: 1.14.4)
**[REQUIRED] Description of the problem:** 
Command /plot setbiome is setting unlimited (?) timer on player and does not work correctly. Tried with /plot setbiome Savanna (which I heard is not correct now) and /plot setbiome minecraft:savanna (which should be correct, while it's from wall list of biomes, but it does not work), both give timer without any change to plot.

**Any relevant console output or screenshots:**
https://pastebin.com/2PEkM42J

**Plugins being used on the server:**

**How to replicate:** 

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment] 2020-01-04 04:03
Duplicate of several other issues. Fixed in breaking builds.

**Closed by MattBDev** 2020-01-04 04:03 UTC
