### ISSUE TITLE
Bee EnterBlockEvent/ChangeBlockEvent

### ISSUE THREAD

**Issue by BufferOverflw** [IntellectualSites/PlotSquared#3397] opened 2021-12-24 19:19 UTC
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Bees can not get out of their nest again even with the flag `entity-change-block` 

### To Reproduce

1. Place a Bee Nest
2. Place flowers around the Bee Nest
3. Spawn bee's with the bee egg
4. the bees have to be pollinated by the flowers and when they go into the nest they despawn

### Expected behaviour

the bee's were inside the nest

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/b340d051d280483b863cc1b6a7cbeecd

### PlotSquared Version

6.2.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-12-30 09:58
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3033

**Closed by NotMyFault** 2021-12-30 09:58 UTC
Labels: Duplicate
