### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2765] opened 2020-04-13 05:33 UTC
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2

### Server build info: 

```
Paper git-Paper-180
```

### WorldEdit/FAWE versions:

- [x] WorldEdit version: 7.2.0-SNAPSHOT+4971-8c83fd6

### Description of the problem:
```
[22:27:13] [Craft Scheduler Thread - 175/WARN]: [PlotSquared] Plugin PlotSquared v4.493 generated an exception while executing task 28951
java.lang.NullPointerException: null
	at com.github.intellectualsites.plotsquared.bukkit.object.BukkitPlayer.sendMessage(BukkitPlayer.java:192) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.MainUtil.lambda$sendMessage$3(MainUtil.java:664) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-180]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-180]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-180]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
### How to replicate:
Use PlotSquared-Breaking dev 493

Caused by https://github.com/IntellectualSites/PlotSquared/commit/9a847446fa5ec1ba38fcffbe703e35d013fed471 or https://github.com/IntellectualSites/PlotSquared/commit/18765534ce3898a8d351b105e3c56e7d0f0a6c11 or https://github.com/IntellectualSites/PlotSquared/commit/1e96ca19f8af18f704ec1a09efbcc8f998767ac8 ? Downgrading to dev 491 doesn't have the problem.

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by Sauilitired** [comment] 2020-04-15 14:58
> Caused by 9a84744 or 1876553 or 1e96ca1 ? Downgrading to dev 491 doesn't have the problem
Just want to point out that neither of those are present in the development builds, as those were in the version 5 branch 😄 

 I'll look into this though. Should be harmless, however.

**Comment by MattBDev** [comment] 2020-05-13 14:58
Can't reproduce the issue.
@Sauilitired Go ahead and close this if you agree.

**Closed** 2020-05-14 12:03 UTC
Labels: 1.15, [?] Testing Required, v4
