### ISSUE TITLE
Visual annoyance

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1452] opened 2016-11-29 09:49 UTC
A very minor issue, when you change your plots biome there is a one block line on the edge of the plot that is in some sort of halfway state with the road biome. This ends up making snow look really bad on the edges https://i.gyazo.com/9a098899ff9d500ba8009bc9c79cf970.png as well as the one block slightly different color grass

**Comment by manuelgu** [comment] 2016-11-30 04:10
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/1349

**Closed** 2016-11-30 04:10 UTC
