### ISSUE TITLE
Merge regions wont get calculated right

### ISSUE THREAD

**Issue by buepas** [IntellectualSites/PlotSquared#2445] opened 2019-07-28 16:40 UTC
**[REQUIRED] PlotSquared Version Number:** PlotSquared-19.7.13-44ad99e-776

**[REQUIRED] Spigot/Paper Version Number:** git-Spigot-db6de12-18fbb24

**[REQUIRED] Minecraft Version Number:** 1.8.9

**[REQUIRED] Description of the problem:** When getting regions of a merged plot the getRegions() method returns different output for the same merged plot, depending on what plot the connected_cache was populated from (normally the one a player interacts first with). The problem here is, that some regions for some merges are getting messed up resulting in regions ignoring roads etc. (seen in the screenshot below: One of the red circled Corners do not have corners detected because of the issue) I already made a fix by sorting the connected plots by their merge count (smallest first) and the way they are connected (the ones in a straight line first, then the corner ones) after sorting the List (the converted Set) every corner does get detected.
**Any relevant console output or screenshots:**
![image](https://user-images.githubusercontent.com/9660472/62009871-15142b00-b164-11e9-9623-5948f7c51e6b.png)

**How to replicate:** 
  0   1   2 x-axis
0 o | x | x 
1 o | x | x
2 x | x | x
3 x | x | x
y-axis

x = owned plot; o = not owned plot
By merging the bottom row first, and then upwards the corner between (0,2) and (1,2) as seen on the screenshot does not get detected. The orientation of the plot is important, I also have a codesnippet ready.

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
#2444 is the PR for this issue

**Comment by AeSix** [comment] 2019-07-30 11:59
Closing due to code having been written to resolve this issue.  If the issue is not resolved, the ticket may be re-opened.

**Closed by AeSix** 2019-07-30 11:59 UTC
Labels: 1.8.x, Spigot
