### ISSUE TITLE
slabs do not update when claiming a plot

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#667] opened 2015-10-10 01:02 UTC
block: '44:6'
      block_claimed: '44:7'

https://gyazo.com/f058fbd720d01eb904d0d786b661bcd5

plotsquared 3.2.8

**Comment by boy0001** [comment] 2015-10-10 04:57
Duplicate of #510

**Closed by boy0001** 2015-10-10 04:57 UTC
