### ISSUE TITLE
Pull blocks from the path to the pad with sticky pistons

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/PlotSquared#2442] opened 2019-07-26 16:38 UTC
**[REQUIRED] PlotSquared Version Number:**
```
26.07 18:26:16 [Server] INFO [P2] >> PlotSquared (Version: PlotSquared-4.304)
26.07 18:26:16 [Server] INFO [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
26.07 18:26:16 [Server] INFO [P2] >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki
26.07 18:26:17 [Server] INFO [P2] >> Newest Version: development-builds
```
**[REQUIRED] Spigot/Paper Version Number:** 
```
26.07 18:26:43 [Server] INFO This server is running Paper version git-Paper-639 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
26.07 18:26:43 [Server] INFO Previous version: git-Paper-637 (MC: 1.13.2)
```
**[REQUIRED] Minecraft Version Number:** 
1.13.2
**Links to worlds.yml file and settings.yml file:** 
[worlds.yml](https://hastebin.com/dalaweyegi.sql)
[settings.yml](https://hastebin.com/abolopajog.bash)

**[REQUIRED] Description of the problem:** 
A used can retrieve some block from road with sticky-piston

**Any relevant console output or screenshots:**
Piston is on claim plot
Air is on wall plot
wood is on road

![2019-07-26_18 22 28](https://user-images.githubusercontent.com/472429/61966683-8670a400-afd3-11e9-94cc-b44b3d4aa2dd.png)

![2019-07-26_18 22 37](https://user-images.githubusercontent.com/472429/61966694-8e304880-afd3-11e9-9403-ced0ad4d59d5.png)

![2019-07-26_18 22 44](https://user-images.githubusercontent.com/472429/61966699-912b3900-afd3-11e9-9f1b-8efcd1daf202.png)

![image](https://user-images.githubusercontent.com/472429/61966863-19114300-afd4-11e9-812c-291c859316b6.png)

**Plugins being used on the server:**
Plugins (22): AdvancedPortals, BestViewDistance*, BungeeTabListPlus*, CreativeNbtControl, DisableJoinMessage*, dynmap*, FastAsyncVoxelSniper, FastAsyncWorldEdit, FlySpeed*, ForceField*, LOTM-ForceGameMode*, LuckPerms, Multiverse-Core, PermBridge*, PlaceholderAPI*, PlotSquared, PremiumVanish, ProtocolLib*, SpawnJoin*, Vault, ViaVersion*, WorldEdit

**How to replicate:** 
See screenshot

This is a duplicate from #112 and #4 but it was close since 4 years

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue) 
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-07-30 11:13
Is this repeatable without ViaVersion?  And what is PermBridge, You shouldn't need a permissions bridge with LuckPerms and Vault being installed. 

Please replicate this issue with only P2, FAWE, LuckPerms and Vault, ensuring you are using the most up to date versions of each, and the server.  Update the ticket.

**Comment by jewome62** [comment] 2019-07-30 14:18
I will try this evening.

Server is 1.13.2 and testing client is 1.13.2 ViaVersion should not override current protocol.
PermBridge is a own plugin which check if the player is allowed and if not, the player is kicked
A whitelist but with permission

**Comment by jewome62** [comment] 2019-07-30 17:03
@AeSix I confirm the bug without ViaVersion on server

**Comment by AeSix** [comment] 2019-07-31 10:29
With only P2, FAWE, LuckPerms and Vault?

**Comment by jewome62** [comment] 2019-08-07 23:54
The server is empty now. so i have tested.
![image](https://user-images.githubusercontent.com/472429/62665379-52a45f80-b97f-11e9-8a79-79c1d9dc0d3f.png)
Same problem
![image](https://user-images.githubusercontent.com/472429/62665421-78316900-b97f-11e9-8e91-066b462825d6.png)

**Comment by jewome62** [comment] 2019-08-07 23:58
OK, I found the realbug.

My bug is only of the space where there was the path (before merge)
The sticky piston on regular border can't be extended

**Comment by MattBDev** [comment] 2019-08-08 00:08
I tested this out on @AeSix's server with several tricks I know but was unable to reproduce.

**Comment by jewome62** [comment] 2019-08-08 00:16
Seriously ?
Invite me on your plot world i will show you

**Comment by AeSix** [comment] 2019-08-08 00:44
minecats uses worldguard, and I believe worldguard may be interfering with testing. BUt then worldguard would be a simple answer to the problem if that's the case.

**Comment by jewome62** [comment] 2019-08-08 00:47
I can make more simple : 
Paper 1.13.2 et Plotsquared latest
![image](https://user-images.githubusercontent.com/472429/62667059-4ff93880-b986-11e9-8df0-286eb1b6e268.png)

I create new server without other plugin just PlotSquared and WorldEdit (required dependency)
![image](https://user-images.githubusercontent.com/472429/62667202-e4fc3180-b986-11e9-9911-b99c6aabc0de.png)

with new setup, no special config.
i claim the plot on the left
![2019-08-08_02 41 18](https://user-images.githubusercontent.com/472429/62667121-9058b680-b986-11e9-9972-fe857bf470b1.png)
![2019-08-08_02 41 33](https://user-images.githubusercontent.com/472429/62667148-abc3c180-b986-11e9-8218-9eea74a8a93e.png)
![2019-08-08_02 41 43](https://user-images.githubusercontent.com/472429/62667150-ae261b80-b986-11e9-8f4d-190d7144f920.png)

**Comment by MattBDev** [comment] 2019-08-08 04:26
Literally the piston shouldn't be able to extend in the first place. @NotMyFaultOG can you please rest this out for us?

**Comment by jewome62** [comment] 2019-08-08 08:55
Hello @MattBDev  and @N0tMyFaultOG . I retry this morning and test with non-op and that's the same bug.
I specify that it is not to remove a block of the border (it is well blocked) but of the road towards the border. When the block is on the edge, we can not pull it further on the pad or push it to put it back in place

**Comment by AeSix** [comment] 2019-08-10 15:37
Tested using: PlotSquared 3.05, WE7/WG7 on Spigot 1.13.2 (final build)
Pistons do not extend into the border area, and as such cannot interact with the blocks in the road. 

As @jewome62 used a newer version, I have updated P2 to 4.318, tested again with the same results.

Being I got the same results, I changed servers to Paper 1.13.2 626.  I received the same results.

This must be an issue with some configuration, Java JVM version, or some other niche environment dynamic that does not exist in most P2 installation environments.  

Closing ticket as the issue is not replicable in multiple servers and versions. I do not believe WorldGuard plays a role in this as the piston itself is not able to interact with the block /in/ the road, and such WorldGuard wouldn't have an opportunity to control this.  

@jewome62  Please test using Java 1.8 update 201 or newer, PlotSquared 4.318, WorldGuard 7 release, WorldEdit 7 release, and Paper 626.  If you continue to have the same issue, it's more than likely some issue with your host server, or some compatibility plugin or similar.  If you can replicate this on another host machine using the versions here, re-post and we'll reopen the ticket.

**Closed by AeSix** 2019-08-10 15:37 UTC
Labels: 1.13.x, Spigot, [✖] Cannot Replicate

**Comment by jewome62** [comment] 2019-08-11 18:43
@AeSix 
Since more than 1 week i'm on
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)

**Comment by AeSix** [comment] 2019-08-11 19:00
Well, try installing Spigot 1.13.2, WorldEdit 7 release, WorldGuard 7 release, PlotSquared 4.318+, and try.  With just this, running on Java 8 u201, the proper behavior is experienced.  

What is your host OS?
I need your type (Windows, Linux, BSD, macOS, etc), version, distro, kernel version, etc if not Windows.
