### ISSUE TITLE
Setting aliases for merged plots

### ISSUE THREAD

**Issue by ZuRiKanHD** [IntellectualSites/PlotSquared#4373] opened 2024-03-13 17:51 UTC
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Hello, we noticed that when setting aliases for merged plots there is a confirmation in the chat that the alias has been set. However, this does not appear in the plot information. Teleporting doesn't work either. The merged plot consists of 4 plots.

### To Reproduce

Create a merged plot
Try setting an alias.

### Expected behaviour

Alias can be set for merged plots.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fb329c98dc3141b9ab870b393da72677

### PlotSquared Version

7.3.6 - Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment] 2024-03-13 18:58
Plotsquared is not compatible with Pufferfish, it is developed for spigot and paper. Also you should check your Luckperms as it throws a lot of errors and is needed for you to have permissions to set the alias. Please resolve your errors first and retry replicating this issue.

**Comment by SirYwell** [comment] 2024-03-13 19:00
Sounds like a duplicate of #3573

**Comment by OneLiteFeather** [comment] 2024-03-13 19:08
For the teleportation, you should take a look at using Paper instead

**Closed** 2024-03-13 19:09 UTC
Labels: Duplicate
