### ISSUE TITLE
Crashing since P2 v4 build 115

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#2241] opened 2019-01-18 23:27 UTC
# Bug report template 

**Debug paste link:** 
https://incendo.org/paste/view/7633ef7aa786412cbae920ca2464ceec

**Description of the problem:** 
Server crashes since build 115 or so. Not sure since a few builds were not 100%.
Server starts, when finished the boot process, it hangs.
https://pastebin.com/ZePTmxQp
Logblock is called in the errors, but until build 106 it runs fine. I suspect it has something to do with both plugins using a mysql database.

**How to replicate:** 

Build 106 runs fine. Build 115, and 117 start up and crash.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment] 2019-01-19 00:11
Try disabling plot expiry

**Comment by dordsor21** [comment] 2019-01-19 00:20
Also I can't replicate this at all.

**Comment by dordsor21** [comment] 2019-01-19 14:09
`plots.admin.command.autoclear` and it should come up on join/when entering a plot, from what i can decipher

**Comment by x1p** [comment] 2019-01-19 23:16
It seems that turning plot expiry off has somewhat solved it.
I can't think of any reason why this should be a problem. There are not that much plots to examen and the number of plot to be cleared are close to zero. I have checked most plots by hand this afternoon.

**Comment by x1p** [comment] 2019-01-20 16:43
Done that.
Funny thing is: although nothing is executed, the CPU goes to 100%. Something is done in the background. How much calculation can be done with <100 plots?

Would love to have this enabled somehow in the future.
Thanks for your help.

**Comment by dordsor21** [comment] 2019-01-20 17:45
So, you don't currently get crashes with expiry disabled? Also the 100% CPU is not (at all) necessarily PlotSquared.

**Comment by AeSix** [comment] 2019-01-29 15:45
Looking at the plugin list in the debugpaste, 
I would suggest disabling half your plugins and testing. If the issue continues, disable the other half. (leave whats needed for P2 to operate though)

If the issue continues after that, disable all but the most essentials plugins and test. If it don't happen with the bare minimum of what's needed for P2 to run... then it's an issue with another plugin. If it does continue, then it's probably something to do with the server you're running on. 

Possible causes: Multiverse Core, AWE, LogBlock, DynMap, Java 1.8_181 (update to 191, 201 seems to break consoles)

Note: Unless you have non-plot worlds, you should remove Multiverse core and use P2 to manage all of the worlds.  That and AWE are probably the two I'd disable first. 

--------
If this issue has already been resolved, mind closing the ticket? Otherwise, let us know how the above testing went! Thanks :)

**Comment by x1p** [comment] 2019-01-29 16:25
Multiverse has been running stable for about 5 months, probably more, with no issues what so ever. AWE was already removed and was not the issue.
Since plot expiry has been turned off, it runs fine. Plot expiry was not 100% working anyway. So I would suggest this is the cause most probably.
The server has plenty resources. That shouldn't be the cause either. I ran fine for months with excellent performance.

**Comment by AeSix** [comment] 2019-01-29 20:14
I understand your concern.  The problem is that Multiverse and PlotSquared no longer play well together, since 1.13.2, and have been going downhill since.  MV will probably work with P2 again in the future, same with FAWE and AWE.  But for now, it's recommended that P2 on 1.13 uses WorldEdit and the built-in multi-world management, because of the issues. 

AFAIK, The plot expiry code hasn't been messed with - and to be even more accurate - I've been running builds from 115 to 129 in production for weeks, with absolutely no issue with plot expiry.  So, for your installation to have an issue with plot expiry, and the rest of us not - then it's not an issue with PlotSquared, but an issue with some other plugin, the server you've built, the version of java, your OS, or the host your OS is installed on.  Couple that with the KNOWN ISSUES with MV and AWE both, these should be your first targets of scrutiny, not P2. 

It would help your case completely if you were to follow the instructions I gave you earlier in the day, to test out your plugins and install.

**Comment by x1p** [comment] 2019-01-29 22:23
Tried it without MV, but multiple plugins go completely nuts about things that exist in a non existent world.
I'll rather accept that expiry does not function.

**Closed** 2019-01-29 23:00 UTC
Labels: [✖] Cannot Replicate
