### ISSUE TITLE
1.16.5 my server does not recognize the plugin

### ISSUE THREAD

**Issue by RoboRobi2** [IntellectualSites/PlotSquared#3135] opened 2021-07-02 10:40 UTC
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

when I put in the plugin and then restarted it and entered /plugin, the plugin was not visible and you couldn't use it

### To Reproduce

1 I install the plugin on the server
2 i started the server and it wasn't there

### Expected behaviour

i think it worked and i can make a plot world

### Plot Debugpaste

unknown command

### PlotSquared Version

6.0.5 premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-07-02 10:41
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3134
Stop raising nonsense issues.

**Closed by NotMyFault** 2021-07-02 10:41 UTC
Labels: Invalid

**Comment by RoboRobi2** [comment] 2021-07-02 10:44
sorry but we have no more information the plugin doesn´t work

**Comment by NotMyFault** [comment] 2021-07-02 10:46
There is always information, e.g. taking a look in your latest.log will tell you why something didn't load.

**Comment by RoboRobi2** [comment] 2021-07-02 10:48
the problem is in the log there is nothing the server does not recognize the plugin

**Comment by RoboRobi2** [comment] 2021-07-02 10:49
Loading libraries, please wait...
[11:38:50] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:38:51] [main/INFO]: Reloading ResourceManager: Default, bukkit
[11:38:52] [Worker-Main-12/INFO]: Loaded 7 recipes

[11:38:50] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

[11:38:51] [main/INFO]: Reloading ResourceManager: Default, bukkit

[11:38:52] [Worker-Main-12/INFO]: Loaded 7 recipes

[11:38:53] [Server thread/INFO]: Starting minecraft server version 1.16.5

[11:38:53] [Server thread/INFO]: Loading properties
&gt;
[11:38:54] [Server thread/INFO]: This server is running CraftBukkit version 3096-Spigot-9fb885e-296df56 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

[11:38:55] [Server thread/INFO]: Debug logging is disabled

[11:38:55] [Server thread/INFO]: Server Ping Player Sample Count: 12

[11:38:55] [Server thread/INFO]: Using 4 threads for Netty based IO

[11:38:55] [Server thread/INFO]: Default game type: SURVIVAL

[11:38:55] [Server thread/INFO]: Generating keypair

[11:38:55] [Server thread/INFO]: Starting Minecraft server on 134.255.227.215:25565

[11:38:55] [Server thread/INFO]: Using default channel type

[11:38:57] [Server thread/ERROR]: Could not load 'plugins/PlotSquared-Bukkit-6.0.5-Premium.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/plotsquared/bukkit/BukkitPlatform has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:224) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.UnsupportedClassVersionError: com/plotsquared/bukkit/BukkitPlatform has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_211]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_211]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:186) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211]
at org.bukkit.plugin.java.PluginClassLoader.&lt;init&gt;(PluginClassLoader.java:67) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
... 7 more

[11:38:57] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.47

[11:38:58] [Server thread/INFO]: [HolographicDisplays] Loading HolographicDisplays v2.4.8

[11:38:58] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b131

[11:38:58] [Server thread/INFO]: [floodgate] Loading floodgate v2.0-SNAPSHOT

[11:38:58] [Server thread/INFO]: [floodgate] Took 563ms to boot Floodgate

[11:38:58] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.5+57d5ac9

[11:38:59] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@1a8553c1]

[11:38:59] [Server thread/INFO]: [Essentials] Loading Essentials v2.18.2.0

[11:38:59] [Server thread/INFO]: [EssentialsProtect] Loading EssentialsProtect v2.18.2.0

[11:38:59] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.18.2.0

[11:38:59] [Server thread/INFO]: [EssentialsGeoIP] Loading EssentialsGeoIP v2.18.2.0

[11:38:59] [Server thread/INFO]: [EssentialsAntiBuild] Loading EssentialsAntiBuild v2.18.2.0

[11:38:59] [Server thread/INFO]: [Geyser-Spigot] Loading Geyser-Spigot v1.4.0-SNAPSHOT

[11:38:59] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.18.2.0

[11:38:59] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v4.2.2-b812

[11:38:59] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.5+3827266

[11:38:59] [Server thread/INFO]: [EssentialsXMPP] Loading EssentialsXMPP v2.18.2.0

[11:38:59] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.3.47

[11:39:00] [Server thread/WARN]: [LuckPerms] Loaded class net.kyori.adventure.text.Component from floodgate v2.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.

[11:39:00] [Server thread/INFO]: __

[11:39:00] [Server thread/INFO]: | |__) LuckPerms v5.3.47

[11:39:00] [Server thread/INFO]: |___ | Running on Bukkit - CraftBukkit

Thats the log

**Comment by NotMyFault** [comment] 2021-07-02 10:51
> the problem is in the log there is nothing the server does not recognize the plugin

There is much more information than "nothing". Please read your logs carefully. Tho, it's quite hard to call such a part nothing.
```
[11:38:57] [Server thread/ERROR]: Could not load 'plugins/PlotSquared-Bukkit-6.0.5-Premium.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/plotsquared/bukkit/BukkitPlatform has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:224) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.UnsupportedClassVersionError: com/plotsquared/bukkit/BukkitPlatform has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_211]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_211]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:186) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
... 7 more
```
Anyway, you need Java 16 or newer to launch the plugin, like outlined in the changelogs.

**Comment by RoboRobi2** [comment] 2021-07-02 10:52
how to put java 16 on the server

**Comment by NotMyFault** [comment] 2021-07-02 10:54
Use this guide https://paper.readthedocs.io/en/latest/java-update/
For more assistance, join our [discord server](https://discord.gg/intellectualsites)
