### ISSUE TITLE
Road schematic pasting one block higher

### ISSUE THREAD

**Issue by kylewbird** [IntellectualSites/PlotSquared#3405] opened 2021-12-27 12:59 UTC
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

The road schematic is pasting one block higher than it is supposed to. I have change the following setting as instructed to but it still does not work properly. 
If paste-road-on-top: is set to true, then only the first layer is copied, 
If paste-road-on-top is set to false then both layers are copied, but the whole schematic is pasted one block higher

### To Reproduce

see video 

### Expected behaviour

as explained above, see video

### Screenshots / Videos

https://www.youtube.com/watch?v=4geN5sUQPVs&ab_channel=DarkenedFury

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fffa1cbc5a0b42e297d96187335af82e

### PlotSquared Version

PlotSquared v6 6.2.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-12-30 09:59
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3346

**Closed by NotMyFault** 2021-12-30 09:59 UTC
Labels: Duplicate
