### ISSUE TITLE
Armor stands can't be placed anymore

### ISSUE THREAD

**Issue by V1Matt** [IntellectualSites/PlotSquared#4121] opened 2023-07-24 12:52 UTC
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

In 7.0.0 RC 3, players can not place armor stands anywhere (not on places they are supposed to be able to place them, nor on places they are not supposed to be able to place them, like roads or unowned plots).

Switching back to Release Candidate 2 _does_ fix the issue.

Fawe is up to date. Changing to older Fawe version does _not_ fix the issue.

Removing my own Plot plugins does _not_ fix the issue.

I made myself server operator to see if that would somehow make a difference, but even then I still couldn't place armor stands.

Entity limits are not reached. Armor stands can not be placed, even if there are no entities in the entire world.

The placing sound of an armor stand is played when attempting to place an armor stand in an area where players should be able to place them, in other places there is no placing sound.

I went through all config files (Paper, Spigot, Bukkit, Plotsquared, Fawe) to see if I could change something in there to fix the issue, but I found nothing.

Other entities, like mobs, paintings and item frames, seem to be working fine.

Using the vanilla /summon command to summon an armor stand still works.

There are no errors in console or in-game chat.

The armor stand _does_ get taken from the player's inventory when attemping to place it in survival mode (not in creative mode).

I hope my English is alright. Thank you for reading, I hope I filled in this form in the right way!

### To Reproduce

1. Get an armor stand
2. Try to place it anywhere you're supposed to be able to place it.
3. It is not placed.

### Expected behaviour

Players should be able to place armor stands in locations they have access to.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8d8fb0325a8248db9dfbfe7f6ff1990a

### PlotSquared Version

7.0.0-rc.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2023-07-25 15:20
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/4120

**Closed by NotMyFault** 2023-07-25 15:20 UTC
Labels: Requires Testing
