### ISSUE TITLE
/p clear is creating terrain

### ISSUE THREAD

**Issue by SpaceWeedMC** [IntellectualSites/PlotSquared#933] opened 2016-03-05 23:31 UTC
# Bug report template (clear for feature request)
http://hastebin.com/etomudomeh:

/p clear for the bridge template:

Claim a plot and do /p clear:

Make sure you've completed the following steps (put X inside of brackets):
- [X] Include `/plot debugpaste`
- [ ] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [ ] Made sure the bug/error isn't caused by any other plugin

**Comment by SpaceWeedMC** [comment] 2016-03-05 23:36
Picture!

http://prntscr.com/abpftj

**Comment by manuelgu** [comment] 2016-03-06 07:31
Might be related to or is a duplicate of #932

**Comment by boy0001** [comment] 2016-03-06 08:04
Try: https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting

**Comment by boy0001** [comment] 2016-03-07 14:07
Will reopen if the above does not solve your issue.

**Closed by boy0001** 2016-03-07 14:07 UTC
