### ISSUE TITLE
One player unmerging in a plot group affects the entire group

### ISSUE THREAD

**Issue by Trophonix** [IntellectualSites/PlotSquared#2183] opened 2018-12-05 18:41 UTC
**Debug paste link:** 
Can't give a debugpaste as this issue occurred on someone else's server.

**Description of the problem:** 
If a group of players decide to merge plots together and one later changes his or her mind and does /plot unmerge, the ENTIRE huge group is completely unmerged, deleting everything in the space between the plot sections. This is a game-breakingly huge oversight in development, I will not recommend this plugin as long as this remains a problem.

**How to replicate:** 

- merge plots with several other players
- unmerge
- all the plots have been unmerged without any action being required by any of the other players, destroying their plots.

**Comment by Sauilitired** [comment] 2018-12-05 18:50
The problem here is that a merged plot is treated like a single plot, and un-linking it will split the entire plot into the individual plots. This is intended behavior, and so not a bug. What could be done is instead treating an un-link as the removal of one plot from the mega plot. Which would then cause the command to behave as expected by OP. 

I am not sure if this is necessarily a change that should be implemented. But I am very much willing to listen to opinions on the matter.

**Comment by AeSix** [comment] 2018-12-05 19:02
The idea of allowing multiple players to merge plots together has bothered me since I found that its possible. I do not allow it, as intending behavior will do nothing but cause antagonism and anger players. 

In my opinion, this functionality should be removed altogether. Even the suggestion of removing the single plot can destroy tons of work by other players, resulting in the same angered players.

Perhaps this functionality should require the server owner editing the conf file to explicitly enable, after reading a disclosure of how unlinking works.

**Comment by Sauilitired** [comment] 2018-12-05 19:14
@AeSix I tend to agree. A mega/merged plot is meant to be treated as a single plot, and allowing for partial un-linking would mean that there's a distinction between merged and single plots.

Removing a single plot would still have to create roads between the newly separate plot, and the remaining merged plots. This would mean that up to 4 roads would re-generate by default (there is still the possibility to prevent road re-generation by using command arguments). I feel as if this would just further complicate things.

**Comment by Sauilitired** [comment] 2018-12-06 15:42
I have come to the conclusion that this isn't something that will be changed. If someone has any good arguments against this, then feel free to submit an issue [here](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues).

**Closed by Sauilitired** 2018-12-06 15:42 UTC
Labels: [-] Low Priority, [?] help wanted
