### ISSUE TITLE
/plot move and /plot copy not working

### ISSUE THREAD

**Issue by whitelily36** [IntellectualSites/PlotSquared#2290] opened 2019-03-08 14:06 UTC
# Bug report template 

**Debug paste link:** 

https://incendo.org/paste/view/20e505aac15f4fbfaefdb0c525db47ff
**Description of the problem:** 
/plot move and /plot copy not working.  For /plot move it only moves the title, none of the blocks.  /plot copy just doesn't work.

**How to replicate:** 

Claim a plot, build random stuff on it
Go to another plot and obtain the plot id via /plot info
Go back to the origin plot and type either /plot move X;Y or /plot copy X;Y

**Checklist**:

- [y] I included a `/plot debugpaste` link
- [y] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [y] I made sure I am using an up-to-date version of PlotSquared
- [y] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-03-08 18:26
I confirm this is not working for me. 
https://incendo.org/paste/view/9b86e4a553944e55bd355a151ecaf8bf

Perhaps this is due to the use of an in-development version of FAWE on my part.

@whitelily36  It does not state which version of WorldEdit you are using.  Please confirm you are using WorldEdit 7 Beta 5 from here:
https://dev.bukkit.org/projects/worldedit/files

If the issue is resolved with WE7b5, please update the ticket and close.  If it is NOT resolved with WE7b5, please update the ticket and let us know! 

Thank you!

**Closed** 2019-03-08 23:04 UTC

**Comment by whitelily36** [comment] 2019-03-10 12:39
I can confirm we are using WorldEdit 7 Beta 5.
