### ISSUE TITLE
Trees wont grow in merged plots

### ISSUE THREAD

**Issue by augesrob** [IntellectualSites/PlotSquared#1021] opened 2016-03-29 04:43 UTC
There is no bug info in console

**Debug paste link**:
http://hastebin.com/ilewoxabag

**Description of the problem:**

Players and OP owners can not grow trees on merged plots.
I works only in the new claim area but not the older one.
It works if the plot isn't merged at all.

**How to replicate**:

--(Auto merge is on)--

#Trees Grow

1. Claim a plot either /p claim or /p auto
2. Claim a few plots side by side. They auto merge together.
3. Place a sapling down on the ground *wait for it to grow or use bone meal*
*Please not this is the step that doesnt work at all
4. Doesn't matter what sapling it is it grow regardless. 

- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [-] Made sure the bug/error isn't caused by any other plugin

**Comment by augesrob** [comment] 2016-03-29 04:43
Update: #Chorus Flower - They are growing so please ignore this. Trees are not growing on merged plots still.

**Comment by MattBDev** [comment] 2016-03-29 05:04
I can't replicate this. Please try limiting the plugins you are using to see if this is the cause of the issue.

**Comment by MattBDev** [comment] 2016-03-29 15:27
@augesrob Have you been able to reproduce this without all those plugins?

**Comment by augesrob** [comment] 2016-03-29 15:32
I havent removed any of them because i do use them all. Sorry.

**Comment by MattBDev** [comment] 2016-03-29 15:33
@augesrob you can't whitelist the server and disable a few to test this in your plotworld? If not, setup a test server?

**Comment by manuelgu** [comment] 2016-03-29 15:33
We don't expect you to remove plugins from the server you are running production. You could mirror your server and make it a test server whilst the main server can run..

**Comment by augesrob** [comment] 2016-03-29 15:58
@manuelgu Yes ill do this via portforward. Might take awhile to back it all up

**Comment by MattBDev** [comment] 2016-03-31 16:41
Any update on this because I've been able to prove twice that this is an invalid claim

**Comment by MattBDev** [comment] 2016-04-04 16:10
Closing since I asked for an update without a reply and I haven't been able to reproduce on SEVERAL difference instances.

**Closed by MattBDev** 2016-04-04 16:10 UTC
Labels: [✖] Cannot Replicate

**Comment by alchemistmatt** [comment] 2016-04-24 01:11
We have also experienced this bug.  Trees would only grow (with bonemeal) on one of 6 merged plots. As soon as we unmerged the plots, bonemeal worked fine on all of the trees that previously refused to grow.  I'll make an effort to disable plugins to see if I can narrow down the conflicting one.

**Comment by alchemistmatt** [comment] 2016-04-24 02:07
Test completed as requested.  I removed every single plugin except for PlotSquared and I still could not grow a tree with bonemeal on the second half of a merged plot.  The first half works; the second half doesn't (and with more than 2 plots, only the first plot works).  Please repeat your test with that in mind.  We're running Spigot 1.9.2, built from commit [5a403651d2b](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/5a403651d2b6da681d7aba14e3b1df8171fc5249) along with BungeeCord built from commit [b6b015f] (https://github.com/SpigotMC/BungeeCord/commit/b6b015fe1f5b4ed62bb0f09c03cafda3efe82ac0).  And we're using PlotSquared 3.3.3, and Java 1.8.0_66.

**Comment by alchemistmatt** [comment] 2016-04-24 03:42
I would be willing to try a dev build of PlotSquared, but none of the .jar files at http://ci.athion.net/job/PlotSquared/127/ has a plugin.yml file (or the same structure as the 3.3.3 .jar file) so I'm not sure where/how to get a dev version.

**Comment by lagnat** [comment] 2016-05-28 20:06
Seeing this bug as well.
