### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by lmorgh** [IntellectualSites/PlotSquared#1142] opened 2016-05-30 09:27 UTC
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/afosuwuren.avrasm <-- just the error
http://hastebin.com/tidoxakili
**Description of the problem:**
Throws error in console on startup

**How to replicate**:
Start my server
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- x[] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment] 2016-05-30 19:53
Duplicate of #1105

**Closed by MattBDev** 2016-05-30 19:53 UTC
Labels: [✖] Duplicate
