### ISSUE TITLE
Whole chunks are deleted.

### ISSUE THREAD

**Issue by BlockyTheDev** [IntellectualSites/PlotSquared#3569] opened 2022-04-12 17:30 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When using /plot delete, /p merge or /p clear there appears an huge hole (Part of nabour Plots and whole road gone). If you try these commands after that again the plugins says that there is a timer bound to the plot or me until restart. After the restart the plot looks like new generated but the nabour plots deleted blocks aren't here anymore.

### To Reproduce

1. Install the newest PlotSquared version & Fawe stable version
2. Claim Plots
3. Delete Plots
4. See
5. /restart
6. See

### Expected behaviour

The Plot should be deleted properly (No ways gone...) and the Plots shouldn't have any bound timer or user left. It should be like a fresh generated plot/road.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8a96ff30d28c41b78f847482db7a47ab

### PlotSquared Version

6.6.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by BlockyTheDev** [comment] 2022-04-12 17:31
![Screenshot 2022-04-12 193134](https://user-images.githubusercontent.com/86119630/163020449-ca216932-c254-4444-a12f-a5c971be87a4.jpg)

**Comment by NotMyFault** [comment] 2022-04-14 18:33
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1666

**Closed by NotMyFault** 2022-04-14 18:33 UTC
