### ISSUE TITLE
Schematics are not importable into MCEdit.

### ISSUE THREAD

**Issue by Quicksteve** [IntellectualSites/PlotSquared#1131] opened 2016-05-24 17:35 UTC
**Debug paste link**: http://hastebin.com/zaresociko

**Description of the problem:** Plot Downloading works properly, however importing them into MCEdit fails with the following error:

```
Unhandled Exception

Traceback (most recent call last):
  File "/home/leo/Playground/Java/mcedit2/src/mcedit2/editorsession.py", line 883, in import_ (self is a EditorSession)
    self.importSchematic(filename)
  File "/home/leo/Playground/Java/mcedit2/src/mcedit2/editorsession.py", line 957, in importSchematic (self is a EditorSession)
    schematic = WorldEditor(filename, readonly=True)
  File "/home/leo/Playground/Java/mcedit2/src/mceditlib/worldeditor.py", line 233, in __init__ (self is a WorldEditor)
    self.adapter = findAdapter(filename, readonly, resume=resume)
  File "/home/leo/Playground/Java/mcedit2/src/mceditlib/findadapter.py", line 62, in findAdapter  
    raise ValueError("Cannot detect type of file %s." % filename)
ValueError: Cannot detect type of file /home/leo/Downloads/plot (1).schematic.
```

**How to replicate**: Use /plot download, then download the schematic and try importing it into MCEdit (Using MCEdit 2 as MCEdit 1 will not work on Ubuntu, even with wine).

I've attached the schematic I tried to import (had to ZIP it to allow it to upload): 
[Plot.zip](https://github.com/IntellectualSites/PlotSquared/files/280082/Plot.zip)

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment] 2016-05-26 15:31
Confirmed.
![](http://i.imgur.com/1wVEDJ9.png)

PlotSquared doesnt fully save all NBT data in a schematic file, torch rotation for example. This might be the issue here.

**Comment by MattBDev** [comment] 2016-05-26 17:13
Note to self or Empire: needs to be fixed before 3.4.0

**Comment by timafh** [comment] 2016-06-04 09:26
Will the fix for this issue include saving of chest content, sign content etc?

**Comment by dordsor21** [comment] 2016-09-06 12:10
is still a problem and is of quite high priority

**Comment by MattBDev** [comment] 2016-09-07 15:01
Can someone provide an example schematic that won't import?

**Comment by dordsor21** [comment] 2016-09-07 15:39
[plot.zip](https://github.com/IntellectualSites/PlotSquared/files/459602/plot.zip)

**Comment by MattBDev** [comment] 2016-09-07 19:22
I couldn't figure out why. I think we need to summon @boy0001 for this.

**Comment by ItsAZZA** [comment] 2016-09-13 13:57
Any news on fixing this issue? If you need any more info, please feel to contact!

**Comment by boy0001** [comment] 2016-09-14 00:00
Downloaded files are missing the gzip footer (10 bytes which are redundant since it's also the end of the file). It works with WorldEdit and PlotSquared because both stop reading at the end of the file. The uncompressed bytes are identical. 

The gzip output stream isn't closed until after the file is uploaded as closing it will also close the underlying stream. To fix this the gzip-os needs to be passed some wrapped os that doesn't allow closing the underlying stream.

**Closed** 2016-09-14 00:13 UTC
Labels: [!] Bug, [‼] high priority

**Comment by dordsor21** [comment] 2016-09-15 06:57
Not fixed

**Comment by manuelgu** [comment] 2016-09-15 10:39
@dordsor21 Got the [latest](http://ci.athion.net/job/PlotSquared/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-3.4.6-SNAPSHOT-a4363bd.jar) development version of PlotSquared and created a new schematic with that version?

**Comment by dordsor21** [comment] 2016-09-15 12:37
yes

**Comment by ItsAZZA** [comment] 2016-09-15 12:50
Can confirm. Still the same error, as earlier in the latest build of PlotSquared.

**Comment by Quicksteve** [comment] 2016-09-15 12:52
Can confirm. This still doesn't work.

**Comment by boy0001** [comment] 2016-09-15 13:48
You need to also update FAWE if you have that installed.

**Comment by dordsor21** [comment] 2016-09-15 14:52
Can't use against latest FAWE that includes the fixes as it's broken

**Comment by dordsor21** [comment] 2016-09-16 15:12
Can confirm works against latest FAWE

**Comment by ItsAZZA** [comment] 2016-09-18 21:29
Can confirm, works using latest FAWE. Thanks for the fix!
