### ISSUE TITLE
Question: Add ability to have /plot unclaim command, but make toggleable in config?

### ISSUE THREAD

**Issue by VoxaDub** [IntellectualSites/PlotSquared#1078] opened 2016-04-24 03:03 UTC
Is it possible that the /plot unclaim command could be added as an alias or just a toggle in the config, but set to disabled by default? Or just be an alias for /plot setowner none with a set permission? Since I cant just give someone the permission to do "/plot setowner none"

**Comment by JackDn** [comment] 2016-04-24 14:44
Please stop creating new issues about this.

**Comment by VoxaDub** [comment] 2016-04-25 03:51
No, I can create a suggestion. No reason I shouldnt be able to.

**Comment by JackDn** [comment] 2016-04-25 04:05
You can't create 3 issues about the same suggestion which has already been denied.

**Comment by VoxaDub** [comment] 2016-04-25 04:06
I created one issue?

**Comment by VoxaDub** [comment] 2016-04-25 04:06
This is an entirely different suggestion.

**Comment by JackDn** [comment] 2016-04-25 04:15
#1059

**Comment by VoxaDub** [comment] 2016-04-25 04:40
Thats one, learn to count. And its not the same issue, learn to read as well.

**Comment by MattBDev** [comment] 2016-04-25 17:25
Duplicate of #1059

**Closed by MattBDev** 2016-04-25 17:25 UTC
