### ISSUE TITLE
P2 not preventing players from using portals

### ISSUE THREAD

**Issue by TobyMinceraft** [IntellectualSites/PlotSquared#2410] opened 2019-06-27 23:56 UTC
**PlotSquared Version Number:**
- PlotSquared-4.298

**Spigot/Paper Version Number:**
- git-Spigot-df0eb25-8003ced (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
(just realized, not latest version)

**Minecraft Version Number:** 
- 1.14.2

**Links to worlds.yml file and settings.yml file:**
- worlds.yml:  https://pastebin.com/vE37u6P6
- settings.yml:  https://pastebin.com/uQGAq7NG

**Description of the problem:**
Partially told in title.
When a player (such as myself) goes through either an End or Nether portal, rather than being met with the portal travelling sound constantly being played and the player remaining in the P2 world, they are sent to the default world for that portal.

**Any relevant console output or screenshots:**
- n/a

**Plugins being used on the server:**
- CoreProtect
- PluginConstructorAPI
- Essentials
- MineableSpawners
- ClearLag
- MultiverseReloaded (not to be confused with Multiverse - similar plugin, fewer features)
- Lockette
- WoodCutter
- NoSpawnChunks
- FastAsyncWorldEdit
- EssentialsChat
- PermissionsEx
- SupaDupaBroadcast
- ViaVersion
- CraftingStore
- Non-Specific-Odyssey
- Vault
- ViaBackwards
- EssentialsSpawn
- TalkAs
- PerWorldInventory
- CrateReloaded
- ProtocolLib
- Vote
- Votifier
- AuctionHouse
- DiscordSRV
- ServerSigns
- SuperVanish
- ServerListPlus
- PluginLibrary
- WorldEdit
- PlotSquared
- WorldGuard
- EditableSign
- GriefPrevention
- BuildPortals
- ChestShop
- GriefPreventionFlags

**How to replicate:**
- Make sure you have a normal world **not** managed by P2, with server set at default settings
1)  In a PlotSquared-managed world, build a Nether or End portal
2)  Go into the portal
3)  Suddenly, you are in the other world

**Checklist**:
- [x] I made sure there are no duplicates of this report
- [x] I included all information required in the sections above
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin"

" Note: because of this, there was an error in GriefPrevention where it couldn't log the portal creation, but of course that is also because of Spigot's portal handling.

**Comment by AeSix** [comment] 2019-06-28 00:42
Is the repeatable without BuildPortals, MultiverseReloaded, etc? With just P2? 

Half of the plugins I looked up did not have stable 1.14 releases.  Yes, that matters.

**Comment by TobyMinceraft** [comment] 2019-06-28 01:26
BuildPortals is generating a few exceptions if I travel to certain worlds, but that doesn't mess with the regular portals; and MultiverseReloaded is just a world management plugin that creates worlds from in-game. Though, anything is possible.

I'll try booting up the server without these two and update you.

**Comment by TobyMinceraft** [comment] 2019-06-28 01:50
Without these two plugins, I am getting the same thing: portal use is not prevented.

**Comment by dordsor21** [comment] 2019-06-28 12:46
Is portal use prevented in a non-P2 world?

**Comment by TobyMinceraft** [comment] 2019-06-28 14:43
1)  No. Those portals are fine.
2)  I know that's possible, but what I'm looking for is to only disable the portals within the P2-managed world, not the rest of the server.

**Comment by dordsor21** [comment] 2019-06-28 14:45
Ah right, I understand.

**Comment by AeSix** [comment] 2019-08-09 12:31
@TobyMinceraft You can use WorldGuard to prevent portal use per world, using that world's global region.  

I do not see any mention of P2 having this behavior.  As such, this is a feature request, and should be put in as an issue at https://github.com/IntellectualSites/PlotSquaredSuggestions/issues

Additionally, there are multiple other plugins which you can use to bypass native behavior of portals in Minecraft, and which can be used to allow portals from specific worlds, or even WG regions. 

As this is not a bug, and is a feature, i'm closing the ticket.

**Closed by AeSix** 2019-08-09 12:31 UTC
Labels: 1.14.x, [✔] Verified
