### ISSUE TITLE
NBT Data isn't stored / pasted when using /plot schematic

### ISSUE THREAD

**Issue by Peda1996** [IntellectualSites/PlotSquared#2618] opened 2019-12-03 12:54 UTC
I am not sure if this issue is related to https://github.com/IntellectualSites/PlotSquared/issues/2569

### Server config info (Debug/file paste links):
https://athion.net/ISPaster/paste/view/d43812b0172a43e891fb499626124444

### Server type:
-  [x] Server Version: git-Paper-230 (MC: 1.14.4)

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4

### Server build info: 

[13:45:12 INFO]: Previous version: git-Paper-226 (MC: 1.14.4)

### WorldEdit/FAWE versions:

- [x] WorldEdit *version*:  Bukkit-Official (7.0.1;61bc012)

### Description of the problem:
Contents inside chests are not storing NBT Data when using /plot schematic save, and afterwards pasting the plot. I suspect that this also happens with other stored items. Saving and pasting schematics on worldedit on the other hand works without problems.

### How to replicate:

Walk onto a valid plot. Create a chest with an enchanted item inside. Type in /plot schematic save. Afterwards, paste the schematic with /plot schematic paste <schematicName>. 

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment] 2019-12-03 18:38
Partial duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2569
Will be fixed once if 2569 is implemented

**Closed by N0tMyFaultOG** 2019-12-03 18:38 UTC
Labels: [?] Testing Required
