### ISSUE TITLE
Can't Delete Plot (1.8)

### ISSUE THREAD

**Issue by UnioDex** [IntellectualSites/PlotSquared#2351] opened 2019-05-04 09:08 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
PlotSquared-Bukkit-19.05.02-77e2659-757.jar

**[REQUIRED] Spigot/Paper Version Number:** 
TacoSpigot 1.8.8

**[REQUIRED] Minecraft Version Number:** 
1.8.8
**[REQUIRED] Description of the problem:** 
I updated PlotSquared and tried to delete a plot but it gave me an error and didn't delete the plot properly.

**Any relevant console output or screenshots:**
https://pastebin.com/wNbGQXA5

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by UnioDex** [comment] 2019-05-04 09:08
To fix the issue i reverted back to build 686

**Comment by MattBDev** [comment] 2019-05-04 20:14
Can one of our issue moderators *cough*@Aesix*cough* find the duplicate of this issue and close this one?

**Comment by AeSix** [comment] 2019-05-05 18:25
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/1653

@UnioDex as Matt mistakenly believes I have the power to close tickets, can you add your findsings to the above referenced issue and close this issue please.

**Closed** 2019-05-05 18:27 UTC

**Comment by UnioDex** [comment] 2019-05-07 14:54
@AeSix @dordsor21 this issue wasn't duplicate. The one you are referenced is not relevant.

I tested every build since #686 to the latest one. And this issue starts with build #743 (https://ci.athion.net/job/PlotSquared-Legacy/743/)

Broken commit: https://github.com/IntellectualSites/PlotSquared/commit/13e190cfb80fed3344254237027fbb95ac092c0e

Last working version:
https://ci.athion.net/job/PlotSquared-Legacy/739/

**Comment by AeSix** [comment] 2019-05-07 19:34
If you're reverting changes, why not just stick to the last build that works?

Or branch that build and add in the commits that still work for 1.8.8?  At some point, plugins will no longer be able to support modern, legacy and archaic versions of Minecraft at the same time.

**Comment by UnioDex** [comment] 2019-05-08 08:20
@AeSix I actually stick to last build that works usually. But since you are still officially support 1.8.8, I wanted to let you know there is an issue + made a pull request to fix the issue. If you'd stop supporting 1.8.8 I would still do these changes but i would keep it on my own branch. So let me know if you don't want me to do pull requests because I use 1.8.8.
