### ISSUE TITLE
PlotSquared 6.10.6 causes server crash

### ISSUE THREAD

**Issue by Whitescan** [IntellectualSites/PlotSquared#3924] opened 2023-01-11 00:55 UTC
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Unexpected Error crashes the Server.
Worked on the previous version.

Not sure what else to include. 

### To Reproduce

1. See crash report below

### Expected behaviour

No unexpected errors and no crashes.

### Error log (if applicable)

https://paste.gg/p/anonymous/69d79d6fe43c4840a57c180b793c18b3

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/1e639bab15b1469c96a107c2cfc3881b

### PlotSquared Version

6.10.6-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

No additional information.

**Comment by NotMyFault** [comment] 2023-01-11 07:37
Please fill in steps to replicate the issue because this class does definitely exist:

![Screenshot 2023-01-11 at 08 35 25](https://user-images.githubusercontent.com/13383509/211745224-fab9d934-087b-4cd4-8c13-82cc36e8991b.png)

Maybe something went wrong on your end and mangled the while updating jar?

**Comment by Whitescan** [comment] 2023-01-11 14:38
Fresh download from [SpigotMC.org](https://www.spigotmc.org/resources/plotsquared-v6.77506/)
![grafik](https://user-images.githubusercontent.com/70441126/211833882-7116ed49-9028-4f63-b0c8-2c0ee6e027f6.png)

**Comment by Whitescan** [comment] 2023-01-11 14:39
> Please fill in steps to replicate the issue because this class does definitely exist:

I can't add steps to reproduce since I have no clue how it happend. But I think my Screenshot above proves that the class is actually just missing in the current build uploaded to SpigotMC.org

**Comment by NotMyFault** [comment] 2023-01-11 14:43
> But I think my Screenshot above proves that the class is actually just missing in the current build uploaded to SpigotMC.org

Why would you think so? It clearly is present on your screenshot:

![Screenshot 2023-01-11 at 15 40 54](https://user-images.githubusercontent.com/13383509/211835042-de1d1250-86c4-4d44-9872-b7a83c32a8d3.png)

**Comment by Whitescan** [comment] 2023-01-11 14:47
Well. Missed that one tbh. But still. The issue persists for some reason?

**Comment by NotMyFault** [comment] 2023-01-11 14:48
I'm waiting for steps to replicate the issue. Without, I fear I am unable to state anything specific.

**Comment by Whitescan** [comment] 2023-01-11 14:52
Yeah I get that. I'll try my best to replicate. I downloaded the jar on my server to check if the class is missing but it's also there.
No idea what caused this. 

Based on the name, I noticed there are some dark spots on the roads that were fine in the previous version.
Does it have anything to do with the class in question? https://prnt.sc/XYZbBY2NvAZk

**Comment by SirYwell** [comment] 2023-01-11 15:28
Try reproducing the problem with:
- only PlotSquared and FAWE installde
- Paper instead of Purpur

(also make sure to have backups of everything relevant)

**Comment by Whitescan** [comment] 2023-01-11 17:25
I tried that as well, wasn't able to reproduce ever since it happend.
No idea how it happend.

**Comment by NotMyFault** [comment] 2023-01-19 08:08
Given, nobody else reported that issue and almost 500 people use 6.10.6 I'll go ahead and close the issue assuming there went something wrong on your end while downloading or uploading the file.

**Closed by NotMyFault** 2023-01-19 08:08 UTC
Labels: Requires Testing
