### ISSUE TITLE
Nukkit support again (maybe PowerNukkit_X_)

### ISSUE THREAD

**Issue by IndianBartonka** [IntellectualSites/PlotSquared#4065] opened 2023-06-10 22:41 UTC
### What feature do you want to see added?

I like this plugin and i usually using nukkit

### Are there any alternatives?

Idk

**Comment by Scot-Survivor** [comment] 2023-06-11 10:02
Doesn't the Nukkit API almost completely mirror the bukkit api?

**Comment by NotMyFault** [comment] 2023-06-11 12:15
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3326

**Closed by NotMyFault** 2023-06-11 12:15 UTC
Labels: Enhancement
