### ISSUE TITLE
PlotSquared loads before WorldEdit dev 4106.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2305] opened 2019-03-20 12:16 UTC
PlotSquared Breaking dev 190
WorldEdit dev 4106

```
[05:08:44] [Server thread/ERROR]: Could not load 'plugins/PlotSquared-Bukkit-4.189.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.13.2.jar:git-Paper-568]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-568]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-568]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-568]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-568]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-568]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[patched_1.13.2.jar:git-Paper-568]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.13.2.jar:git-Paper-568]
	... 6 more
Caused by: java.lang.IllegalStateException: Failed to force load WorldEdit. Road schematics will fail to generate
	at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.<clinit>(BukkitMain.java:75) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[patched_1.13.2.jar:git-Paper-568]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.13.2.jar:git-Paper-568]
	... 6 more
Caused by: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platforms have been registered yet! Please wait until WorldEdit is initialized.
	at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:172) ~[?:?]
	at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.<clinit>(BukkitMain.java:73) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[patched_1.13.2.jar:git-Paper-568]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.13.2.jar:git-Paper-568]
	... 6 more
[05:08:45] [Server thread/ERROR]: Could not load 'plugins/plot2dynmap-2.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: PlotSquared
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:222) ~[patched_1.13.2.jar:git-Paper-568]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-568]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-568]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-568]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Downgrading to WorldEdit dev 4095, loading seems fine. Assuming this WorldEdit commit breaks P2. https://github.com/EngineHub/WorldEdit/commit/c885f70c7b561dc7bc1f603fac5eae380c48fb09

Edit: Actually I believe it may be due to this commit. https://github.com/EngineHub/WorldEdit/commit/d1c2a029bf87b77e7e774da7dadad4887dfb6ae9

**Comment by dordsor21** [comment] 2019-03-20 16:41
This will be fixed when WE release beta 6. We will not fix P2 to WE dev builds, as they change stuff too frequently.

**Closed by dordsor21** 2019-03-20 16:41 UTC

**Comment by Sauilitired** [comment] 2019-03-20 16:43
To add on to that. It's caused by our force loading "fix", which works fine in beta-05. Without the fix, the beta does not work. 

We know exactly how to fix this, when the next WorldEdit beta comes around. We won't push any fixes for their dev builds, and their code base tends to be quite volatile in between releases.

**Comment by AeSix** [comment] 2019-03-20 16:48
I think best bets for now is to stick with WorldEdit 7 beta 5 (unless they came out with a beta 6 in the last day or so)

FAWE is getting closer to being ready to work with P2... The devs and testers are working out issues still :)

**Comment by mibby** [comment] 2019-03-24 06:27
Okay, no worries. Just thought I'd let you know ahead of time. :)

For the time being, I just commented out https://github.com/IntellectualSites/PlotSquared/blob/c48116b723b690ed31e697d6d149e3551bd0e300/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/BukkitMain.java#L66 and recompiled manually. Seems to start-up fine now with the latest WorldEdit dev build.
