### ISSUE TITLE
Console Warning

### ISSUE THREAD

**Issue by YouShengL** [IntellectualSites/PlotSquared#4086] opened 2023-06-22 14:20 UTC
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

Start the server and the error log is there

### To Reproduce

Anything to Enable the HoloPlots

### Expected behaviour

No idea
The error comes out while i started the server without any player joined

### Screenshots / Videos

w

### Error log (if applicable)

https://paste.gg/p/anonymous/bce4ef1906c6402a842978f07d0655ac

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/136b7ba0e08c4e7a86098f65500e8e71

### PlotSquared Version

plotsquared-bukkit-7.0.0-RC.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

nothing

**Comment by NotMyFault** [comment] 2023-06-22 15:13
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/4082

**Closed by NotMyFault** 2023-06-22 15:13 UTC
Labels: Requires Testing

**Comment by YouShengL** [comment] 2023-06-22 15:16
I don't really understand, it seems like the problem of Holoplots and the different language of PlotSquared??

**Comment by NotMyFault** [comment] 2023-06-22 15:16
> I don't really understand, it seems like the problem of Holoplots and the different language of PlotSquared??

Read my response on the issue linked.

**Comment by mrfloris** [comment] 2023-06-23 10:07
> Duplicate of #4082

That's a duplicate of https://github.com/IntellectualSites/PlotSquared/issues/4079
