### ISSUE TITLE
Chestshop/sign selling compatibility?

### ISSUE THREAD

**Issue by Zhaotje** [IntellectualSites/PlotSquared#863] opened 2016-02-11 23:21 UTC
Hello,

I'm new to this plot plugin and I'm wondering how players can interact with chest selling/buying or sign selling/buying.
I have tested a few things but did not work out or unprotected the plots.

Does any know how to enable chest selling without players entering the chest.
The reason for help is that I changed from plotme that went corrupt and tried this with better/more options to plots. despite this problem, I really like the overal looks by it.

For more information please ask me freely.

With kind regards,

Zhaotje

**Comment by boy0001** [comment] 2016-02-12 05:02
Duplicate of
#776
#742
#606
#784

In the PlotSquared settings.yml change:
```YML
    flags: {}
```
to
```YML
    flags: 
      use: 63,68
```
Then use `/plot reload`

**Closed by boy0001** 2016-02-12 05:02 UTC
