### ISSUE TITLE
/plot (clear|delete) ignores configured borders

### ISSUE THREAD

**Issue by Maxetto** [IntellectualSites/PlotSquared#1076] opened 2016-04-23 18:19 UTC
**Debug paste link**:
http://hastebin.com/udafoseheg

**Description of the problem:**
When you clear a Plot with /plot clear or /plot delete, Plot borders of other plots are sandstone slabs (44:1), completely ignoring config options.
This doesn't happen to the plot you're clearing/deleting.

**How to replicate**:
- Set up a different block for borders in the Config
- (Might be needed) Set up a different road schematic
- Claim some adiacent plots
- Type: /plot clear (or /plot delete) on a plot

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment] 2016-04-23 21:47
I'm not sure if I understood you correctly, but I think that this is intended behavior. '/plot clear' only clears blocks within the borders and not the border itself.

**Comment by Maxetto** [comment] 2016-04-23 22:19
No, it does regenerate the North and the West part of the plots. It might be related to custom Road Schematics, however before version 3.4.X, I didn't have problems with clearing/deleting.

**Comment by boy0001** [comment] 2016-05-19 08:25
This has been fixed in the dev builds.

**Closed by boy0001** 2016-05-19 08:25 UTC
Labels: [!] Bug
