### ISSUE TITLE
Could not pass event PlayerBucketEmptyEvent

### ISSUE THREAD

**Issue by LaVADraGoN** [IntellectualSites/PlotSquared#2401] opened 2019-06-21 02:07 UTC
Paper Version 1.14.2: Build 94
PlotSquared v4.291
Minecraft Version Number: 1.14.2

*Links to worlds.yml file and settings.yml file:*
Settings.yml = https://pastebin.com/udjVRd0s
Worlds.yml = https://pastebin.com/jr5E0dFU

**Description of the problem: It is possible to place buckets filled with water on protected Plots.

Any relevant console output or screenshots: [ERROR] Could not pass event PlayerBucketEmptyEvent to PlotSquared v4.291

` [Server thread/ERROR]: Could not pass event PlayerBucketEmptyEvent to PlotSquared v4.291
java.lang.IllegalArgumentException: Cannot get ID of Modern Material
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.14.2.jar:git-Paper-94]
	at org.bukkit.Material.getId(Material.java:3319) ~[patched_1.14.2.jar:git-Paper-94]
	at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onBucketEmpty(PlayerEvents.java:2382) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor39.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-94]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-94]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-94]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-94]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:396) ~[patched_1.14.2.jar:git-Paper-94]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:368) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.ItemBucket.a(ItemBucket.java:139) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.ItemBucket.a(ItemBucket.java:69) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.ItemStack.a(ItemStack.java:330) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:393) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1448) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:975) ~[patched_1.14.2.jar:git-Paper-94]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-94]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

**Plugins being used on the server:**
ActionPoints, AnimatedNames, BuyRegion,ChatControl,Clearlag,cloudnet-bridge,CMI+,CMIInjector,CombatPets,CommandSyncClient,DiscordSRV,FeatherBoard,GadgetsMenu,InsaneShops,Jobs,JupiterCore,LiteBans,LuckyPerms,Minions,Multiverse-Core,MvdWPlaceholderAPI,PlotSquared,ProtocolLib,QuickShop-Remake,Spatan,TradeMe,Vault,votifier,worldedit,worldguard

How to replicate: 
We are not totally sure how this happends. We did some test on change permissions and such. But it seams to occur randomly for the default player.
Best replicated with using filled Bucked on not Solid Objects (stairs etc.) or entitys. It works not always ,but sometime it throw an Error in Console and places a watersource. 
We had to disable the Pets from GadgetMenu, this works everytime a Player place a Bukkit against a Pet.

**Comment by zachrocks22** [comment] 2019-07-07 22:33
Also having this issue on 1.14.3 on the latest release.

**Comment by Drynael** [comment] 2019-07-11 13:58
Same Error here:

```
[15:50:19] [Server thread/ERROR]: Could not pass event PlayerBucketEmptyEvent to PlotSquared v4.3
java.lang.IllegalArgumentException: Cannot get ID of Modern Material
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.14.3.jar:git-Paper-127]
	at org.bukkit.Material.getId(Material.java:3319) ~[patched_1.14.3.jar:git-Paper-127]
	at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onBucketEmpty(PlayerEvents.java:2382) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor69.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-127]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-127]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-127]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-127]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:396) ~[patched_1.14.3.jar:git-Paper-127]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:368) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.ItemBucket.a(ItemBucket.java:139) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.ItemBucket.a(ItemBucket.java:69) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.ItemStack.a(ItemStack.java:330) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:395) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1447) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-127]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```
Versions:
System Info: Java 1.8
Server: Paper version git-Paper-127 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
PlotSquared: PlotSquared-Bukkit-4.300
WordEdit:  Bukkit-Official (7.0.0;214af8a)
WorldGuard: Bukkit-Official (7.0.1-beta-01;14e7525)

**Comment by MattBDev** [comment] 2019-08-07 00:51
@zachrocks22 @LaVADraGoN @Drynael Can one of you please test this issue again on the latest dev build and let me know if it is still broken?

**Comment by zachrocks22** [comment] 2019-08-07 02:24
Can verify the issue is fixed as of the latest development build. (Breaking Build: 317) (Using 1.14.4 Paper)

**Closed** 2019-08-07 03:19 UTC
Labels: 1.14.x
