### ISSUE TITLE
Error when using the /plot list command

### ISSUE THREAD

**Issue by McLovinnnn** [IntellectualSites/PlotSquared#4286] opened 2024-01-03 14:21 UTC
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

When using the plot list command you get this error "java.lang.IllegalArgumentException: Tag name must match pattern [!?#]?[a-z0-9_-]*, was info.server".

Reported on the discord and was told to create this issue and include this link
https://github.com/IntellectualSites/PlotSquared/blob/main/Core/src/main/java/com/plotsquared/core/command/ListCmd.java#L467

### To Reproduce

1. /plot list all

### Expected behaviour

Print out a list of all plots on the server

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/953d45010960400ebd1e20d7f303a292

### PlotSquared Version

plotsquared-bukkit-7.3.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by DevJoey** [comment] 2024-01-11 15:24
Can confirm 

/p list all 2 works but the first page not

![image](https://github.com/IntellectualSites/PlotSquared/assets/38475631/70d970e0-d04a-4226-b3ef-3a8a1734d27f)

**Comment by OneLiteFeather** [comment] 2024-01-11 22:39
Can you replicate this on Plotsquared 7.3.2-Snapshot ? I tried and could not replicate it using 1.20.4 latest paper and fawe too

**Comment by OneLiteFeather** [comment] 2024-01-11 22:51
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/4282

**Closed by OneLiteFeather** 2024-01-11 22:51 UTC
Labels: Requires Testing, Awaiting Response
