### ISSUE TITLE
Linked Plots being forgotten

### ISSUE THREAD

**Issue by Samaru** [IntellectualSites/PlotSquared#677] opened 2015-10-18 16:55 UTC
When users merge their plots, at random occasions, such as server restarting, the plugin forgets the merged plots and unclaims them.

**Comment by divad** [comment] 2015-11-02 17:49
Can we have an update on this please?

**Comment by MattBDev** [comment] 2016-02-15 14:02
Duplicate of #801

**Closed by MattBDev** 2016-02-15 14:02 UTC
Labels: [✖] Duplicate
