### ISSUE TITLE
Problem with auto-delete plots

### ISSUE THREAD

**Issue by Espantonius** [IntellectualSites/PlotSquared#3006] opened 2021-05-06 11:18 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Without touching anything or deleting anything from files, it doesn't delete the plots that have passed X days.

This is my auto-delete plots configuration: 

```
auto-clear:
  task1:
    threshold: 1
    required-plots: -1
    confirmation: true
    days: 90
    worlds: 
    - "*"
    calibration:
      variety: 0
      variety-sd: 0
      changes: 0
      changes-sd: 1
      faces: 0
      faces-sd: 0
      data-sd: 0
      air: 0
      air-sd: 0
      data: 0
```

I have enabled the option of enabled-components.plot-expiry: true 

### To Reproduce

1. Activate and configure the days to expire the plot.
2. Claim plot and wait for the configured days.
3. View the plot information. 
4. After the limit of days it doesn't delete it.

### Expected behaviour

That the plots are deleted after the configured days.

### Screenshots / Videos

This is a plot that has expired but has not been deleted: https://prnt.sc/12kmbr7
Data player: https://prnt.sc/12kmg6f

### Error log (if applicable)

none

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fcda7c08d5674374860ebe16328ca469

### PlotSquared Version

PlotSquared version 5.13.11

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I have previously reported this problem when deleting user information.
I haven't deleted anything for a few days and it's still the same.
The plots continue to count days of disconnection but don't delete them. 

I've tried many settings and none work, even the one on the wiki: https://github.com/IntellectualSites/PlotSquared/wiki/World-reduction#plot-condensation-added-in-275-intensive

I have also tried to change the configuration seen in this area of the wiki https://github.com/IntellectualSites/PlotSquared/wiki/Plot-analysis but when start the server again it restores by default and removes some options.

**Comment by Espantonius** [comment] 2021-05-12 13:38
I have been testing and modifying things but i have not yet managed to delete the plots.
I have seen that it doesn't list the plots that have expired either: https://prnt.sc/12ufdw8

**Comment by NotMyFault** [comment] 2021-08-16 19:14
Based on the information provided, I experienced similar. `days` were set to 7 and `/plot info`'s `Seen` revealed 1w 2d and 9h.
`/plot $ start-expire/stop-expire` reported that tasks were already started _and_ halted after executing the commands.
However, I'm not very familiar with the plot expiry, but I enabled confirmation, yet I'm not too sure where and how I should confirm that.

**Comment by Malachiel87** [comment] 2021-08-21 15:08
I having the same issue, task it look already starting, no confirmation, doubt it about working

**Comment by JasonHorkles** [comment] 2021-10-02 21:20
I have plots that are very old but the plugin never asks me to keep/delete them
Here's a debug paste from a while ago https://athion.net/ISPaster/paste/view/3cca38fa59224445bb9a594ead23ed90

**Comment by PierreSchwang** [comment] 2022-01-12 07:35
Based on my testing, is it possible that the user data from bukkit was reset, but still present in PlotSquared? 
That way, the plot owner has a play time of 0, which will not trigger a plot delete. That could be the cause here too.

That wouldn't explain why its stuck, but for the other part: that some plots aren't deleted - that's the most common reason.

**Comment by NotMyFault** [comment] 2022-01-14 17:31
Pierre provides a fix for the issue, unfortunately I don't have a production server set up where I could test the fix. If someone else wants to test the fix provided, let us know (on discord), or comment on the PR with your results.

**Comment by PierreSchwang** [comment] 2022-02-04 22:28
As a fix was implemented, can you still reproduce the issue @Espantonius?

**Comment by Espantonius** [comment] 2022-02-05 12:53
I've tried the latest version and it's still the same for me.
https://prnt.sc/26p62v3
The only thing i've seen now is that when the limit of days to be deleted passes, it changes it to "unknown" and the following message appears on the console: 

`[13:46:40 WARN]: [PlotSquared] Task #31322 for PlotSquared v6.4.1-SNAPSHOT generated an exception
java.lang.IllegalAccessException: The meta data access instance has been closed
        at com.plotsquared.core.player.MetaDataAccess.checkClosed(MetaDataAccess.java:130) ~[PlotSquared.jar:?]
        at com.plotsquared.core.player.TemporaryMetaDataAccess.set(TemporaryMetaDataAccess.java:63) ~[PlotSquared.jar:?]
        at com.plotsquared.core.plot.expiration.ExpireManager.lambda$confirmExpiry$0(ExpireManager.java:151) ~[PlotSquared.jar:?]
        at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:46) ~[PlotSquared.jar:?]
        at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:51) ~[PlotSquared.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by PierreSchwang** [comment] 2022-02-05 13:03
> I've tried the latest version and it's still the same for me.
> https://prnt.sc/26p62v3
> The only thing i've seen now is that when the limit of days to be deleted passes, it changes it to "unknown" and the following message appears on the console: 
> 
> `[13:46:40 WARN]: [PlotSquared] Task #31322 for PlotSquared v6.4.1-SNAPSHOT generated an exception
> java.lang.IllegalAccessException: The meta data access instance has been closed
>         at com.plotsquared.core.player.MetaDataAccess.checkClosed(MetaDataAccess.java:130) ~[PlotSquared.jar:?]
>         at com.plotsquared.core.player.TemporaryMetaDataAccess.set(TemporaryMetaDataAccess.java:63) ~[PlotSquared.jar:?]
>         at com.plotsquared.core.plot.expiration.ExpireManager.lambda$confirmExpiry$0(ExpireManager.java:151) ~[PlotSquared.jar:?]
>         at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:46) ~[PlotSquared.jar:?]
>         at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:51) ~[PlotSquared.jar:?]
>         at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
>         at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408]
>         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-408]
>         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]`
> 
> 

Oic, that's a different issue I've addressed in #3481

**Comment by Espantonius** [comment] 2022-02-05 13:08
> > I've tried the latest version and it's still the same for me.
> > https://prnt.sc/26p62v3
> > The only thing i've seen now is that when the limit of days to be deleted passes, it changes it to "unknown" and the following message appears on the console:
> > `[13:46:40 WARN]: [PlotSquared] Task #31322 for PlotSquared v6.4.1-SNAPSHOT generated an exception java.lang.IllegalAccessException: The meta data access instance has been closed at com.plotsquared.core.player.MetaDataAccess.checkClosed(MetaDataAccess.java:130) ~[PlotSquared.jar:?] at com.plotsquared.core.player.TemporaryMetaDataAccess.set(TemporaryMetaDataAccess.java:63) ~[PlotSquared.jar:?] at com.plotsquared.core.plot.expiration.ExpireManager.lambda$confirmExpiry$0(ExpireManager.java:151) ~[PlotSquared.jar:?] at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:46) ~[PlotSquared.jar:?] at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:51) ~[PlotSquared.jar:?] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-408] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408] at java.lang.Thread.run(Thread.java:833) ~[?:?]`
> 
> Oic, that's a different issue I've addressed in #3481

I just looked again and it appears when you enter a plot that has expired days.

**Comment by PierreSchwang** [comment] 2022-02-12 20:36
> I have put the latest version and it no longer gives the error. Now i can see the expiring plots but it doesn't delete them automatically. This is the code, is it configured correctly?
> 
> ```
> # This is an auto clearing task called `task1`
> auto-clear:
>   task1:
>     threshold: -1
>     required-plots: -1
>     confirmation: true
>     days: 90
>     skip-account-age-days: -1
>     # True, if a plot should be deleted if the plot owner is unknown to the server
>     delete-if-owner-is-unknown: true
>     worlds: 
>     - "*"
>     # See: https://intellectualsites.github.io/plotsquared-documentation/optimization/plot-analysis for a description of each value.
>     calibration:
>       variety: 0
>       variety-sd: 0
>       changes: 0
>       changes-sd: 1
>       faces: 0
>       faces-sd: 0
>       data-sd: 0
>       air: 0
>       air-sd: 0
>       data: 0
> ```
> 
> [https://prnt.sc/26umcmc](url)

You'd have to set "confirmation" to "false" - Otherwise you'd have to confirm the deletion for each plot

**Comment by Espantonius** [comment] 2022-02-12 21:09
Perfect. The plots are already deleted and everything works correctly. Thanks!

**Closed** 2022-02-12 21:10 UTC
Labels: Bug, Approved
