### ISSUE TITLE
Plotsquared prevent me setting a location in the main plotworld as BedSpawn

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#3049] opened 2021-05-19 20:35 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

**Copy of https://issues.intellectualsites.com/issue/PS-163 by DevJoey** 

I am writing a custom plugin which sets the bedspawn with. player.setBedSpawnLocation(loc, true);
now i have a Location Object which is in the main plotworld. (Main PlotWorld is defined as world in server.prop and under bukkit.yml)
Now if i will set this location object to the players bedSpawnLocation() it will not set. still null. it has take hours to debug and now i know that this is a plot2 bug.

### To Reproduce

- Create a plotworld
- go to server.prop and define the plotworld under level-name
- go to bukkit.yml and define the generator (PlotSquared) for that world.
- Go to your IDE
- Write in some event to debug
- Do Location loc = new Location("yourmainplotworld", x, y,z);
- Do player.setBedSpawnLocation(loc, true); true is force, it means there must be no bed at this location.
- do Sysout(player.getBedSpawnLocation). it will be null. This occurs only, if the plotworld is the main world. I have no idea why

### Expected behaviour

-

### Screenshots / Videos

In plotworld: http://prntscr.com/v2oght Still null
In a other world: http://prntscr.com/v2ogsz All works fine

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/df65fa61f721426e9f5770472db128b3

### PlotSquared Version

5.13.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-05-22 15:03
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2998

**Closed by NotMyFault** 2021-05-22 15:03 UTC
Labels: Requires Testing
