### ISSUE TITLE
Problem with schematics

### ISSUE THREAD

**Issue by Raphy123** [IntellectualSites/PlotSquared#465] opened 2015-07-28 00:35 UTC
Hello, I love this plugin but I have a bug..

I want to add schematic on plots, that : http://zupimages.net/up/15/31/dyq7.png

But all my schem are changed ! After I have that :
http://zupimages.net/up/15/31/5gao.png

.. Why ? :(

**Comment by Sauilitired** [comment] 2015-07-28 06:31
I'm sorry, for this is incredibly funny :D Oh well, it's not intended behavior.

**Comment by Raphy123** [comment] 2015-07-28 07:56
Yes.. but.. how I can resolveee XD ?

**Comment by boy0001** [comment] 2015-07-28 09:13
If you want to test, there are some dev builds:
ci.intellectualsites.com/job/PlotSquared/

**Comment by Raphy123** [comment] 2015-07-28 09:22
The correct version is PlotSquared-Bukkit.jar ? Or the third on dev builds ?

**Comment by boy0001** [comment] 2015-07-28 09:27
PlotSquared-Bukkit.jar is for bukkit / spigot.

**Comment by Raphy123** [comment] 2015-07-28 09:27
Ok thanks Boy :) I test that !

**Comment by Raphy123** [comment] 2015-07-28 09:36
latest dev build is ok.. but she is stable ?

**Comment by boy0001** [comment] 2015-07-28 09:47
We don't know, there's not enough time to test each time we commit.

**Comment by boy0001** [comment] 2015-07-31 18:19
Fixed as of latest version.

**Closed by boy0001** 2015-07-31 18:19 UTC
Labels: [!] Bug, [?] Testing Required, [‼] high priority
