### ISSUE TITLE
Road Schematics don't work as of 823e78377bf74227f45f8d3c4722dc4beaf9c0b3

### ISSUE THREAD

**Issue by draand28** [IntellectualSites/PlotSquared#3407] opened 2021-12-27 15:28 UTC
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

The road schematics don't work at all anymore since this commit. 
I have built the plugin using all the commits between 6.1.3 and 6.1.4 and found that commit 823e78377bf74227f45f8d3c4722dc4beaf9c0b3 is the one at fault.
Otherwise, the plugin works perfectly when setting the head to the previous commit, even on Paper 1.18.1

Of course I have tried with all of the following release versions but none of them actually work.

### To Reproduce

Just try to /p createroadschematic then /p debugroadschematic plot
It won't work. Some random slabs will generate but nothing else.

### Expected behaviour

To actually be able to use road schematics.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/b040d7bd96284a2fb80572b283a823a6

### PlotSquared Version

6.1.4-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-12-27 15:32
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3405

**Closed by NotMyFault** 2021-12-27 15:32 UTC
Labels: Duplicate
