### ISSUE TITLE
PlotMe convertor not fully working

### ISSUE THREAD

**Issue by ArtificialTruth** [IntellectualSites/PlotSquared#583] opened 2015-08-28 16:54 UTC
So I started the server with no plotme jars, and it did it's thing.
However only one of my 3 worlds were converted, which were defaultplotworld.
http://pastebin.com/TzHHzMsp
I may have set the worldgenerators to PlotsSquared before starting the server, maybe that afffected the converting.

**Comment by boy0001** [comment] 2015-08-28 21:11
What information indicates that it didn't convert those worlds?
 - Does it show up in the database (send me your database if you want me to check  this)
 - Do the worlds not have the generators set?
 - If it's just the plots not showing up in game, it's likely a world generator issue, and setting the world generator in `bukkit.yml`, `plugins/Multiverse-Core/worlds.yml` and `plugins/PlotSquared/settings.yml` should resolve that.

Things that may help:
 - If it's immediately after conversion, you may need to restart the server for changes to take effect.

How many plots do you have in total?
 - The conversion says it converted 17985 plots, if this is less than the number of plots you have, let me know.

Other information that may prove useful:
 - A copy of your PlotMe and PlotSquared databases (dropbox or something?)
 - A copy of your PlotMe and PlotSquared configuration

If the above solves your problem, or you found another solution, please let me know.

**Comment by TheOnlyRealTGS** [comment] 2015-08-28 21:22
I'm pretty sure I set the generator to PlotsSquared now actually, before i started the server.
I could do /plot home # but all the homes were only in defaultplotworld.

>If it's immediately after conversion, you may need to restart the server for changes to take effect.
But why would only 1 plot world work then?

>The conversion says it converted 17985 plots, if this is less than the number of plots you have, let me know.
I have no idea.

**Comment by nickthekidNL** [comment] 2015-08-29 07:46
the same thing is working for me....i have everything setup i fixed all the generatoors...and everything the problem is...is that the data from plotme is not moving to plots squared....so on plotsquared it shows no one owns the plot but  on plot me it does.....i hope this makes sence

**Comment by TheOnlyRealTGS** [comment] 2015-09-19 11:10
Fixed the formatting in https://github.com/IntellectualSites/PlotSquared/issues/583#issuecomment-135890403

**Comment by Dreadonator** [comment] 2015-11-05 10:30
The converting did not work for me and it messed up my Server! pls fix it!!

**Comment by RedstoneFuture** [comment] 2019-01-13 01:35
Need we still a PlotMe conversion? ^^ The last Update of PlotMe was 2015.

**Comment by AeSix** [comment] 2019-01-15 17:18
I would suggest that all converters be removed from P2, and a separate converter be maintained for PlotMe, Plotz and Plots (new 1.13 plot thing, looks too basic, may want to convert to P2, may not), and possibly for P2 file to db as well. That *should* allow the old-plots code to be pretty static, and then hooking into P2 for the correct data structure for that version, using P2's storage backend. If I'm not mistaken, there's already API calls that would make this possible? 

With the advent of "Plots", the converter may need to be updated occasionally, if it's even included.

The major benefit to this would be to slim down the P2 jar and configs, removing older plugin references ceasing confusion on new admins. 

(I'm suggesting this only due to the previous reply, otherwise wouldn't as the ticket is marked closed)

**Comment by Sauilitired** [comment] 2019-01-15 17:22
@MattBDev suggested something similar. I don't see much reason to actively maintain a converter for plugins that haven't been updated in years. PloZ isn't even available for downloading anymore. But yes, it would be nice to strip version 4 of conversion code.

**Comment by Sauilitired** [comment] 2019-01-15 17:31
Is [this](https://www.spigotmc.org/resources/plots.44573/) the plugin you were talking about, @AeSix? It seems to be something entirely different.

**Comment by AeSix** [comment] 2019-01-15 22:09
oops... looks more like a griefprevention alt. sorry, i quit reading about 3 sentences in. lol

**Comment by MattBDev** [comment] 2019-01-16 21:11
We will no longer have any converters in the code. PlotMe Conversion is legacy behavior and will have limited support.

**Closed** 2019-01-16 21:11 UTC
Labels: [!] Bug
