### ISSUE TITLE
Plot merging/unmerging not working correctly

### ISSUE THREAD

**Issue by alexschrod** [IntellectualSites/PlotSquared#2375] opened 2019-05-28 11:23 UTC
**[REQUIRED] PlotSquared Version Number:** PlotSquared-4.277

**[REQUIRED] Spigot/Paper Version Number:** Paper #624 for MC 1.13.2

**[REQUIRED] Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
* worlds.yml: https://pastebin.com/QP9jrDKR
* settings.yml: https://pastebin.com/T7n3Vb82

**[REQUIRED] Description of the problem:**
Roads and plot borders do not always get correctly restored when plots are merged and unmerged, the same goes for biomes. Biomes also seem to misbehave during plots being cleared.

**Any relevant console output or screenshots:**
Video showing merging and unmerging, claiming and clearing, with the issues at hand: https://youtu.be/CjJXNw6jfi4?t=125 (content before this time is setting up the world, can be watched if interested -- world uses all default values)

**Plugins being used on the server:**
* Advanced Portals
* Chestshop
* Dynmap
* DiscordSRV
* editable signs
* enjinminecraftplugin
* essentialsX
* essentialsXChat
* essentialsXSpawn
* FastLeafDecay
* LuckPerms-Bukkit
* Matrix
* Mycommand
* NuVotifier
* PlayerHeads
* plot2dynmap
* PlotSquared
* PluginConstructorAPI
* ProtocolLIB
* serverlistMOTD
* serverrestorer
* simple egg
* skript
* u-chat
* vault
* worledit
* Worldguard

**How to replicate:** (timestamps for point in video this is done)
* Create new plot world
* Claim a plot (/plot claim) 2:13
* Claim another plot 2:22
* Merge plots 2:28
* Unmerge plots 2:35
* _Observe road not being correctly restored_
* Merge again 2:44
* Unmerge again 2:46
* _Observe road being correctly restored_
* Merge again 2:50
* Unmerge again 2:56
* _Observe road not being correctly restored again_
* Claim another plot 3:08
* Set biome to jungle 3:16
* Clear plot 3:21
* _Observe plot's biome only being partially cleared_
* Set biome to jungle 3:33
* Merge jungle plot with cleared plot 3:39
* _Observe biome where road used to be not updating_
* Merge with first plot 3:49
* _Observe once more biome where road used to be not updating_
* Set biome to jungle 3:53
* _Observe whole plot taking on the correct biome_
* Unmerge center plot 4:01
* _Observe once more roads not being correctly restored_

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue) (I found some similar ones, but they were all closed, suggesting they weren't considered to be currently active issues)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment] 2019-05-28 14:24
Does disconnecting and reconnecting to the server have any effect on any of these issues?

**Comment by alexschrod** [comment] 2019-05-29 04:09
No, this issue is not a server/client synchronization issue.

**Comment by MattBDev** [comment] 2019-05-29 14:27
Thanks. I just wanted to make sure.

**Comment by alexschrod** [comment] 2019-05-29 17:26
@MattBDev -- I've essentially fixed this issue myself now, I just need to do a little more testing and then I'll do a PR.

**Comment by alexschrod** [comment] 2019-05-30 11:41
@MattBDev Oh, I should mention, some of the biome issues I have since confirmed to be server/client related. That being said, what separates blocks that get their biome corrected right away and what takes a relog is whether or not those blocks are in a chunk that is wholly within a plot.

That is to say, it depends on whether it is this code that runs:
https://github.com/IntellectualSites/PlotSquared/blob/885d1b9d7efbf23185a4b2469c5578e19fcc5f3d/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/generator/HybridPlotManager.java#L183-L186
or if it's this:
https://github.com/IntellectualSites/PlotSquared/blob/885d1b9d7efbf23185a4b2469c5578e19fcc5f3d/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/generator/HybridPlotManager.java#L188-L189

I'm guessing Bukkit's generation forces updates to the client in a way the other code does not or cannot. What's interesting is that it's the exact same code that runs when you do `setbiome`, i.e.
https://github.com/IntellectualSites/PlotSquared/blob/04b9b67c9d993e9ac183ca321668d536f30c68dd/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/Plot.java#L906-L907
but when this runs, the client gets the update right away.

**Comment by wizjany** [comment] 2019-05-30 12:14
I was under the impression biomes could only be updated on the client if you re-send the full chunk, i.e. https://wiki.vg/Protocol#Chunk_Data
Is this not the case?

**Comment by alexschrod** [comment] 2019-05-30 14:58
@wizjany So I guess the solution would be to make Bukkit send out the whole chunk for all the chunks it modified?

**Comment by wizjany** [comment] 2019-05-30 16:02
afaik this is beyond the scope of bukkit api. unsure how P2 does it but I'd assume they're using craftbukkit/nms stuff.

**Comment by dordsor21** [comment] 2019-05-30 16:10
If I'm remembering correctly;

Using the bukkit setblock does not force a chunk update, however, regenerating the chunk effectively delete the chunk, and regenerates it according to the world's generator, which obviously does send a full chunk reload.

OR

Full chunk reloads are only sent when all columns within any chunk section are updated (as set by craftbukkit) which does not happen at the edges of plots, since roads are not regenerated in /plot clear etc etc.

It'll be one of these reasons, but I haven't the time right now to check the PS code, though I'm pretty sure it's the first reason.

**Comment by AeSix** [comment] 2019-07-31 13:27
As of Spigot 1.13.2 and P2 4.305, and WorldEdit 7:

merging plots causes:
mid-plot signs to not be removed where applicable
random strips of different biome, as seen with differently shaded grass

Unmerging plots causes:
road between plots to not be regenerated
signs are updated (this is good)


Unconfirmed issues (needs more testing):
intersections generate an empty space in the new, merged plot
borders not always being properly changed

**Comment by mindw0rm** [comment] 2019-10-11 13:53
I guess this belongs here, since all other merge bugs got marked duplicate of this one ...
Minecraft version is 1.14.4, current spigot, plotsquared version is 4.395 (HEAD of current breaking branch).

Merging a 2x2 plot in the wrong order keeps a part of the road intact; this road does _not_ belong to the plot. See the following screenshot:
![2019-10-11_15 22 12](https://user-images.githubusercontent.com/6404575/66655744-eb37b400-ec3c-11e9-8031-36eee596e3fe.png)
To replicate:
* claim top-right plot
* claim top-left plot
* on top-left plot, look to the top-right plot and merge
* claim bottom-left plot
* on bottom-left plot, look to top-left plot and merge
* claim bottom-right plot. 
* on bottom-right plot, look to bottom-left plot and merge

The road that was left out does not belong to a plot, while everything else belongs to the same plot (i.e. `/plot info shows the same ID everywhere`). This is of course independent from the actual directions, if I look to the top-right block while doing the last merge, the road between bottom-left and bottom-right would remain. 

This _might_ even be intentional, but it sure looks like a bug ;)

If you first merge the two top plots, then the two bottom plots, and then merge the two 2x1 plots, the result a proper 2x2 plot.

**Comment by AeSix** [comment] 2019-10-11 14:38
I'm fairly certain it's a bug.  I'm also fairly certain, to resolve it, and consequiently other bugs, would require a re-write of the whole thing.

**Comment by boy0001** [comment] 2019-11-12 22:41
Can't replicate with the current breaking build.

**Comment by mindw0rm** [comment] 2019-11-13 19:10
I can still replicate the behaviour described in https://github.com/IntellectualSites/PlotSquared/issues/2375#issuecomment-541073892 with the current HEAD. 

However, meanwhile I found out that you can fix it if you do another `/plot merge` while standing on the bottom-right plot and looking to the top-right (or vice versa).

**Comment by wizjany** [comment] 2019-11-13 20:30
before i unsubscribe from this thread, i'd like to point out that `HEAD` doesn't refer to any meaningful object. if you do `git checkout master~1000`, `HEAD` will point to something 1000 commits out of date of the `master` branch. and `master` isn't even the default branch on this repo.

**Comment by mindw0rm** [comment] 2019-11-13 20:44
@wizjany  you are of course right (well, I don't know why you mention `master`, when HEAD without mentioning of a branch should be understood as referring to the default branch. `master` is in no way special except that it is the default branch name), so I edited my comment.
But I'm pretty sure everyone understood it anyway. 

happy nitpicking elsewhere :bye:

**Comment by boy0001** [comment] 2019-11-13 23:48
Behavior in #2375 is as expected. Use `/plot merge all` if you want to merge fully. I was referring to the unmerge bug in the original post.

**Comment by AeSix** [comment] 2019-11-14 02:09
I'm setting this to "testing required" and removing "can't replicate" and "bug" as it may be resolved.
Please test using PlotSquared 4.40 (or newer) and post results please.  When we get confirmation that this is resolved, the ticket can be closed, otherwise if we get confirmation that it's still broken, we'll need more information - i.e. a new /debugpaste

**Comment by Sauilitired** [comment] 2020-05-14 12:40
Cannot be replicated in version 5.

**Closed by Sauilitired** 2020-05-14 12:40 UTC
Labels: 1.13+, Spigot, [?] Testing Required, [‼] high priority
