### ISSUE TITLE
Plots delete is being reverted (plot delete and expiry task)

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1476] opened 2016-12-11 20:02 UTC
Plots are sometimes not being deleted, they are getting reset back to their owner after a server restart
I am using plotsquared as of https://github.com/IntellectualSites/PlotSquared/commit/7b1c4a504273d45131a568a30727e280c5487dab and paperspigot 1.10.2

The most recent report: 
Hey_Itzpinky plot that they claimed yesterday and built on
https://gyazo.com/ae8b47059c373bd8b007b5fb103f18e3

was set back to the previous owner https://gyazo.com/cabd920ce7f1488479aeb36827fb8d43
masterswordgod was last seen on the server 3 months ago on the same plot, (90 days of inactivity is what i have my plot expiry task set to)

I searched the logs for -9;-24 and got this
```
[04:13:25] [Server thread/INFO]: [ExpireManager] Deleted expired plot: plot_normal;-9;-24 : 1 - 1
[19:52:25] [Server thread/INFO]:  - Setting owner: plot_normal;-9;-24 -> HeyItz_Pinky
[19:52:25] [Server thread/INFO]:  - Correcting 1 trusted for: plot_normal;-9;-24
```

so this might be possibly wrong or not working or who knows what.

I had to manually change the owner to fix this for the player

This also happened with /plot delete, I deleted a plot, restarted the server, and after a restart the plot was still owned by the previous owner. Only thing relevant in logs was 
``` 
Plot was deleted: null;149;695// TODO implement this when sure safe
```

**Comment by MattBDev** [comment] 2016-12-11 20:43
I'm not sure what was intended for that piece of missing code.....It was created around last year by @boy0001

**Comment by PhanaticD** [comment] 2017-01-08 22:00
this still happens

player1: /plot delete
player2: /plot auto
server restart
player1 is owner again of the plot he deleted

**Comment by xion87** [comment] 2017-03-12 16:52
Is not fixed, and cause multiple people to have plots

**Comment by boy0001** [comment] 2017-03-14 15:15
@MattBDev 
That code is responsible for correcting any discrepancies between what data the server has and the database. The reason why deletion is commented out is that there are valid reasons for the server not knowing about some plots in the database e.g. A world being unloaded.

**Comment by xion87** [comment] 2017-03-15 00:35
it cause issue also with merged plots, data are not saved at server shutdown to database
I write here what i see:
![immagine](https://cloud.githubusercontent.com/assets/3611852/23928381/b0913e64-091f-11e7-932f-817aaadd7c59.png)

**Comment by xion87** [comment] 2017-03-16 00:21
More info, i deleted the duplicate  values mantaing news ones and seem to fix all plots issue.
@boy0001 
i suggest for fix i suggest to remove all duplicate values manitaing only the ones with high number id

**Closed** 2017-03-16 03:15 UTC

**Comment by boy0001** [comment] 2017-03-16 03:16
@xion87 
Changing how to handles the loading when there are duplicates might fix it.
