### ISSUE TITLE
Plots "unknown" owner

### ISSUE THREAD

**Issue by SliderKP** [IntellectualSites/PlotSquared#1147] opened 2016-06-02 09:49 UTC
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/kunikiseyu

**Description of the problem:**
my users lose their plots that become of "unknown " if the plot purge my active users lose their plots , the signs say "unknown " does not happen always happens occasionally , why is this happening? and I can explain how to do that if a user does not modify any block of the plot becomes deleted ? because they do not understand about plot analysis , I'm from Argentina and my English is not very good , I want to delete all plots that say " unknown" and also those which are unchanged , I hope they can resolve this error
**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment] 2016-06-02 13:56
Please make sure to follow the steps listed in the template before filing a bug report in the future. This report is a duplicate of #781

**Closed by MattBDev** 2016-06-02 13:56 UTC

**Comment by SliderKP** [comment] 2016-06-02 15:10
what i can do tu fix this... ? the other report is not solved bro.

**Comment by manuelgu** [comment] 2016-06-02 15:16
@SliderKP This is a duplicate report so #781 is the place to discuss things related to the issue. There is no fix for it at the moment. It is under investigation.

**Comment by SliderKP** [comment] 2016-06-04 15:01
@manuelgu , thanks for your reply, i wait for a fix to this.
