### ISSUE TITLE
Setting flag "server-plot" to true doesn't update sign with the server name

### ISSUE THREAD

**Issue by Leomixer17** [IntellectualSites/PlotSquared#2430] opened 2019-07-19 18:22 UTC
# Bug report template 
**[REQUIRED] PlotSquared Version Number:** 
[P2] >> PlotSquared (Version: PlotSquared-4.299)

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-129 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

**How to replicate:** 

1. Claim a plot
2. Set flag "server-plot" to true
3. The sign still shows the name of the real owner

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-07-21 13:18
@MattBDev is this actually expected behavior, using server name on the sign, I mean?

@Leomixer17  You have verified your server name is set?

**Comment by Leomixer17** [comment] 2019-07-21 13:33
@AeSix Yes, indeed the title shown when entering the plot is correct

**Comment by AeSix** [comment] 2019-08-10 16:23
I tested this with Spigot 1.13.2 & P2 4.318.
I get the same behavior as described.  

I'm still uncertain if this is a bug, or if the name on the sign is to reflect the player who claimed the plot, as this is a flag, and not a traditional change of ownership for the plot. 

Perhaps @Sauilitired or @MattBDev  can clarify on this issue.

**Comment by Sauilitired** [comment] 2019-08-12 17:52
The title is shown correctly because the name is sort of "overriden" while the flag is set. I never even considered updating the signs, when this flag was added. It might be a good addition, although I would certainly be interested in hearing other thoughts on this.

**Comment by AeSix** [comment] 2019-08-12 18:00
I personally think it's a good idea to track/maintain/display the /proper/ owner of the plot, be it with sign, as a new line in /p info, or something.  

Regarding the sign not displaying the owner as "server" causing confusion, simply removing the sign works.  I don't know if that breaks anything, but if it does, the sign shouldn't be allowed to be removed.  

As this ticket addresses expected behavior as designed, I'm closing it, and creating a suggestion ticket, linking to this ticket for reference. 

@Leomixer17 to be clear, this isn't a bug, it's as designed.

**Closed by AeSix** 2019-08-12 18:00 UTC
Labels: 1.13.x, 1.14.x, Spigot
