### ISSUE TITLE
Interacting with sweet_berry_bush

### ISSUE THREAD

**Issue by Lusteroth** [IntellectualSites/PlotSquared#2612] opened 2019-11-29 19:01 UTC
# NOTICE:
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```
 
**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**
 
**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**
 
**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!
 
# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

 https://athion.net/ISPaster/paste/view/25246bb7b2934954870e8c6f19f9b4a3 #2588 

 

 
 
 
### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*
 
### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
 
### Server build info:

``` Paper 1.14.4 Build 226 ```
 
### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*:  WorldEdit 7.0.1 (1.13.2 - 1.14.4)
 
### Description of the problem:

 
Players are able to harvest `sweet_berry_bush`es on plots where they don't have any permissions to do it.
 
### How to replicate:

 
Interact with a `sweet_berry_bush` on other plots.
 
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
 
 
### Other plugins being used on the server:

 
WorldEdit, WorldGuard
 
### Relevant console output, log lines, and/or screenshots:

 
https://pastebin.com/94YyCPva
 
### Additional relevant comments/remarks:

 
# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment] 2019-11-29 23:01
Do they get berries without being able to break the bush?

**Comment by N0tMyFaultOG** [comment] 2019-11-29 23:05
Looking on the latest entry of their debugpaste, it looks like a possible duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2588

**Comment by Lusteroth** [comment] 2019-11-29 23:06
Yes. (The bush hasn't berries anymore)

**Comment by Lusteroth** [comment] 2019-11-29 23:14
> 
> 
> Looking on the latest entry of their debugpaste, it looks like a possible duplicate of #2588

Debugpaste is the same, correct. In #2588 I reported an interaction bug with *_wall_signs, here I'm reporting a very similar bug with the bushes. Probably both errors have the same cause.

**Comment by MattBDev** [comment] 2019-11-29 23:25
It is a duplicate of #2588 and I am working on it.

**Closed by MattBDev** 2019-11-29 23:25 UTC
Labels: [?] Testing Required
