### ISSUE TITLE
Error when attempting to download a plot

### ISSUE THREAD

**Issue by Segysmundo** [IntellectualSites/PlotSquared#2363] opened 2019-05-19 16:03 UTC
**PlotSquared Version Number:** 4.286
**Spigot/Paper Version Number:** Paper 1.13.2-b624

**Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
[worlds.yml](https://pastebin.com/kFn1bfZ4)
[settings.yml](https://pastebin.com/fLunxsts)

**Description of the problem:** When trying to download a plot with **/plot download** an error shows up in console and the download never occurs.

**Any relevant console output or screenshots:** [Error](https://pastebin.com/LNbkM18u)

**Plugins being used on the server:** None relevant to the error I believe.

**Checklist**:
- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-05-19 21:37
@boy0001 not an issue with the backend service, is it?

**Comment by SeDark** [comment] 2019-05-21 21:24
Same :/

**Comment by jewome62** [comment] 2019-07-30 23:32
Always same problem

```
[01:16:07] [Server thread/INFO]: jewome62 issued server command: /plot download
[01:16:09] [Craft Scheduler Thread - 35/WARN]: com.sk89q.worldedit.regions.CuboidRegion$3$1: End of iterator
[01:16:09] [Craft Scheduler Thread - 35/WARN]: [PlotSquared] Plugin PlotSquared v4.304 generated an exception while executing task 16656
java.lang.IllegalArgumentException: Invalid tag classs (com.sk89q.jnbt.CompressedSchematicTag).
	at com.sk89q.jnbt.NBTUtils.getTypeCode(NBTUtils.java:116) ~[?:?]
	at com.sk89q.jnbt.NBTOutputStream.writeNamedTag(NBTOutputStream.java:92) ~[?:?]
	at com.boydti.fawe.regions.general.plot.FaweSchematicHandler$1.run(FaweSchematicHandler.java:129) ~[?:?]
	at com.boydti.fawe.regions.general.plot.FaweSchematicHandler$1.run(FaweSchematicHandler.java:121) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.MainUtil.lambda$upload$0(MainUtil.java:153) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-641]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-641]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-641]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

```
31.07 01:30:01 [Multicraft] jewome62 ran command: version
31.07 01:30:01 [Server] INFO This server is running Paper version git-Paper-641 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
31.07 01:30:01 [Server] INFO Previous version: git-Paper-639 (MC: 1.13.2)
31.07 01:30:01 [Server] INFO Checking version, please wait...
31.07 01:30:07 [Server] INFO You are running the latest version
31.07 01:30:09 [Multicraft] jewome62 ran command: plot version
31.07 01:30:09 [Server] INFO [P2] >> PlotSquared (Version: PlotSquared-4.304)
31.07 01:30:09 [Server] INFO [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
31.07 01:30:09 [Server] INFO [P2] >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki
```
![image](https://user-images.githubusercontent.com/472429/62172575-f9ab4a80-b332-11e9-89c6-cfea587c685e.png)

**Comment by AeSix** [comment] 2019-07-31 11:26
Does this occur when using Spigot? It seems both errors are generated with Paper.

I have confirmed with P2 4.305, the command is /p downloadplot 
However, I have this pointed to my own domain, and have it disabled as I current do not have the server setup to accept plot uploads, and so I receive a different error. 

Using Spigot 1.13.2, P2 4.305
II receive a socket error due to the address not being valid for this use.  However, I would have expected to have the above error as it seems to be in the pre-sending cycle, and erroring before the game attempts to contact the hosting server. 

Therefore, I cannot test any further.

**Comment by jewome62** [comment] 2019-08-07 23:44
> 08.08 01:40:17 [Server] WARN [PlotSquared] ====================================================
08.08 01:40:17 [Server] WARN [PlotSquared]  PlotSquared works better if you use Paper 
08.08 01:40:17 [Server] WARN [PlotSquared]  as your server software. 
08.08 01:40:17 [Server] WARN [PlotSquared]   

¯\_(ツ)_/¯

I have try with Spigot I have same problem
```
08.08 01:42:43 [Server] INFO This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
08.08 01:42:43 [Server] INFO This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
```

```
[01:42:33] [Craft Scheduler Thread - 0/WARN]: [PlotSquared] Plugin PlotSquared v4.309 generated an exception while executing task 363
java.lang.IllegalArgumentException: Invalid tag classs (com.sk89q.jnbt.CompressedSchematicTag).
	at com.sk89q.jnbt.NBTUtils.getTypeCode(NBTUtils.java:116) ~[?:?]
	at com.sk89q.jnbt.NBTOutputStream.writeNamedTag(NBTOutputStream.java:92) ~[?:?]
	at com.boydti.fawe.regions.general.plot.FaweSchematicHandler$1.run(FaweSchematicHandler.java:129) ~[?:?]
	at com.boydti.fawe.regions.general.plot.FaweSchematicHandler$1.run(FaweSchematicHandler.java:121) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.MainUtil.lambda$upload$0(MainUtil.java:153) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by N0tMyFaultOG** [comment] 2019-08-07 23:48
Fawe is the issue, should work fine with regular WorldEdit.

**Comment by AeSix** [comment] 2019-08-10 14:56
As this is an issue with FAWE, and a ticket has been opened there, I'm closing this ticket.

This ticket is referenced in the FAWE ticket.

**Closed by AeSix** 2019-08-10 14:56 UTC
Labels: 1.13.x
