### ISSUE TITLE
Cap bypass causes the server to lag.

### ISSUE THREAD

**Issue by ch4ika** [IntellectualSites/PlotSquared#4338] opened 2024-02-14 11:48 UTC
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

https://www.youtube.com/watch?v=5mlM_YMHm64

The whole thing is used to circumvent the limit and overfill plots with entities, which then causes the server to lag.
Players take advantage of this to overload a server with entities so that server performance suffers.

The whole thing only works on a merged plot.
The entities do not count this as a cap on the property but as a street.

### To Reproduce

1. Fill the entity cap.
2. Stand between the merged plot where the street used to be.
3. Place any entity and make it move around.
4. Then the cap resets to 0 every time and so it is possible to have infinite entities.

### Expected behaviour

Once you have reached the cap, it should no longer be possible for entities to spawn or be set.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/be9bf29257fe417886b598ed4d1cf227

### PlotSquared Version

7.2.2-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment] 2024-02-14 15:31
Please check your debugpaste, there is an error with the configuration that might is the real issue. Try to find the error and retry if the behaviour is still the same

**Comment by OneLiteFeather** [comment] 2024-02-14 16:30
You should probably fix also the "not existent world" error too in your log regarding your database and retry.

**Comment by Tamikaschu** [comment] 2024-02-14 16:34
can confirm with: [](https://athion.net/ISPaster/paste/view/da08fe2fa57a4a16808e9db8fd5a6194)

**Comment by ch4ika** [comment] 2024-02-14 16:38
I repeat again, it has nothing to do with the config. If you read the latest.log correctly, you would see that the config was reloaded several times.

**Comment by OneLiteFeather** [comment] 2024-02-14 16:40
Please upload the original file worlds.yml and we can take a proper look what is creating the exception

**Comment by OneLiteFeather** [comment] 2024-02-14 16:41
> can confirm with: https://athion.net/ISPaster/paste/view/da08fe2fa57a4a16808e9db8fd5a619

Somehow this debugpaste is empty

**Comment by Tamikaschu** [comment] 2024-02-14 16:42
> > can confirm with: https://athion.net/ISPaster/paste/view/da08fe2fa57a4a16808e9db8fd5a619
> 
> Somehow this debugpaste is empty

ive just edited it to https://athion.net/ISPaster/paste/view/da08fe2fa57a4a16808e9db8fd5a6194

**Comment by ch4ika** [comment] 2024-02-14 16:48
https://athion.net/ISPaster/paste/view/7bddc50c8f3f46c5b05cbae70884470d

**Comment by Tamikaschu** [comment] 2024-02-14 16:54
https://www.youtube.com/watch?v=z6S3MxM3Ryg
plotcap was manually set to 10 entities on this plot

**Comment by ch4ika** [comment] 2024-02-14 17:05
Our users are spamming villagers and crashing the server due to that. We would be looking forward to finding a solutions to that otherwise we would have to disable mob spawning completely.

![image](https://github.com/IntellectualSites/PlotSquared/assets/104507238/a4981156-9369-4613-b50c-88264fbacad9)

**Comment by OneLiteFeather** [comment] 2024-02-14 17:05
@ch4ika Is there a so called "_broken" worlds.yml, if yes please send it here as a file

**Comment by TheMeinerLP** [comment] 2024-02-14 17:08
> Our users are spamming villagers and crashing the server due to that. We would be looking forward to finding a solutions to that otherwise we would have to disable mob spawning completely.
> 
> ![image](https://private-user-images.githubusercontent.com/104507238/304816330-a4981156-9369-4613-b50c-88264fbacad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MzA3MzIsIm5iZiI6MTcwNzkzMDQzMiwicGF0aCI6Ii8xMDQ1MDcyMzgvMzA0ODE2MzMwLWE0OTgxMTU2LTkzNjktNDYxMy1iNTBjLTg4MjY0ZmJhY2FkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxNzA3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDQ1ZjMzYjE5OTVmZmQxOGZjNTc2NjFjNmI4NjQ0Mzk4YjY2ZjE1ZDg4Y2RkMTg2NzRkMWU4YWIyNGNhNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hzr57KLbSjcSo2CnSKMkS001IPye96jW3l6J4r7xiSk)

The plot cap is related to claimed plots and additional. 
Means if you have 5 Plots and per each plot a cap of 30 Entities. You have the possibility of 30 * 5 = 150 Entities.

**Comment by Tamikaschu** [comment] 2024-02-14 17:30
> The plot cap is related to claimed plots and additional. Means if you have 5 Plots and per each plot a cap of 30 Entities. You have the possibility of 30 * 5 = 150 Entities.

The Plotcap would still be displayed wrong then. Furthermore can the "possible amount of entities" only be reached by spawning them where the road uses to be and the entity is moving between the plots. If you try to spawn them regularly on a normal side of the plot, the plotcap will prevent them from spawning even before the "possible amount of entities" is reached. As you can see here: https://youtu.be/erzWdK8fW_8 the debug shows that the plotcap is indeed reaches. Still you are able to spawn more entities under the given conditions

**Comment by TheMeinerLP** [comment] 2024-02-14 17:43
Before we continue here, the original issue has a lot of errors in the log. If they have not yet been fixed. I will not invest any more time in it. Based on the configuration given in the DebugPaste. All mob caps with lines are observed. 

Config Parsing Error: https://mclo.gs/lQ3pRDc
Database Error: https://mclo.gs/0KymN2j

**Please fix this before we continue here.**

**Comment by ch4ika** [comment] 2024-02-14 18:07
I set up a new server and was able to reproduce the same thing there.
https://www.youtube.com/watch?v=KCqGM4RalOE&feature=youtu.be

I even noticed that armor stands were completely ignored.
https://www.youtube.com/watch?v=0YuhzfdSx0I

https://athion.net/ISPaster/paste/view/18dff0567af4415c8287d67c3c6d2d8c
7.2.2-SNAPSHOT

**Comment by TheMeinerLP** [comment] 2024-02-14 18:20
I can replicate this with Armor Stand. Not with other entities. According to the statement of the issue, the issue is incorrect because the specification is for all entity types. 

See:
> To Reproduce
Fill the entity cap.
Stand between the merged plot where the street used to be.
Place any entity and make it move around.
Then the cap resets to 0 every time and so it is possible to have infinite entities.

I see that you have added a different version locally than in the original issue. Which falsifies the test procedures and does not allow replications.

**Comment by Tamikaschu** [comment] 2024-02-14 18:28
> I see that you have added a different version locally than in the original issue. Which falsifies the test procedures and does not allow replications.

I dont quite understand the point u are trying to make. The same issue still persists on both of our localhost servers on default settings. It is described and shown sufficient in all of the videos yet you are still consisting on fixing unrelated problems in the original issue. Would u prefer closing this issue and creating one with the information given here: https://github.com/IntellectualSites/PlotSquared/issues/4338#issuecomment-1944342208

**Comment by TheMeinerLP** [comment] 2024-02-14 18:35
To make this a little more transparent and clearer. 
We take the Worlds.yml like Settings.yml from the debug paste. Start a server with this configuration and the latest version of the plugin and Fawe. Follow the steps from the video / issue and see if we can replicate this 1 to 1. 
We leave all other changes the same from Plotsquared, i.e. no extra DB etc. to exclude inconsistencies from external influences. 

If the bug occurs there, it is valid. If it differs from the description etc. There is feedback. If it cannot be reproduced, it is usually rejected. 

I would like to briefly note that fixing these bugs and maintaining issues happens in spare time and especially fixing the bugs takes a lot of time, so we check very carefully whether it can be reproduced. 

At least from my point of view of the positions and how I work on the bugs, from the team it may be that it is done differently.

**Closed** 2024-02-14 18:36 UTC
Labels: Requires Testing, Invalid
