### ISSUE TITLE
Plotsquared islands instead of squares

### ISSUE THREAD

**Issue by 6uze** [IntellectualSites/PlotSquared#4151] opened 2023-08-31 20:36 UTC
### What feature do you want to see added?

I would like to do in the plugin that instead of squares i want do islands. I must have a world or it can be configured somehow?sorry That I posted a topic in this section but I don't know how to give n another that for example help.

### Are there any alternatives?

.

### Anything else?

.

**Comment by dordsor21** [comment] 2023-09-30 14:49
Duplicate of #3318

**Closed by dordsor21** 2023-09-30 14:49 UTC
Labels: Enhancement
