### ISSUE TITLE
plot debugexec analyze not Work

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/PlotSquared#2424] opened 2019-07-14 21:43 UTC
**[REQUIRED] PlotSquared Version Number:** PlotSquared 4 Build 299

**[REQUIRED] Spigot/Paper Version Number:** Paper 1.13.2 Build 633

**[REQUIRED] Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
[config-file.zip](https://github.com/IntellectualSites/PlotSquared/files/3390450/config-file.zip)

**[REQUIRED] Description of the problem:** 
Try the command `/plot debugexec analyze`

**Any relevant console output or screenshots:**
```
14.07 23:31:07 [Server] INFO jewome62 issued server command: /plot debugexec analyze 
14.07 23:31:07 [Server] WARN [PlotSquared] Plugin PlotSquared v4.299 generated an exception while executing task 1677641 
14.07 23:31:07 [Server] INFO java.lang.NullPointerException: null 
14.07 23:31:07 [Server] INFO at com.github.intellectualsites.plotsquared.plot.generator.HybridGen.generateBlockBucketChunk(HybridGen.java:42) ~[?:?] 
14.07 23:31:07 [Server] INFO at com.github.intellectualsites.plotsquared.plot.object.PlotArea.getBlockBucketChunk(PlotArea.java:121) ~[?:?] 
14.07 23:31:07 [Server] INFO at com.github.intellectualsites.plotsquared.bukkit.util.BukkitHybridUtils.lambda$analyzeRegion$4(BukkitHybridUtils.java:78) ~[?:?] 
14.07 23:31:07 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-637] 
14.07 23:31:07 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-637] 
14.07 23:31:07 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-637] 
14.07 23:31:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?] 
14.07 23:31:07 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?] 
14.07 23:31:07 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
```
**Plugins being used on the server:**
Plugins (20): AdvancedPortals, BestViewDistance*, BungeeTabListPlus*, DisableJoinMessage*, FastAsyncVoxelSniper, FastAsyncWorldEdit, FlySpeed*, ForceField*, LOTM-ForceGameMode*, LuckPerms, Multiverse-Core, PermBridge*, PlaceholderAPI*, PlotSquared, PremiumVanish, ProtocolLib*, SpawnJoin*, Vault, ViaVersion*, WorldEdit 
**How to replicate:** 
Go on plot and make `/plot debugexec analyze`

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment] 2019-07-19 00:37
Duplicate of #2319

**Closed by MattBDev** 2019-07-19 00:37 UTC
