### ISSUE TITLE
Unable to merge plots as Admin

### ISSUE THREAD

**Issue by burdoto** [IntellectualSites/PlotSquared#2331] opened 2019-04-20 10:59 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 
Currently unable to post a paste link; see #2332

**Description of the problem:** 
Unable to merge plots for my users.
I do not want my users to have access to `/plot merge`; I want them to talk to me for merged plots. But I cannot merge two plots if I do not own any of them, even though I have `*` permission and OP (lv 4).
![grafik](https://user-images.githubusercontent.com/42473485/56456387-d3593480-636b-11e9-9226-5e4ecb1fff8b.png)

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link (-> Unable to do so)
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment] 2019-05-01 16:33
Unclaimed plots cannot be merged.

**Closed by dordsor21** 2019-05-01 16:33 UTC

**Comment by burdoto** [comment] 2019-05-01 17:04
This also applies for two plots owned by other players.

**Comment by AeSix** [comment] 2019-05-01 18:56
To merge two plots "A" and "B" - both "A" and "B" must be owned by the same person.  If "A" is owned by you, and "B" is owned by me - they cannot be merged.  If "A" is owned by you, and "B" is unowned - the plots cannot be merged.  There is a very simple resolution to this - claim "A" and then claim "B", then merge.  If "B" is owned by someone else, then you need to set the owner for "B" to the same owner as "A" before you can merge them.

**Comment by burdoto** [comment] 2019-05-02 05:40
Good to know, I will try this. Thanks!

**Comment by TNTUP** [comment] 2019-05-07 19:30
I was able to merge players plots into others by request in 1.12.2, but since in 1.13.2 I cannot merge them anymore. Something changed between 1.12.2 vs. 1.13.2? Sorry by commenting on an already closed issue, found it by searching "merge" plot issues

**Comment by AeSix** [comment] 2019-05-07 19:47
I believe this change was done by design as there were too many issues (technical, in the plugin - and administrative, on the servers)

Since this was a manual process anyways, it would not be that difficult to change the owner name on one of the plots, merge and add the second owner as trusted.

**Comment by TNTUP** [comment] 2019-05-07 20:10
that would be a mess if a player wants to merge a plot with a friend and changing owners everytime if someone requests it, not an issue on 1.12.2 but on 1.13.2 does. Just've have noticed this issue was about merging plots to unclaimed ones, but I meant claimed ones. Sorry, should've make my own issue
