### ISSUE TITLE
Unknown Error 

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2614] opened 2019-11-30 18:13 UTC
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/cf85330c1407453181ecd3a13adb8c84

### Server type:
**select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

I get a wierd error i dont know how to replicate.

### How to replicate:

I dont know its random
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

Only MultiVerse WE and p2
### Relevant console output, log lines, and/or screenshots:

https://hasteb.in/miyenapi.sql

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment] 2019-11-30 18:14
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2588

**Closed by N0tMyFaultOG** 2019-11-30 18:14 UTC
Labels: [?] Testing Required
