### ISSUE TITLE
Plotsquared support for fabric

### ISSUE THREAD

**Issue by ACG94** [IntellectualSites/PlotSquared#4161] opened 2023-09-14 02:00 UTC
### What feature do you want to see added?

Would it be possible to have fabric compatibility added to plotsquared? Worldedit supports fabric. 
A lot of other mods/plugins now support fabric as well. 

Would be nice to have fabric support; a lot of servers are switching from spigot/paper to fabric servers, and there’s no mod/plugin which compares to plotsquared.

### Are there any alternatives?

Make plotsquared for fabric… 

Just would be nice to communities with multiple servers where they use fabric, they then wouldn’t have to have a seperate server running spigot for plotsquared

**Comment by NotMyFault** [comment] 2023-09-14 10:21
Duplicate of #2236

**Closed** 2023-09-14 10:21 UTC
Labels: Enhancement
