### ISSUE TITLE
vanilla generation separated by streets

### ISSUE THREAD

**Issue by STEINTALCHRIS** [IntellectualSites/PlotSquared#3322] opened 2021-11-04 23:56 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When creating a plot world according to Vanilla generation, i.e. a normal survival world which has plots separated by streets, the map cannot be generated without errors.
if the map finally works after a few reboots due to errors, further errors occur. Claimed plots are not reset when deleting. merged plots are not merged correctly when merging (the street is sometimes not removed at all) and also because when deleting the problem that the plots are not set back to the original. Even the streets are not restored with merged plots, streets without soil are created, margins are set incorrectly. 

### To Reproduce

[P2] Usage: /plot setup <value>
[P2] What generator do you want?
 - PlotSquared (Default Generator)
[P2] What world type do you want?
 - normal - Standard plot generation
 - augmented - Plot generation with terrain
 - partial - Vanilla with clusters of plots
[P2] What terrain would you like in plots?
 - ROAD - Terrain separated by roads
 - ALL - Entirely vanilla generation
[Step 1] Plot height - Expecting: INTEGER Default: 62
[Step 2] Plot width - Expecting: INTEGER Default: 42
[Step 3] Plot block (Block(s) to fill the plot with from Y0 to the defined plot height (Set in a previous step)) - Expecting: BLOCK_BUCKET Default: minecraft:stone
[Step 4] Whether a layer of blocks should be put on top of the plot block - Expecting: BOOLEAN Default: true
[Step 5] Plot floor block (One layer of blocks put on top of the plot block) - Expecting: BLOCK_BUCKET Default: minecraft:grass_block
[Step 6] Top wall block (Block(s) shaping the border of an unclaimed plot) - Expecting: BLOCK_BUCKET Default: minecraft:stone_slab
[Step 7] Wall block (claimed) (Block(s) shaping the border of a claimed plot) - Expecting: BLOCK_BUCKET Default: minecraft:sandstone_slab
[Step 8] Road width - Expecting: INTEGER Default: 7
[Step 9] Road height - Expecting: INTEGER Default: 62
[Step 10] Road block - Expecting: BLOCK_BUCKET Default: minecraft:quartz_block
[Step 11] Wall filling block (Block(s) been put under the plot border down to Y1) - Expecting: BLOCK_BUCKET Default: minecraft:stone
[Step 12] Wall height - Expecting: INTEGER Default: 62
[Step 13] Whether a bedrock layer under the plot should be generated or not - Expecting: BOOLEAN Default: true
[P2] What do you want your world to be called?
CONSOLE: Starting creation of world 'testwelt'...
[Multiverse-Core] Loading World & Settings - 'testwelt' - Env: NORMAL - Type: NORMAL
[PlotSquared/PlotSquared] Detected world load for 'testwelt'
[P2] Area flags: []
[P2] Road flags: []
[PlotSquared/HybridPlotWorld] - schematic: false
[PlotSquared/HybridPlotWorld] - Dumping settings for ClassicPlotWorld with name testwelt
[PlotSquared/HybridPlotWorld] -- road_schematic_enabled = false
[PlotSquared/HybridPlotWorld] -- plot_schematic = false
[PlotSquared/HybridPlotWorld] -- plot_schematic_height = -1
[PlotSquared/HybridPlotWorld] -- path_width_lower = 4
[PlotSquared/HybridPlotWorld] -- path_width_upper = 133
[PlotSquared/HybridPlotWorld] -- schem_y = 62
[PlotSquared/HybridPlotWorld] -- road_height = 70
[PlotSquared/HybridPlotWorld] -- plot_height = 62
[PlotSquared/HybridPlotWorld] -- wall_height = 70
[PlotSquared/HybridPlotWorld] -- main_block = *
[PlotSquared/HybridPlotWorld] -- top_block = *
[PlotSquared/HybridPlotWorld] -- wall_block = stone_slab
[PlotSquared/HybridPlotWorld] -- claimed_wall_block = sandstone_slab
[PlotSquared/HybridPlotWorld] -- wall_filling = stone
[PlotSquared/HybridPlotWorld] -- road_block = quartz_block
[PlotSquared/HybridPlotWorld] -- plot_bedrock = true
[PlotSquared/HybridPlotWorld] -- place_top_block = false
[PlotSquared/HybridPlotWorld] -- plot_width = 128
[PlotSquared/HybridPlotWorld] -- road_width = 9
[PlotSquared/HybridPlotWorld] -- road_offset_x = 0
[PlotSquared/HybridPlotWorld] -- road_offset_z = 0
[PlotSquared/HybridPlotWorld] -- size = 137
[PlotSquared/PlotSquared] - generator: null>PlotSquared
[PlotSquared/PlotSquared] - plot world: testwelt
[PlotSquared/PlotSquared] - plot area manager: com.plotsquared.core.generator.HybridPlotManager@76219d82

### Expected behaviour

Buy 4 plots, merge them, edit this big plot and the street that is still there. do / p delete to delete the plot

### Screenshots / Videos

![2021-11-05_00 43 04](https://user-images.githubusercontent.com/60184969/140435537-7880514c-cedf-408c-aeab-0bcfa35a4693.png)
![2021-11-05_00 43 58](https://user-images.githubusercontent.com/60184969/140435545-7f71c27f-009d-4e2c-bc60-edb493753933.png)
![2021-11-05_00 44 45](https://user-images.githubusercontent.com/60184969/140435549-80941ae7-4f7b-452b-81b7-c1df2b359c41.png)
![2021-11-05_00 45 34](https://user-images.githubusercontent.com/60184969/140435568-5f538d8b-c84a-427e-a5af-799b546e5598.png)
![2021-11-05_00 46 37](https://user-images.githubusercontent.com/60184969/140435577-c8f37e14-f628-4146-a922-78fa3364d472.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/59bcd918a69942eda9f89a7859fcf3a4

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8434378ec947447f81e20d1a86b7ec6c

### PlotSquared Version

PlotSquared version 6.1.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

i have some players who are looking forward to playing in a vanilla world that has plots separated by streets, unfortunately the error has existed for some time. I would be happy to receive information if something happens to the error or how to fix it.

furthermore my english is not so good. therefore i have translated some sections with the google translator. if problems arise with communication, I like to try to express myself differently in order to better explain what I mean
Greetings Christian

**Comment by NotMyFault** [comment] 2021-11-05 00:24
> Claimed plots are not reset when deleting

That is a duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2631.

The errors you provided appear to boil down to an improper setup. Chunk generation is an expensive task you do before letting any players on the server, them moving around to load and generate chunks is way more expensive than doing it before. Tools like Chunky can help you there to pregenerate a map.
Using proper startup flags can also help your server to run better, see https://startmc.sh/

**Closed** 2021-11-17 16:28 UTC
Labels: Question
