### ISSUE TITLE
"/plot list shared <name>" down't show plots there othere player are shared

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2343] opened 2019-04-25 16:15 UTC
`Syntax: "/plot list <forsale|mine|shared|world|top|all|unowned|unknown|player|world|done|fuzzy <search...>> [#]"`

If I use "/plot list shared Testplayer" I can't get the plots where the Testplayer is added or trusted. - I get the same list like "/plot list shared" This would be good, If the staff would like check the allowed plots of a player.

**Checklist**:

- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
(tested with 1.12.2 "PlotSquared-17.12.7-6c06e48-1944" and the last P² version for 1.13.2 "PlotSquared-19.4.6-5d515b3-221"
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment] 2019-05-01 16:28
The 1.12.2 version you tested with is a year and a half old, and the "last P² version for 1.13.2" is not for 1.13.2. Please test with latest versions for the correct minecraft version

**Comment by RedstoneFuture** [comment] 2019-05-04 13:44
Ouh ok.. Sorry!

new test: with PlotSquared-19.5.2-5796db5-274 in 1.13.2

Is this planed that I can only use '/p list shared' with the plots they are I added or  trusted?
A other player can't use '/p list shared Testplayer' to see the list of plots they Testplayer was added or trusted.

**Comment by AeSix** [comment] 2019-08-10 17:29
Using Spigot 1.13.2 and P2 4.318, I've tested this:

1) /plot list shared -  results in showing the issuing player a list of all plots they are added/trusted to by other players.  
2) /plot list <player> - shows a list of plots for that player.
3) /plot list shared <player> - results in the same functional output as /plot list shared
Adding additional players also yields the same result as /plot list shared.
4) /plot list <player> shared - this outputs the same as /plot list <player>

if the /plot list sub-commands are supposed to take multiple arguments, it's failing to do so.  Only the command (/plot) subcommand (list) and the first argument for list is taken and used. 

According to dordsor21, this is a bug.  I'm uncertain if Sauilitired and MattBDev see this as "by design" or not however. 

additionally:
```/plot list```  &  ```/plot list mine```  - results in the same list (redundant)
```/plot shared``` gives ***useful*** information for /plot list 
```/plot list help``` does not show anything useful.

**Comment by AeSix** [comment] 2019-08-13 20:14
@RedstoneFuture I'm closing this ticket, as according to the command handler for "/p list" this is expected behavior as designed, as there is no handler for any arguments past "shared"
here: https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/commands/ListCmd.java

This should be put in as a suggestion on that github project.

**Closed by AeSix** 2019-08-13 20:14 UTC
Labels: 1.12.x, 1.13.x, Approved, [!] Bug, [?] help wanted
