### ISSUE TITLE
BUG /plot swap returns the original plot owners after restart

### ISSUE THREAD

**Issue by Dad3** [IntellectualSites/PlotSquared#2282] opened 2019-02-25 18:33 UTC
**Debug paste link:**
https://incendo.org/paste/view/0dd2befb90b54ed78b91c8b43209d5c9

**Description of the problem:** 
I tested a few times to make sure. /plot swap works fine and swaps the plots and owners, but after a restart, it unswaps the owners of the plot. This is an old issue that was closed and now reopened.
I have not tested this on 1.13

**How to replicate:** 
Use /plot swap on different plot owners. Then restart the server and you'll see it unswaps the plot owners.

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment] 2019-07-31 11:44
hey @Dad3 is this still an issue with build 773 from here:
https://ci.athion.net/view/Everything/job/PlotSquared-Legacy/

If you're not longer experiencing the issue, please close the ticket.  There's been 176 builds since this issue was originally reported, and a lot of "minor tweaks" "fixes" etc in the changelog.  

I've updated my 1.12.2 server to 1.13.2 and thus cannot test *this* issue.

**Comment by AeSix** [comment] 2019-07-31 12:02
I have confirmed an issue with */plot swap* on 1.13.2 w/ P2 4.305:
Adding here because of the similarities and ultimately a duplicate issue. 

When swapping plots, plot1 (the plot the command is issued on) copies over to plot2 properly.  However, plot2 contents are not properly duplicated to plot1^, only partially. 
+ plot1 and plot2 owners are swapped in /p i and with hologram
- The plot signs are not changed.
- There is error output in the console (as seen below)

Upon restart of the server:
+ plot1^'s original contents are available on plot2 (as should be)
- plot1 contains a partial copy of plot2^ (the same copy which was moved during the swap) 
- plot1 and plot2 are assigned to their original owners (reverted to pre swap)
- plot signs reflect current owners (never changed)

to be clear plot1 is missing skulls from plot2^
```
[07:41:37 INFO]: AeSix issued server command: /plot swap 20;5
[07:41:39 INFO]: AeSix issued server command: /p i
[07:41:41 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:41 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:41 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:41 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:41 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:41 INFO]: ( null,null,null )
[07:41:41 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:41 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:41 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:41 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:42 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
[07:41:42 INFO]: ( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )
```

Expected behavior, I believe:
command is issued in plot1
plot1 and plot2 swap contents, owners and signs
plot1^ has an exact duplicate of the previous plot2
plot2^ has an exact duplicate of the previous plot1
These are permanent changes and not reverted by restarts.

**Comment by AeSix** [comment] 2019-08-10 17:07
Spigot 1.13.2 / P2 4.318 / WE7
Just tested again:
Plot contents do not change at all.  Plot owner, members, trusted and flags appear to be swapped.  
The /plot swap functions are now in a worse state than when I initially tested this 10 days ago with 4.305.

**Comment by MothGirlMusic** [comment] 2019-08-25 12:15
was this issue fixed? plots no longer are swappable for me. your issue says you can swap but owners are reverted upon restart.. my issue is that it says plots have been swapped but nothing actually happens.. then the game complains about the plots overlapping. which they dont.. but the error keeps appearing no matter how far out you go

**Comment by AeSix** [comment] 2019-08-25 20:06
These are both symptoms of the same issue.  The developer is aware of the issues, and has been working on the issue in his free time.  The developers are volunteers, and do this work without financial compensation.

**Comment by MothGirlMusic** [comment] 2019-08-25 20:17
i felt it rude the way you said to read through issues first [when creating a new bug only lets you read the first posts of everything with keywords in it.. of which i had no way of knowing they were linked.] so i'm just asking this since there's no real mark up or explaination of why the issues were linked other than you now telling me and otherwise only a single post from 15 days ago.

**Comment by Sauilitired** [comment] 2020-02-24 07:03
**Attempt to reproduce:**

**Setup:**
- Have player one (p1) claim 0;0. Update the plot (set the floor).
- Have player two (p2) claim 0;1. Update the plot (set the floor).

**Swapping:**
- p2 uses `/plot swap 0;0`
_Results:_
- Plot floors are swapped
- Plot owners are swapped.
- Signs are NOT updated.

**Restart:**
- Server is restarted.
__Results:__
- Plot 0;0 is owned by p1
- Plot 0;1 is owned by p2

**Status:**
Confirmed.

**Comment by Sauilitired** [comment] 2020-02-24 10:49
Fixed in v5.

**Closed by Sauilitired** 2020-02-24 10:49 UTC
Labels: 1.12.x, 1.13+, 1.14.x, Spigot, [!] Bug, v5
